var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(c,g,e){if(null==c)throw new TypeError("The 'this' value for String.prototype."+e+" must not be null or undefined");if(g instanceof RegExp)throw new TypeError("First argument to String.prototype."+e+" must not be a regular expression");return c+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,g,e){c!=Array.prototype&&c!=Object.prototype&&(c[g]=e.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(c,g,e,f){if(g){e=$jscomp.global;c=c.split(".");for(f=0;f<c.length-1;f++){var l=c[f];l in e||(e[l]={});e=e[l]}c=c[c.length-1];f=e[c];g=g(f);g!=f&&null!=g&&$jscomp.defineProperty(e,c,{configurable:!0,writable:!0,value:g})}};
$jscomp.polyfill("String.prototype.startsWith",function(c){return c?c:function(c,e){var f=$jscomp.checkStringArgs(this,c,"startsWith");c+="";var g=f.length,m=c.length;e=Math.max(0,Math.min(e|0,f.length));for(var h=0;h<m&&e<g;)if(f[e++]!=c[h++])return!1;return h>=m}},"es6","es3");
var Utils=function(){var c=[],g=[],e=[],f=null,l=navigator.userAgent.indexOf("Firefox");/chrome/.test(navigator.userAgent.toLowerCase());var m=navigator.userAgent.indexOf("Edge"),h,k,d,n,q="mixi.jp mmall.jp mixi.at mplace.jp mixi.co.jp www.find-job.net mreco.jp mreco0.jp mixi-nenga.jp".split(" ");return{IsSAEnabled:function(){0==n&&void 0!=(window.BubbleHide&&window.MoveBubble&&window.ShowBubble&&window.pop)&&(n=!0);return n},ResetSAEnabled:function(){n=!1},getSAProtocol:function(){return-1!=l?new RegExp(/chrome:\/\/saff\/content/):
new RegExp(/^(sacore:|siteadvisor:)/)},getSADetectInterval:function(){return 100},getSADetectCnt:function(){return 30},LTrim:function(a){for(var b=0;b<a.length&&(" ">=a.charAt(b)||"\u007f"<a.charAt(b));b++);return a.substring(b,a.length)},RTrim:function(a){for(var b=a.length-1;0<=b&&" ">=a.charAt(b);b--);return a.substring(0,b+1)},Trim:function(a){return this.LTrim(this.RTrim(a))},getFormatLink:function(a){if(!a.match("^http")){var b=a.indexOf("-");if(0==b||-1!=l&&1==b)a=a.slice(b+1);a=this.Trim(a);
a.match("^http")||(a="http://"+a)}return a},getSearchText:function(){return c},getSearchNodes:function(){return g},getSearchFlags:function(){return e},clearAll:function(a){c=[];g=[];e=[];return!0},execSearchQuery:function(a,b){if("undefined"==typeof a)return!1;"undefined"==typeof b&&(b="normal");for(h=document.evaluate(a,document,null,0,null);k=h.iterateNext();)d=k,c.push(d.href),g.push(d),e.push(b);return!0},excludeMixiDomain:function(a){for(x in q)if(-1!=a.indexOf(q[x]))return!1;return!0},execMixiSearchQuery:function(a,
b){if("undefined"==typeof a)return!1;"undefined"==typeof b&&(b="normal");for(h=document.evaluate(a,document,null,0,null);k=h.iterateNext();)d=k,-1!=d.href.indexOf("redirect_page")?(a=d.href.split("&")[1].split("=")[1],this.excludeMixiDomain(a)&&(c.push(d.href),g.push(d),e.push(b))):this.excludeMixiDomain(d.href)?(c.push(d.href),g.push(d),e.push(b)):-1!=d.href.indexOf("http://mixi.jp/redirect_check.pl")&&(a=d.href.split("url=")[1].split("&")[0],this.excludeMixiDomain(a)&&(c.push(a),g.push(d),e.push(b)));
return!0},execMixiDirectSearchQuery:function(a,b){if("undefined"==typeof a||!this.execMixiSearchQuery(a,b))return!1;for(a=0;a<c.length;a++)-1!=c[a].indexOf("&url=")&&(b=c[a].split("&")[1].split("="),-1==b[1].indexOf("mixi.jp")&&-1==b[1].indexOf("mmall.jp")&&(c[a]=b[1]));return!0},execNodeTextQuery:function(a,b,f){var d=[],p=[];if("undefined"==typeof a||"undefined"==typeof b)return!1;this.GetNodeColl(a,d);if(0==d.length)return!1;this.GetTextColl(b,p);if(d.length==p.length){for(i=0;i<d.length;i++)c.push(p[i]),
g.push(d[i]),e.push(f);return!0}return!1},execNodeTextQueryforBaiduPromotion:function(a,b,d){if(this.execNodeTextQuery(a,b,d)){for(a=0;a<c.length;a++)if(-1!=c[a].indexOf(" "))for(b=c[a].split(" "),j=0;j<b.length;j++)if(""!=b[j]){c[a]=b[j];break}return!0}return!1},execBaiduPromotionQuery:function(a,b){return"undefined"!=typeof a&&"undefined"==typeof b?this.execSearchQuery(a,"baidupromotion"):this.execNodeTextQueryforBaiduPromotion(a,b,"baidupromotion")},execTopBtmSponsQuery:function(a,b){return"undefined"!=
typeof a&&"undefined"==typeof b?this.execSearchQuery(a,"topbottom"):this.execNodeTextQuery(a,b,"topbottom")},execRightSponsQuery:function(a,b){return"undefined"!=typeof a&&"undefined"==typeof b?this.execSearchQuery(a,"right"):this.execNodeTextQuery(a,b,"right")},GetNodeColl:function(a,b){for(h=document.evaluate(a,document,null,0,null);k=h.iterateNext();)d=k,b.push(d)},GetTextColl:function(a,b){for(h=document.evaluate(a,document,null,0,null);k=h.iterateNext();)d=k,b.push(d.innerText||d.textContent)},
executeXPathSponsorAttrRemoveQuery:function(a,b){for(h=document.evaluate(a,document,null,0,null);k=h.iterateNext();)d=k,d.removeAttribute(b)},getImageSize:function(a){var b={};-1!=a.toLowerCase().indexOf("nortoncertified")?b.iWidth=62:-1==a.toLowerCase().indexOf("shop")?b.iWidth=46:b.iWidth=65;b.iHeight=15;return b},createImage:function(a){response=document.createElement("img");response.className="l sb-l";var b=Shasta.getLinkSrcImg(a);response.src=Shasta.getResProtocol()+b;response.id=Shasta.getLinkId(a);
response.style.padding="0px";response.style.border="none";response.style.textDecoration="none";response.style.cssText="position:relative; *position:static; *zoom:1;";response.style.top="2px";response.style.cursor="pointer";0>m&&0<response.width?(response.style.width=response.width+"px",response.style.height=response.height+"px"):(response.style.width="16px",response.style.height="16px");response.addEventListener("mouseover",function(b){coShasta(this,Shasta.getURLObject(a),a,Utils.getMouseOffset(b,
this))},!1);document.addEventListener("mouseout",function(b){b=b?b:window.event;(b=b.relatedTarget||b.toElement)&&"HTML"!=b.nodeName||coShastaMouseLeave(this,a)},!1);response.addEventListener("mouseup",function(b){coShastaMouseUp(this,a,b.button)},!1);document.addEventListener("DOMMouseScroll",function(){coShastaScroll(this,a)},!1);document.addEventListener("click",function(){coShastaMouseClick(this,a)},!1);return response},getMouseOffset:function(a,b){if("undefined"==typeof a||"undefined"==typeof b)return"-1,-1";
b={};b.x=a.screenX+20-window.screenX;b.y=a.screenY-105-window.screenY;b.x-=a.offsetX;b.y-=a.offsetY;return b},IsIEDocumentMode8OrBetter:function(){if(null!=f)return!f;f=!1;if(-1!=navigator.userAgent.search(/MSIE [67]/))return f=!0,!f;for(var a=document.getElementsByTagName("meta"),b=0;b<a.length;b++)if(-1!=a[b].httpEquiv.search("X-UA-Compatible")&&"IE=7"==a[b].content){f=!0;break}f||7!=document.documentMode||(f=!0);return!f},IsIEQuirkMode:function(){return 5==document.documentMode&&-1!=navigator.userAgent.indexOf("MSIE")},
isAlreadyAnnotated:function(a){if(SymBfw.utils.isNil(a))return!0;var b=null;switch(SymBfw.globals.BROWSER){case "Chrome":b="chrome-extension://";break;case "Firefox":b="moz-extension://";break;case "Edge":b="ms-browser-extension://";break;case "Safari":b="safari-extension://"}var c=!1;a=a.getElementsByTagName("img");for(var d=0;d<a.length;d++)if(!0===a[d].src.startsWith(b)){c=!0;break}return c}}}();
