var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,c,g){if(b){c=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var h=a[g];h in c||(c[h]={});c=c[h]}a=a[a.length-1];g=c[a];b=b(g);b!=g&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof h?a:new h(function(b,f){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var g=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){g(a,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var f=a[b];a[b]=null;try{f()}catch(p){this.asyncThrow_(p)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var h=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(f){b.reject(f)}};h.prototype.createResolveAndReject_=
function(){function a(a){return function(d){f||(f=!0,a.call(b,d))}}var b=this,f=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};h.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof h)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};h.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(f){this.reject_(f);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};h.prototype.reject_=function(a){this.settle_(2,a)};h.prototype.fulfill_=function(a){this.settle_(1,a)};h.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};h.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)e.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var e=new b;h.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};h.prototype.settleSameAsThenable_=function(a,b){var f=this.createResolveAndReject_();try{a.call(b,f.resolve,f.reject)}catch(p){f.reject(p)}};h.prototype.then=function(a,b){function f(a,b){return"function"==typeof a?function(b){try{c(a(b))}catch(u){d(u)}}:
b}var c,d,e=new h(function(a,b){c=a;d=b});this.callWhenSettled_(f(a,c),f(b,d));return e};h.prototype.catch=function(a){return this.then(void 0,a)};h.prototype.callWhenSettled_=function(a,b){function f(){switch(c.state_){case 1:a(c.result_);break;case 2:b(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?e.asyncExecute(f):this.onSettledCallbacks_.push(f)};h.resolve=c;h.reject=function(a){return new h(function(b,f){f(a)})};h.race=function(a){return new h(function(b,
f){for(var e=$jscomp.makeIterator(a),d=e.next();!d.done;d=e.next())c(d.value).callWhenSettled_(b,f)})};h.all=function(a){var b=$jscomp.makeIterator(a),f=b.next();return f.done?c([]):new h(function(a,d){function e(b){return function(f){g[b]=f;p--;0==p&&a(g)}}var g=[],p=0;do g.push(void 0),p++,c(f.value).callWhenSettled_(e(g.length-1),d),f=b.next();while(!f.done)})};return h},"es6","es3");
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(g,h){function e(a){a.done?g(a.value):Promise.resolve(a.value).then(b,c).then(e,h)}e(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var g=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(g);if(!g.done)return this.context_.stop_(),g;var h=g.value}catch(e){return this.context_.yieldAllIterator_=null,this.context_.throw_(e),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,h);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){$jscomp.generator.Generator_.prototype=a.prototype;return new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b))};
$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var g=a.length,h=0;h<g;h++){var e=a[h];if(b.call(c,e,h,a))return{i:h,v:e}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},b=Object.create(new $jscomp.global.Proxy(a,{get:function(c,g,h){return c==a&&"q"==g&&h==b}}));return!0===b.q}catch(c){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();
$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill("WeakMap",function(a){function b(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),f=Object.seal({}),c=new a([[b,2],[f,3]]);if(2!=c.get(b)||3!=c.get(f))return!1;c.delete(b);c.set(f,4);return!c.has(b)&&4==c.get(f)}catch(d){return!1}}function c(a){$jscomp.owns(a,h)||$jscomp.defineProperty(a,h,{value:{}})}function g(a){var b=Object[a];b&&(Object[a]=function(a){c(a);return b(a)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;
var h="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");g("seal");var e=0,k=function(a){this.id_=(e+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};k.prototype.set=function(a,b){c(a);if(!$jscomp.owns(a,h))throw Error("WeakMap key fail: "+a);a[h][this.id_]=b;return this};k.prototype.get=function(a){return $jscomp.owns(a,h)?a[h][this.id_]:void 0};k.prototype.has=
function(a){return $jscomp.owns(a,h)&&$jscomp.owns(a[h],this.id_)};k.prototype.delete=function(a){return $jscomp.owns(a,h)&&$jscomp.owns(a[h],this.id_)?delete a[h][this.id_]:!1};return k},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a($jscomp.makeIterator([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?!1:!0}catch(x){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;$jscomp.initSymbol();$jscomp.initSymbolIterator();var c=new WeakMap,g=function(a){this.data_={};this.head_=k();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};g.prototype.set=function(a,b){var d=h(this,a);d.list||(d.list=this.data_[d.id]=[]);d.entry?d.entry.value=b:(d.entry={next:this.head_,previous:this.head_.previous,head:this.head_,
key:a,value:b},d.list.push(d.entry),this.head_.previous.next=d.entry,this.head_.previous=d.entry,this.size++);return this};g.prototype.delete=function(a){a=h(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};g.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=k();this.size=0};g.prototype.has=function(a){return!!h(this,a).entry};
g.prototype.get=function(a){return(a=h(this,a).entry)&&a.value};g.prototype.entries=function(){return e(this,function(a){return[a.key,a.value]})};g.prototype.keys=function(){return e(this,function(a){return a.key})};g.prototype.values=function(){return e(this,function(a){return a.value})};g.prototype.forEach=function(a,b){for(var d=this.entries(),c;!(c=d.next()).done;)c=c.value,a.call(b,c[1],c[0],this)};g.prototype[Symbol.iterator]=g.prototype.entries;var h=function(a,b){var d=b&&typeof b;"object"==
d||"function"==d?c.has(b)?d=c.get(b):(d=""+ ++n,c.set(b,d)):d="p_"+b;var e=a.data_[d];if(e&&$jscomp.owns(a.data_,d))for(a=0;a<e.length;a++){var f=e[a];if(b!==b&&f.key!==f.key||b===f.key)return{id:d,list:e,index:a,entry:f}}return{id:d,list:e,index:-1,entry:void 0}},e=function(a,b){var d=a.head_;return $jscomp.iteratorPrototype(function(){if(d){for(;d.head!=a.head_;)d=d.previous;for(;d.next!=d.head;)return d=d.next,{done:!1,value:b(d)};d=null}return{done:!0,value:void 0}})},k=function(){var a={};return a.previous=
a.next=a.head=a},n=0;return g},"es6","es3");
$jscomp.polyfill("Set",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_SET||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a($jscomp.makeIterator([b]));if(!c.has(b)||1!=c.size||c.add(b)!=c||1!=c.size||c.add({x:4})!=c||2!=c.size)return!1;var e=c.entries(),k=e.next();if(k.done||k.value[0]!=b||k.value[1]!=b)return!1;k=e.next();return k.done||k.value[0]==b||4!=k.value[0].x||k.value[1]!=k.value[0]?!1:e.next().done}catch(n){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;$jscomp.initSymbol();$jscomp.initSymbolIterator();var c=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.map_.size};c.prototype.add=function(a){this.map_.set(a,a);this.size=this.map_.size;return this};c.prototype.delete=function(a){a=this.map_.delete(a);this.size=this.map_.size;return a};c.prototype.clear=function(){this.map_.clear();
this.size=0};c.prototype.has=function(a){return this.map_.has(a)};c.prototype.entries=function(){return this.map_.entries()};c.prototype.values=function(){return this.map_.values()};c.prototype.keys=c.prototype.values;c.prototype[Symbol.iterator]=c.prototype.values;c.prototype.forEach=function(a,b){var c=this;this.map_.forEach(function(e){return a.call(b,e,e,c)})};return c},"es6","es3");
$jscomp.polyfill("Object.values",function(a){return a?a:function(a){var b=[],g;for(g in a)$jscomp.owns(a,g)&&b.push(a[g]);return b}},"es8","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var h=b.length;c=c||0;for(0>c&&(c=Math.max(c+h,0));c<h;c++){var e=b[c];if(e===a||Object.is(e,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6","es3");
(function(a){(a.SafeWeb=a.SafeWeb||{}).constants={SHASTA_URL:"https://ratings-wrs.symantec.com",SHASTA_LOOKUP_PATH:"brief",DEFAULT_FULL_REPORT_URL:"https://safeweb.norton.com/report/show",HTTP_PROTOCOL:"http",HTTPS_PROTOCOL:"https",PII_SUBMISSION_TIMEOUT:2E3,SCAM_INSIGHT_BLOCK_PAGE_PATH:"content/ui/scam-insight-block-page.html",BLOCK_PAGE_PATH:"content/ui/blockedPage.html",ROOT_NODE:{TAG_NAME:"symantec",VERSION_ATTR:"v",CACHE_POSITIVE_ATTR:"cacheP",CACHE_NEGATIVE_ATTR:"cacheN"},PII_FLAGS:{EXIT_SITE:0,
CONTINUE_TO_SITE:1,SUPPRESSED_DUE_TO_SILENTMODE:2,SUPPRESSED_DUE_TO_HTTPS:4},PII_SUBMISSION_STATUS:{SUCCESS:"Success",FAILURE:"Fail"},SITE_NODE:{TAG_NAME:"site",CANONICAL_SITE_ID_ATTR:"id",COMBINED_RATING_ATTR:"r",SECURITY_RATING_ATTR:"sr",BUSINESS_RATING_ATTR:"br",CACHE_ATTR:"cache",PII_ENABLE_ATTR:"piien",PII_POLICY_HTTPS:"piipolhttps",PII_POLICY_ID:"piipolid",PII_POLICY_FIELD_TYPE:"piipolft"},WRS_RATINGS:{UNKNOWN_SITE:"u",BAD_SITE:"b",WARNING_SITE:"w",GOOD_SITE:"g",NORTON_SECURE_SITE:"r",PII_NOT_ENABLED:"n",
PII_ENABLED:"y",PII_SILENCE:"s"},ANNOYANCE_FACTORS_KEYS:{PUAPP:!0,HRDUN:!0,JOKE:!0,MLAPP:!0,TRCKW:!0,TPSQT:!0,PPCNA:!0,HACK:!0,SPAM:!0,SWBPL:!0},PII_FACTORS_KEYS:{PIIAGE:"age",PIIPOP:"pop"},PII_POLICY_HTTPS_KEYS:{DONTCARE:"dc",HTTPS:"h"},IDENTITY_THREATS_KEYS:{MLWR:!0,MBCHG:!0,RMTA:!0,PHISH:!0,BDOOR:!0,ISTLR:!0,DIAL:!0,DLDR:!0,SPWR:!0},SHOPPING_RISKS_KEYS:{CTFGS:!0,RCGS:!0,REPLC:!0},COMPUTER_THREATS_KEYS:{COHD:!0,ADWR:!0,VIRUS:!0,WORM:!0,SRISK:!0,BREXP:!0,MLWR:!0,MBCHG:!0,HEUR:!0,ELTMS:!0,TRJN:!0},
SITE_FACT_NODE:{TAG_NAME:"d",REPORTED_BY_KEY:"reported_by",SRC_KEY:"src",ID_KEY:"id"},SITE_FACT_IDS:{PRIVACY_POLICY_APPROVED:"privacy policy approved",NETWORK_SCANNING_SERVICE:"network scanning service",SSL_CA_NAME:"ssl CA name",AUTHORIZED_RESELLER:"Authorized Reseller",CERTIFIED_BUSINESS:"certified business",VERISIGN_TRUSTED:"VRTRU",VERISIGN_SSL:"VRSSL"},SITE_FACT_SOURCES:{SRC_BUYSAFE:"BUYSAFE",SRC_VERISIGN:"Verisign",SRC_MARK_MONITOR:"MARKMONITOR"},ATTRIBUTE_COUNT:"cnt",CACHE_LIMIT:1E3,RATING_TYPE:{WCID_HEURISTICS:1,
WCID_CHECK_URL:2,SAFEWEB:3,SCAM_INSIGHT:4},MESSAGES:{WAX_FIELDS_FOUND:"45E6BAD1-9F79-4E16-BA3A-1F77AA21EAC9",PROCESS_PAGE_FOR_SCAM_FIELDS:"FEDA41BC-73DC-4F99-A2CF-B5589CF2D0F8",TOP_FRAME_UNLOADED:"E5C199FF-A74B-414F-803C-4C7030C0E573"},IS_SCAM_INSIGHT_ENABLED:!0,performanceReporter:{COMPONENT:{SCAM_INSIGHT:"scam_insight"},TYPE:{INIT:"init",PII_PROTO_SUBMISSION:"_piiProtoSubmission",CALCULATE_SCAM_RATING:"_calculateScamInsightRating",HANDLE_PII_RATING:"_handlePIIEnabledRating",SET_WRS_RESPONSE:"setWrsResponse",
HANDLE_MESSAGE:"_handleMessage",HANDLE_MESSAGE_CALLBACK:"_handleScamPageFoundCallback",HANDLE_CACHE_RESPONSE:"_handleCacheResponse",SEND_PII_SUBMISSION:"sendPIISubmission",COLLECT_PII_FIELDS:"_collectPIIFields",TOP_FRAME_UNLOADED:"topFrameUnloaded",ADD_MUTATION_OBSERVER:"_addBodyMutationObserver",FIELD_FOUND_CALLBACK:"handleFieldsFoundCallback"}},SCAM_INSIGHT_RESULT:{UNTESTED:0,SUSPICIOUS_PAGE:1,SUSPICIOUS_NO_BLOCK_PAGE:2,NOT_SUSPICIOUS_PAGE:3},SCAM_INSIGHT_RATING_KEY:"scamRating"}})(executionContext);
(function(a){a.SafeWeb.telemetryWrapper=function(a,c){var b={},h=a.utils.isString,e=a.telemetryConstants;b.TELEMETRY_CATEGORY={SCAM_INSIGHT:"Scam_Insight"};b.actionType={PROTO:{PII_SUBMISSION:"PII_Submission"}};b.sendPIISubmissionStatusEvent=function(a){if(!h(a))return null;b.send(b.TELEMETRY_CATEGORY.SCAM_INSIGHT,b.actionType.PROTO.PII_SUBMISSION,a)};b.send=function(b,c,f){if(!h(b)||!h(c)||!h(f))return null;var g={};g[e.parameters.HIT_TYPE]=e.HIT_TYPE.EVENT;g[e.parameters.CATEGORY]=b;g[e.parameters.ACTION]=
c;g[e.parameters.LABEL]=f;(a.telemetry||a.telemetryProxy).send(g)};return b}(a.SymBfw,a.SafeWeb)})(executionContext);
(function(a){a.SafeWeb.Rating=function(a){var b=a.utils.isNil,g=a.utils.isArray,h=SafeWeb.constants,e=a.utils,k=a.localizer,n=a.utils.isInteger,f=a.utils.isString,p=SafeWeb.constants,d=function(c){if(b(c))throw Error("Input dictionary cannot be null");var e=d.ratingSchema,f;for(f in e){var g=e[f],h=c[f];if(b(h)){if(g.isRequired)throw Error("Cannot find value for key "+f+" in the input dictionary.");if(b(g.defaultValue))throw Error("Default value has not been supplied in the Schema.");this[f]=g.defaultValue}else{g=
g.typeChecker;if(!1===g(h))throw Error("Input value for key "+f+" does not match schema.");this[f]=h}}this.id=a.utils.createNewGuid()};d._checkPIISchema=function(a){return f(a.piiEnable)?p.WRS_RATINGS.PII_ENABLED!==a.piiEnable&&p.WRS_RATINGS.PII_SILENCE!==a.piiEnable?!0:f(a.piiPolHttps)&&f(a.piiPolID)&&g(a.piiFieldType)&&n(a.age)&&n(a.pop)?!0:!1:!1};d.ratingSchema={computerThreats:{isRequired:!1,typeChecker:e.isInteger,defaultValue:0},annoyanceFactors:{isRequired:!1,typeChecker:e.isInteger,defaultValue:0},
identityThreats:{isRequired:!1,typeChecker:e.isInteger,defaultValue:0},shoppingRisks:{isRequired:!1,typeChecker:e.isInteger,defaultValue:0},phishingThreats:{isRequired:!1,typeChecker:e.isInteger,defaultValue:0},siteRating:{isRequired:!0,typeChecker:e.isInteger},fullURL:{isRequired:!0,typeChecker:e.isString},normalizedURL:{isRequired:!0,typeChecker:e.isString},cacheTime:{isRequired:!1,typeChecker:e.isInteger,defaultValue:0},piiAttributes:{isRequired:!1,typeChecker:d._checkPIISchema,defaultValue:{piiEnable:p.WRS_RATINGS.PII_NOT_ENABLED}},
scamRating:{isRequired:!1,typeChecker:e.isInteger,defaultValue:h.SCAM_INSIGHT_RESULT.UNTESTED}};d.prototype.getComputerThreats=function(){return this.computerThreats};d.prototype.getAnnoyanceFactors=function(){return this.annoyanceFactors};d.prototype.getIdentityThreats=function(){return this.identityThreats};d.prototype.getShoppingRisks=function(){return this.shoppingRisks};d.prototype.getPhishingThreats=function(){return this.phishingThreats};d.prototype.getFullReportURL=function(){return h.DEFAULT_FULL_REPORT_URL+
"?url="+this.getFullURL()+"&ulang="+k.getLocale()};d.prototype.getSiteRating=function(){return this.siteRating};d.prototype.getFullURL=function(){return this.fullURL};d.prototype.getNormalizedURL=function(){return this.normalizedURL};d.prototype.getID=function(){return this.id};d.prototype.getCacheTime=function(){return this.cacheTime};d.prototype.getPIIEnValue=function(){return this.piiAttributes.piiEnable};d.prototype.getPIIPolID=function(){return b(this.piiAttributes.piiPolID)?null:this.piiAttributes.piiPolID};
d.prototype.getPIIHTTPS=function(){return b(this.piiAttributes.piiPolHttps)?null:this.piiAttributes.piiPolHttps};d.prototype.getPIIFieldType=function(){return b(this.piiAttributes.piiFieldType)?[]:this.piiAttributes.piiFieldType};d.prototype.getPIIAge=function(){return b(this.piiAttributes.age)?0:this.piiAttributes.age};d.prototype.getPIIPop=function(){return b(this.piiAttributes.pop)?0:this.piiAttributes.pop};d.prototype.getScamRating=function(){return this.scamRating};d.prototype.serialize=function(){return JSON.stringify(this)};
d.SITE_RATING={SW_INVALID_STATE:0,SW_TRUSTED_STATE:1,SW_NEUTRAL_STATE:2,SW_KNOWN_PHISHING_STATE:3,SW_SUSPECTED_PHISHING_STATE:4,SW_KNOWN_MALICIOUS_STATE:5,SW_CAUTION_MALICIOUS_STATE:6,SW_NORTON_CERTIFIED:7,SW_TRUSTED_TRANSACTION_STATE:8,SW_UNTRUSTED_TRANSACTION_STATE:9,SW_PAGE_BAD_UNTRUSTED_TRANSACTION_STATE:10,SW_DISABLED_STATE:11,SW_UNLICENSED_STATE:12,SW_ERROR_STATE:13,SW_PENDING_STATE:14,SW_MAX_STATE:15};return d}(a.SymBfw)})(executionContext);
(function(a){a.SafeWeb.WrsParser=function(a){var b=a.utils.isNil,g=a.utils.isntNil,h=a.utils.isEmptyObject,e=SafeWeb.constants,k=a.logger,n=SafeWeb.Rating;a=function(){this._rootDict={cacheP:600,cacheN:600}};a.prototype.parseWRSResponse=function(a,c){if(b(a))return null;if(b(c))throw Error("URL Array cannot be null.");a=$(a);a=this.parseRootNode(a);return b(a)?null:this.parseSiteInformation(a,c)};a.prototype.parseSiteInformation=function(a,c){a=a.find(e.SITE_NODE.TAG_NAME);var d=a.length;if(0===d)return null;
if(c.length!==d)return k.error("Lengths of input URL Array("+c.length+") and Shasta results("+d+") do not match."),null;for(var f=[],g=0;g<d;g++){var p=a[g],r=p.attributes,u=r.length,m={},t=!1,l={};m.fullURL=c[g];var v=0;for(v=0;v<u;v++){var q=r.item(v);switch(q.nodeName){case e.SITE_NODE.CANONICAL_SITE_ID_ATTR:m.normalizedURL=q.value;break;case e.SITE_NODE.COMBINED_RATING_ATTR:m.combinedRating=q.value;break;case e.SITE_NODE.SECURITY_RATING_ATTR:m.securityRating=q.value;t=!0;break;case e.SITE_NODE.BUSINESS_RATING_ATTR:m.shoppingRating=
q.value;break;case e.SITE_NODE.CACHE_ATTR:m.cacheTime=Number(q.value);break;case e.SITE_NODE.PII_ENABLE_ATTR:l.piiEnable=q.value;break;case e.SITE_NODE.PII_POLICY_HTTPS:l.piiPolHttps=q.value;break;case e.SITE_NODE.PII_POLICY_ID:l.piiPolID=q.value;break;case e.SITE_NODE.PII_POLICY_FIELD_TYPE:q=q.value,"*"===q?l.piiFieldType=["*"]:(q=q.split(",").map(Number),l.piiFieldType=q.filter(function(a){return!isNaN(a)}))}}m.piiAttributes=l;h(m.piiAttributes)&&(m.piiAttributes.piiEnable=e.WRS_RATINGS.PII_NOT_ENABLED);
b(m.normalizedURL)&&(m.normalizedURL="");b(m.combinedRating)&&(m.combinedRating=e.WRS_RATINGS.UNKNOWN_SITE);b(m.securityRating)&&(m.securityRating=e.WRS_RATINGS.UNKNOWN_SITE);b(m.shoppingRating)&&(m.shoppingRating=e.WRS_RATINGS.UNKNOWN_SITE);b(m.cacheTime)&&(m.cacheTime=!1===t?this._rootDict.cacheN:this._rootDict.cacheP);m.siteRating=this.getSiteRating(m.securityRating,m.shoppingRating);this.parseSiteAttributes($(p),m);p=new n(m);f.push(p)}return f};a.prototype.parseSiteAttributes=function(a,c){a=
a.children();for(var d=a.length,f=0,h=0,p=0,k=0,n=0;n<d;n++){var m=a.get(n),t=m.nodeName;m=m.attributes;g(e.ANNOYANCE_FACTORS_KEYS[t])&&(h+=Number(m[e.ATTRIBUTE_COUNT].value));g(e.IDENTITY_THREATS_KEYS[t])&&(p+=Number(m[e.ATTRIBUTE_COUNT].value));g(e.SHOPPING_RISKS_KEYS[t])&&(k+=Number(m[e.ATTRIBUTE_COUNT].value));g(e.COMPUTER_THREATS_KEYS[t])&&(f+=Number(m[e.ATTRIBUTE_COUNT].value));g(e.PII_FACTORS_KEYS[t])&&(b(c.piiAttributes)&&(c.piiAttributes={}),c.piiAttributes[e.PII_FACTORS_KEYS[t]]=Number(m[e.PII_FACTORS_KEYS[t]].value))}c.computerThreats=
f;c.annoyanceFactors=h;c.identityThreats=p;c.shoppingRisks=k};a.prototype.getSiteRating=function(a,b){if(a===e.WRS_RATINGS.NORTON_SECURE_SITE)return n.SITE_RATING.SW_NORTON_CERTIFIED;if(a===e.WRS_RATINGS.GOOD_SITE){if(b===e.WRS_RATINGS.GOOD_SITE)return n.SITE_RATING.SW_TRUSTED_TRANSACTION_STATE;if(b===e.WRS_RATINGS.UNKNOWN_SITE)return n.SITE_RATING.SW_TRUSTED_STATE}return a===e.WRS_RATINGS.BAD_SITE?b===e.WRS_RATINGS.BAD_SITE?n.SITE_RATING.SW_PAGE_BAD_UNTRUSTED_TRANSACTION_STATE:n.SITE_RATING.SW_KNOWN_MALICIOUS_STATE:
b===e.WRS_RATINGS.WARNING_SITE||b===e.WRS_RATINGS.BAD_SITE?n.SITE_RATING.SW_UNTRUSTED_TRANSACTION_STATE:a===e.WRS_RATINGS.WARNING_SITE?n.SITE_RATING.SW_CAUTION_MALICIOUS_STATE:n.SITE_RATING.SW_NEUTRAL_STATE};a.prototype.parseRootNode=function(a){a=a.find(e.ROOT_NODE.TAG_NAME);if(0===a.length)return null;for(var b=a[0].attributes,d=b.length,c=0;c<d;c++){var f=b.item(c);switch(f.nodeName){case e.ROOT_NODE.VERSION_ATTR:this._rootDict[e.ROOT_NODE.VERSION_ATTR]=f.value;break;case e.ROOT_NODE.CACHE_POSITIVE_ATTR:this._rootDict[e.ROOT_NODE.CACHE_POSITIVE_ATTR]=
Number(f.value);break;case e.ROOT_NODE.CACHE_NEGATIVE_ATTR:this._rootDict[e.ROOT_NODE.CACHE_NEGATIVE_ATTR]=Number(f.value)}}return a};return a}(a.SymBfw)})(executionContext);
(function(a){a.SafeWeb.connection=function(a){var b={},g=a.utils.isNil,h=a.utils.isFunction,e=a.utils.isArray,k=SafeWeb.constants,n=SafeWeb.WrsParser;b.getResultForURL=function(a,c){if(g(a))throw Error("URL cannot be null");if(!1===h(c))throw Error("Shasta Connection callback cannot be null");var d=encodeURIComponent(SafeWeb.cache.safeURL(a));b.shastaConnection(k.SHASTA_URL+"/"+k.SHASTA_LOOKUP_PATH+"?url="+d,"GET",function(b){var d=b.target.status,e=b.target.responseXML;if(200===d){var f=(new n).parseWRSResponse(e,
[a]);SafeWeb.cache.addRatingsToCache(f);setTimeout(function(){c(d,f)},1)}else setTimeout(function(){c(d,b)},1)})};b.getResultsForURLs=function(a,c){if(!1===e(a))throw Error("URL Array cannot be null");if(0===a.length)throw Error("URL Array length cannot be null");if(!1===h(c))throw Error("Shasta Connection callback cannot be null");var d=k.SHASTA_URL+"/"+k.SHASTA_LOOKUP_PATH,f="",g;for(g in a)f+=a[g]+"\r\n";b.shastaConnection(d,"POST",function(b){var d=b.target.status,e=b.target.responseXML;if(200===
d){var f=(new n).parseWRSResponse(e,a);SafeWeb.cache.addRatingsToCache(f);setTimeout(function(){c(d,f)},1)}else setTimeout(function(){c(d,b)},1)},f)};b.shastaConnection=function(a,b,d,c){if(g(a))throw Error("API URL cannot be null");if(g(b))throw Error("HTTP Method cannot be null");if(!1===h(d))throw Error("Shasta Callback cannot be null");var e=new XMLHttpRequest;e.open(b,a,!0);e.addEventListener("load",function(a){d(a)});e.addEventListener("error",function(a){d(a)});e.setRequestHeader("X-Symc-User-Agent",
"xBP/SafeWeb");e.send(c)};return b}(a.SymBfw)})(executionContext);
(function(a){a=a.SafeWeb.ScamInsightPII=a.SafeWeb.ScamInsightPII||{};var b=dcodeIO.ProtoBuf.newBuilder({})["import"]({"package":"PIIFeatureTelem",options:{optimize_for:"LITE_RUNTIME"},messages:[{name:"ScamInsight_PII_Submission_List",fields:[{rule:"optional",type:"uint32",name:"Version",id:1,options:{"default":1}},{rule:"optional",type:"bytes",name:"Enterprise_GUID",id:2},{rule:"optional",type:"bytes",name:"Machine_GUID",id:3},{rule:"optional",type:"bytes",name:"Machine_CAT",id:4},{rule:"optional",
type:"string",name:"ProductName",id:5,options:{"default":""}},{rule:"optional",type:"string",name:"ProductVersion",id:6,options:{"default":""}},{rule:"repeated",type:"Submission_Type",name:"Submission",id:7}],messages:[{name:"Submission_Type",fields:[{rule:"optional",type:"int64",name:"UTCTime",id:1},{rule:"optional",type:"sint32",name:"LocalTZUTCOffset",id:2},{rule:"optional",type:"string",name:"Site_URL",id:3},{rule:"optional",type:"string",name:"Referrer_URL",id:4},{rule:"optional",type:"string",
name:"FormAction_URL",id:5},{rule:"optional",type:"string",name:"PII_PolicyID",id:6},{rule:"repeated",type:"uint32",name:"Form_Fields",id:7},{rule:"optional",type:"uint32",name:"PII_Flags",id:8}]}]}],enums:[{name:"ScamInsight_PII_FlagValues",values:[{name:"SCAMINSIGHT_PII_CONTINUED_TO_PAGE",id:1},{name:"SCAMINSIGHT_PII_SUPPRESSEDDUETOSILENTMODE",id:2},{name:"SCAMINSIGHT_PII_SUPPRESSEDDUETOHTTPS",id:4}]}]}).build();a.proto=b})(executionContext);
(function(a){a.SafeWeb.piiprotoutils=function(a){var b={},g=SafeWeb.ScamInsightPII.proto.PIIFeatureTelem.ScamInsight_PII_Submission_List,h=g.Submission_Type,e=a.utils.isNil,k=a.utils.isArray,n=a.utils.isEmptyObject,f=a.utils.isString,p=a.utils.urlWithoutQueryParameters,d="1.0.0",w=function(){this.piiSubmissionItem={UNIX_TIME:null,OFFSET_TIME:null,SITE_URL:null,REFERRER_URL:null,FORM_ACTION_URL:null,PII_POLICYID:null,FORM_FIELDS:null,PII_FLAGS:null}};w.prototype.setSubmissionTime=function(){var a=
new Date;this.piiSubmissionItem.UNIX_TIME=a.getTime();this.piiSubmissionItem.OFFSET_TIME=a.getTimezoneOffset()};w.prototype.setSiteUrl=function(a){a=p(a);a=encodeURIComponent(a);this.piiSubmissionItem.SITE_URL=a};w.prototype.isValidPIISubmissionData=function(){return e(this.piiSubmissionItem.UNIX_TIME)||e(this.piiSubmissionItem.OFFSET_TIME)||n(this.piiSubmissionItem.SITE_URL)||!f(this.piiSubmissionItem.SITE_URL)||n(this.piiSubmissionItem.PII_POLICYID)||!f(this.piiSubmissionItem.PII_POLICYID)||!k(this.piiSubmissionItem.FORM_FIELDS)||
e(this.piiSubmissionItem.PII_FLAGS)?!1:!0};b._fillPIIItem=function(a,b){n(a.piiSubmissionItem.REFERRER_URL)||b.setReferrerURL(encodeURIComponent(a.piiSubmissionItem.REFERRER_URL));n(a.piiSubmissionItem.FORM_ACTION_URL)||b.setFormActionURL(encodeURIComponent(a.piiSubmissionItem.FORM_ACTION_URL));var d=dcodeIO.Long.fromNumber(a.piiSubmissionItem.UNIX_TIME);b.setUTCTime(d);b.setLocalTZUTCOffset(a.piiSubmissionItem.OFFSET_TIME);b.setSiteURL(a.piiSubmissionItem.SITE_URL);b.setPIIPolicyID(a.piiSubmissionItem.PII_POLICYID);
b.setFormFields(a.piiSubmissionItem.FORM_FIELDS);b.setPIIFlags(a.piiSubmissionItem.PII_FLAGS)};b.setPIIProductVersion=function(a){if(!f(a))throw Error("Invalid string");d=a};b._createPIIList=function(a){var c=new g,e=new h;c.setVersion(1);c.setProductName("NSSS");c.setProductVersion(d);b._fillPIIItem(a,e);c.setSubmission(e);return c};b.submitShastaPII=function(a){return $jscomp.asyncExecutePromiseGeneratorFunction(function r(){var d,c;return $jscomp.generator.createGenerator(r,function(f){switch(f.nextAddress){case 1:if(!(a instanceof
w))throw Error("Invalid PII Object");if(!a.isValidPIISubmissionData())throw Error("Invalid PII Submission Data");d=b._createPIIList(a);if(e(d))throw Error("PII Creation Failed");c=d.toArrayBuffer();if(e(c))throw Error("Invalid Serialized Message");return f.yield(b._sendPIIDataToShasta(c),2);case 2:return f.return(f.yieldResult)}})})};b._sendPIIDataToShasta=function(b){return $jscomp.asyncExecutePromiseGeneratorFunction(function r(){var d,c,e;return $jscomp.generator.createGenerator(r,function(f){switch(f.nextAddress){case 1:return d=
{"Content-Type":"application/x-protobuf"},c={method:"POST",headers:d,body:b},f.setCatchFinallyBlocks(2),f.yield(fetch("https://shasta-clt.symantec.com/incident-pii/1",c),4);case 4:e=f.yieldResult;if(e.status!==a.constants.httpStatusCodes.OK)throw Error("PII Submission Failed");return f.return();case 2:throw f.enterCatchBlock(),Error("PII Submission Failed");}})})};b.getPIISUbmissionObj=function(){return new w};return b}(a.SymBfw)})(executionContext);
(function(a){a.SafeWeb.cache=function(b){var c=b.utils.isNil,g=b.utils.isntNil,h=b.utils.isEmptyObject,e=b.logger,k=SafeWeb.constants,n=SafeWeb.connection,f={_normalizedURLToRatingsMap:{},_cachedURLs:0,safeURL:function(a){a=new URI(a);return a.protocol()+"://"+a.hostname()+a.pathname()},addRatingsToCache:function(a){if(c(a)||0===a.length)throw Error("Ratings array cannot be null or empty");var b=function(a,b){setTimeout(function(){f.removeRatingFromCache(a)},b)},g;for(g in a){if(f._cachedURLs>=k.CACHE_LIMIT)break;
var h=a[g];if(!c(h)){var n=h.getCacheTime();if(0!==n){var p=h.getNormalizedURL(),u=null;c(p)||0===p.length?(u=f.safeURL(h.getFullURL()),e.error("Normalized URL cannot not be null or empty:"+u)):(c(f._normalizedURLToRatingsMap[p])?f._cachedURLs++:u=f.safeURL(h.getFullURL()),f._normalizedURLToRatingsMap[p]=h,b(p,1E3*n))}}}},removeRatingFromCache:function(a){if(c(a))throw Error("Normalized URL cannot be null");delete f._normalizedURLToRatingsMap[a];f._cachedURLs--},getRatingForURL:function(a,b){var d=
f.ratingForCachedURL(a);g(d)?setTimeout(function(){b(d)},1):n.getResultForURL(a,function(a,d){var c=200===a?d[0]:null;setTimeout(function(){b(c)},1)})},ratingForCachedURL:function(b){if(h(f._normalizedURLToRatingsMap))return null;var d=new URI(b);do{var c=d.hostname(),e=d.domain();var k=d.segment();var n=d.pathname(),p=k.length,m=0;do{k=c+n;k=f._normalizedURLToRatingsMap[k];if(g(k))break;n=n.slice(0,n.lastIndexOf("/"));m++}while(m<p);if(!g(k)){if(!0===d.is("IP")&&(k=f._normalizedURLToRatingsMap[c],
g(k)))break;c=d.subdomain();if(g(c)&&0<c.length){n=c.split(".").length;p=0;do{k=c+"."+e;k=f._normalizedURLToRatingsMap[k];if(g(k))break;c=c.slice(c.indexOf(".")+1,c.length);p++}while(p<n);if(g(k))break}k=e;k=f._normalizedURLToRatingsMap[k]}}while(0);d=null;g(k)&&(d=JSON.parse(JSON.stringify(k)),d.fullURL=b,d=new a.SafeWeb.Rating(d));return d},getRatingsForURLs:function(a,b){var d=[];d.length=a.length;var e={},h=[],k;for(k in a){var p=a[k];if(c(p))d[k]=null;else{var m=f.ratingForCachedURL(p);g(m)?
d[k]=m:(e[h.length]=k,h.push(p))}}0===h.length?setTimeout(function(){b(d)},1):n.getResultsForURLs(h,function(a,c){if(200===a)for(var f in c)d[e[f]]=c[f];setTimeout(function(){b(d)},1)})},updateCacheRatingsForUrl:function(a){if(!c(a)){var b=a.getNormalizedURL();c(b)||0===b.length?e.log("Normalized url for this newRating is null, dont proceed further to alter in this case"):g(f._normalizedURLToRatingsMap[b])&&(f._normalizedURLToRatingsMap[b]=a)}}};return f}(a.SymBfw)})(executionContext);
(function(a){a.SafeWeb.manager=function(a){var b=SafeWeb.cache,g=a.utils.isNil,h=a.utils.isFunction,e={getRatingForURL:function(a,c){if(g(a))throw Error("URL array cannot be null or empty.");if(!1===h(c))throw Error("Callback function cannot be null.");!1===e.validateURL(a)?setTimeout(function(){c(null)},1):b.getRatingForURL(a,c)},getRatingsForURLs:function(a,c){if(g(a)||0===a.length)throw Error("URL array cannot be null or empty.");if(!1===h(c))throw Error("Callback function cannot be null.");for(var f in a)!1===
e.validateURL(a[f])&&(a[f]=null);b.getRatingsForURLs(a,c)},validateURL:function(a){if(g(a))return!1;var b=new URI(a);a=b.protocol();b=b.hostname();return 0===a.length||0===b.length?!1:"http"===a||"https"===a?!0:!1}};return e}(a.SymBfw)})(executionContext);
(function(a){a.SafeWeb.scamInsightUtility=function(a,c){var b=a.utils.urlWithoutQueryParameters,h=a.utils.isEmptyObject,e={};e._viewAnywayCache=new Set;e.addToViewAnywayCache=function(a){h(a)||(a=b(a),e._viewAnywayCache.has(a)||(e._viewAnywayCache.add(a),setTimeout(e._removeFromViewCache,18E5,a)))};e._removeFromViewCache=function(b){a.logger.debug("Removing from view cache : "+b);e._viewAnywayCache.delete(b)};e.isURLInViewAnywayCache=function(a){if(h(a))return!1;a=b(a);return e._viewAnywayCache.has(a)};
return e}(a.SymBfw,a.SafeWeb)})(executionContext);
(function(a){a.SafeWeb.scamInsightMgr=function(a,c){var b=a.extensionAdapter,h=a.utils.isEmptyObject,e=a.utils.isNil,k=a.utils.isntNil,n=a.utils.isArray,f=a.utils.isInteger,p=a.utils.isString,d=c.constants,w=a.telemetrySettings,x=c.piiprotoutils,y=a.utils.urlProtocol,r=a.logger,u=a.utils.isFunction,m=a.performanceReporterFactory,t=c.piiprotoutils,l={initialize:function(){if(d.IS_SCAM_INSIGHT_ENABLED){var a=d.performanceReporter.TYPE.INIT+":"+Date.now();m.reportStartForComponent(d.performanceReporter.COMPONENT.SCAM_INSIGHT,
a);l._processedTabFields=new Map;l._PIISubmissionInfo=new Map;l._scamPageFoundCallback=null;b.addMessageListener(l._handleMessage);b.addTabRemovedEventListener(l._handleTabClose);m.reportStopForComponent(d.performanceReporter.COMPONENT.SCAM_INSIGHT,a)}},registerEventCallback:function(a){if(!u(a))throw Error("Invalid Callback function");l._scamPageFoundCallback=a},setVersion:function(a){if(!p(a))throw Error("Invalid string");t.setPIIProductVersion(a)},_getSITabInfo:function(a){var b=l._processedTabFields.get(a);
e(b)&&(b=new Map,b.set("waxFieldsInfo",new Set),b.set("wrsScamResponse",{}),b.set("matchedFields",new Set),b.set("piiSubmissionTimer",0),b.set("piiFlag",0),b.set("piiSubmitted",!1),b.set("scamInsightBlockPageHandled",!1),l._processedTabFields.set(a,b));return b},_collectPIIFields:function(a,b){if(f(a)&&n(b)&&!(0>=b.length)){var c=d.performanceReporter.TYPE.COLLECT_PII_FIELDS+":"+Date.now();m.reportStartForComponent(d.performanceReporter.COMPONENT.SCAM_INSIGHT,c);var e=l._getSITabInfo(a),h=e.get("waxFieldsInfo"),
g=h.size;b.every(function(a){return h.add(a)});var q=h.size;l._processedTabFields.set(a,e);r.debug("Received WAX fields for tabID : "+a+" arrPIIFields : "+b);r.debug("Processed Tab fields map after wax update : "+a);r.debug(l._processedTabFields.get(a));q>g&&l._calculateScamInsightRating(a);m.reportStopForComponent(d.performanceReporter.COMPONENT.SCAM_INSIGHT,c)}},_getMatchedFields:function(a,b){return e(b)||0===b.size||e(a)||0===a.size?new Set:a.has("*")?b:new Set([].concat($jscomp.arrayFromIterable(a)).filter(function(a){return b.has(a)}))},
_piiProtoSubmission:function(a,b,f){if(!w.isTelemetryEnabled())return null;var g=x.getPIISUbmissionObj();if(h(g)||e(f)||0===f.size)return null;var q=d.performanceReporter.TYPE.PII_PROTO_SUBMISSION+":"+Date.now();m.reportStartForComponent(d.performanceReporter.COMPONENT.SCAM_INSIGHT,q);var v=a.getFullURL();a=a.getPIIPolID();g.setSiteUrl(v);g.setSubmissionTime();g.piiSubmissionItem.PII_FLAGS=b;g.piiSubmissionItem.PII_POLICYID=a;g.piiSubmissionItem.FORM_FIELDS=[].concat($jscomp.arrayFromIterable(f));
x.submitShastaPII(g).then(function(a){r.debug("Protobuf submission successful");c.telemetryWrapper.sendPIISubmissionStatusEvent(d.PII_SUBMISSION_STATUS.SUCCESS)}).catch(function(a){r.debug("Protobuf submission failed - "+a);c.telemetryWrapper.sendPIISubmissionStatusEvent(d.PII_SUBMISSION_STATUS.FAILURE)});m.reportStopForComponent(d.performanceReporter.COMPONENT.SCAM_INSIGHT,q)},getBlockPageData:function(a){if(!f(a))return null;var b=l._PIISubmissionInfo.get(a);if(e(b))return null;var c={},h=b.get("wrsScamResponse");
b.get("piiSubmitted")||(l.sendPIISubmission(d.PII_FLAGS.EXIT_SITE,a),b.set("piiSubmitted",!0),l._PIISubmissionInfo.set(a,b));c.url=h.getFullURL();c.ageScore=h.getPIIAge();c.prevalenceScore=h.getPIIPop();return c},sendPIISubmission:function(a,b){if(!f(b)||!f(a)||-1===Object.values(d.PII_FLAGS).indexOf(a))return null;var c=l._PIISubmissionInfo.get(b);if(e(c))return null;b=d.performanceReporter.TYPE.SEND_PII_SUBMISSION+":"+Date.now();m.reportStartForComponent(d.performanceReporter.COMPONENT.SCAM_INSIGHT,
b);var h=c.get("wrsScamResponse");c=c.get("matchedFields");l._piiProtoSubmission(h,a,c);m.reportStopForComponent(d.performanceReporter.COMPONENT.SCAM_INSIGHT,b)},_sendPIISubmissionSilentRating:function(a){if(!f(a))return null;var b=l._processedTabFields.get(a);if(e(b))return null;var c=b.get("wrsScamResponse"),d=b.get("matchedFields"),h=b.get("piiFlag");l._piiProtoSubmission(c,h,d);b.set("piiSubmitted",!0);l._processedTabFields.set(a,b)},_sendPIISubmissionSilentRatingOnTabClose:function(a){if(!f(a))return null;
var b=l._processedTabFields.get(a);if(e(b))return null;if(!b.get("piiSubmitted")){a=b.get("wrsScamResponse");var c=b.get("piiFlag"),d=b.get("matchedFields");b=b.get("piiSubmissionTimer");l._piiProtoSubmission(a,c,d);clearTimeout(b)}},_calculateScamInsightRating:function(a){if(!f(a))return null;var b=l._processedTabFields.get(a);if(e(b))return null;var c=b.get("waxFieldsInfo"),g=b.get("wrsScamResponse");if(e(c)||0===c.size||h(g))return null;c=[d.SCAM_INSIGHT_RESULT.SUSPICIOUS_PAGE,d.SCAM_INSIGHT_RESULT.SUSPICIOUS_NO_BLOCK_PAGE];
var k=g.getScamRating();if(e(k))throw Error("ScamInsight rating cannot be null");var v=d.performanceReporter.TYPE.CALCULATE_SCAM_RATING+":"+Date.now();m.reportStartForComponent(d.performanceReporter.COMPONENT.SCAM_INSIGHT,v);if(c.includes(k))l._handleCacheResponse(a,g),r.debug("Handled scam rating from cache for tabId : "+a);else{switch(g.getPIIEnValue()){case d.WRS_RATINGS.PII_ENABLED:case d.WRS_RATINGS.PII_SILENCE:l._handlePIIEnabledRating(a,b)}m.reportStopForComponent(d.performanceReporter.COMPONENT.SCAM_INSIGHT,
v)}},_handlePIIEnabledRating:function(a,b){var c=d.performanceReporter.TYPE.HANDLE_PII_RATING+":"+Date.now();m.reportStartForComponent(d.performanceReporter.COMPONENT.SCAM_INSIGHT,c);var f=b.get("waxFieldsInfo"),h=b.get("wrsScamResponse"),g=h.getPIIEnValue(),k=new Set(h.getPIIFieldType());if(e(k)||0===k.size)return null;f=l._getMatchedFields(k,f);if(e(f)||0===f.size)return l._updateCachedScamRating(h,d.SCAM_INSIGHT_RESULT.NOT_SUSPICIOUS_PAGE),null;b.set("matchedFields",f);l._processedTabFields.set(a,
b);r.debug("Processed Tab fields map after matched fields update : "+a);r.debug(l._processedTabFields.get(a));f=h.getPIIHTTPS();e(f)&&(f=d.PII_POLICY_HTTPS_KEYS.DONTCARE);var q=h.getFullURL();k=y(q);e(k)&&(k=d.HTTP_PROTOCOL);g===d.WRS_RATINGS.PII_ENABLED&&f===d.PII_POLICY_HTTPS_KEYS.DONTCARE||g===d.WRS_RATINGS.PII_ENABLED&&f===d.PII_POLICY_HTTPS_KEYS.HTTPS&&k===d.HTTP_PROTOCOL?(l._handleScamPageFoundCallback(a,q),l._updateCachedScamRating(h,d.SCAM_INSIGHT_RESULT.SUSPICIOUS_PAGE)):(q=0,g===d.WRS_RATINGS.PII_ENABLED&&
f===d.PII_POLICY_HTTPS_KEYS.HTTPS&&k===d.HTTPS_PROTOCOL&&(q=d.PII_FLAGS.SUPPRESSED_DUE_TO_HTTPS),g===d.WRS_RATINGS.PII_SILENCE&&(q=d.PII_FLAGS.SUPPRESSED_DUE_TO_SILENTMODE),b.get("piiSubmissionTimer")||(g=setTimeout(l._sendPIISubmissionSilentRating,d.PII_SUBMISSION_TIMEOUT,a),b.set("piiFlag",q),b.set("piiSubmissionTimer",g),l._processedTabFields.set(a,b)),l._updateCachedScamRating(h,d.SCAM_INSIGHT_RESULT.SUSPICIOUS_NO_BLOCK_PAGE));m.reportStopForComponent(d.performanceReporter.COMPONENT.SCAM_INSIGHT,
c)},setWrsResponse:function(a,c){var f=d.performanceReporter.TYPE.SET_WRS_RESPONSE+":"+Date.now();m.reportStartForComponent(d.performanceReporter.COMPONENT.SCAM_INSIGHT,f);if(!e(a)&&!h(c)){r.debug("WRS response set. TabId : "+a+" url : "+c.fullURL);var g=l._getSITabInfo(a);g.set("wrsScamResponse",c);c=c.getPIIEnValue();c!==d.WRS_RATINGS.PII_ENABLED&&c!==d.WRS_RATINGS.PII_SILENCE||b.getTab(a,function(a){b.sendMessageToTab(a,{id:d.MESSAGES.PROCESS_PAGE_FOR_SCAM_FIELDS})});l._processedTabFields.set(a,
g);l._calculateScamInsightRating(a);m.reportStopForComponent(d.performanceReporter.COMPONENT.SCAM_INSIGHT,f)}},deletePIISubmissionInfo:function(a){if(!f(a))return null;var b=l._PIISubmissionInfo.get(a);if(e(b))return null;l._PIISubmissionInfo.delete(a)},_handleTabClose:function(a){if(!f(a))return null;l.deletePIISubmissionInfo(a)},_handleMessage:function(a,c,f){if(!e(a)&&!e(a.id))switch(c=b.getTabID(f),a.id){case d.MESSAGES.WAX_FIELDS_FOUND:if(e(a.data))break;a=a.data;if(0>=a.length)break;l._collectPIIFields(c,
a);break;case d.MESSAGES.TOP_FRAME_UNLOADED:a=d.performanceReporter.TYPE.TOP_FRAME_UNLOADED+":"+Date.now(),m.reportStartForComponent(d.performanceReporter.COMPONENT.SCAM_INSIGHT,a),f=l._processedTabFields.get(c),e(f)||(f.get("piiSubmissionTimer")&&l._sendPIISubmissionSilentRatingOnTabClose(c),l._processedTabFields.delete(c),m.reportStopForComponent(d.performanceReporter.COMPONENT.SCAM_INSIGHT,a))}},_handleScamPageFoundCallback:function(a,b){if(f(a)&&!c.scamInsightUtility.isURLInViewAnywayCache(b)&&
(b=l._processedTabFields.get(a),!e(b))){var d=b.get("scamInsightBlockPageHandled");if(!k(d)||!0!==d){d=b.get("matchedFields");var h=b.get("wrsScamResponse");r.debug("Scam Page detected : ");r.debug(b);l._scamPageFoundCallback(a);var g=new Map;g.set("wrsScamResponse",h);g.set("matchedFields",d);g.set("piiSubmitted",!1);l._PIISubmissionInfo.set(a,g);b.set("scamInsightBlockPageHandled",!0);l._processedTabFields.set(a,b)}}},_handleCacheResponse:function(a,b){f(a)&&!e(b)&&b.getScamRating()===d.SCAM_INSIGHT_RESULT.SUSPICIOUS_PAGE&&
u(l._scamPageFoundCallback)&&l._handleScamPageFoundCallback(a,b.getFullURL())},_updateCachedScamRating:function(a,b){!e(a)&&f(b)&&(a=c.cache.ratingForCachedURL(a.getFullURL()),e(a)||a.getScamRating()===b||(a[d.SCAM_INSIGHT_RATING_KEY]=b,c.cache.updateCacheRatingsForUrl(a)))}};window.addEventListener("load",l.initialize);return l}(a.SymBfw,a.SafeWeb)})(executionContext);
