var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(e,c,a){e!=Array.prototype&&e!=Object.prototype&&(e[c]=a.value)};$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var e=0;return function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+e++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var e=$jscomp.global.Symbol.iterator;e||(e=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[e]&&$jscomp.defineProperty(Array.prototype,e,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(e){var c=0;return $jscomp.iteratorPrototype(function(){return c<e.length?{done:!1,value:e[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(e){$jscomp.initSymbolIterator();e={next:e};e[$jscomp.global.Symbol.iterator]=function(){return this};return e};$jscomp.makeIterator=function(e){$jscomp.initSymbolIterator();var c=e[Symbol.iterator];return c?c.call(e):$jscomp.arrayIterator(e)};
$jscomp.iteratorFromArray=function(e,c){$jscomp.initSymbolIterator();e instanceof String&&(e+="");var a=0,g={next:function(){if(a<e.length){var d=a++;return{value:c(d,e[d]),done:!1}}g.next=function(){return{done:!0,value:void 0}};return g.next()}};g[Symbol.iterator]=function(){return g};return g};
$jscomp.polyfill=function(e,c,a,g){if(c){a=$jscomp.global;e=e.split(".");for(g=0;g<e.length-1;g++){var d=e[g];d in a||(a[d]={});a=a[d]}e=e[e.length-1];g=a[e];c=c(g);c!=g&&null!=c&&$jscomp.defineProperty(a,e,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.keys",function(e){return e?e:function(){return $jscomp.iteratorFromArray(this,function(c){return c})}},"es6","es3");$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(e){function c(){this.batch_=null}function a(b){return b instanceof d?b:new d(function(m,f){m(b)})}if(e&&!$jscomp.FORCE_POLYFILL_PROMISE)return e;c.prototype.asyncExecute=function(b){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(b);return this};c.prototype.asyncExecuteBatch_=function(){var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})};var g=$jscomp.global.setTimeout;c.prototype.asyncExecuteFunction=function(b){g(b,
0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=this.batch_;this.batch_=[];for(var a=0;a<b.length;++a){var f=b[a];b[a]=null;try{f()}catch(h){this.asyncThrow_(h)}}}this.batch_=null};c.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var d=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{b(a.resolve,a.reject)}catch(f){a.reject(f)}};d.prototype.createResolveAndReject_=
function(){function b(h){return function(k){f||(f=!0,h.call(a,k))}}var a=this,f=!1;return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};d.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof d)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var a=null!=b;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};d.prototype.resolveToNonPromiseObj_=function(b){var a=
void 0;try{a=b.then}catch(f){this.reject_(f);return}"function"==typeof a?this.settleSameAsThenable_(a,b):this.fulfill_(b)};d.prototype.reject_=function(b){this.settle_(2,b)};d.prototype.fulfill_=function(b){this.settle_(1,b)};d.prototype.settle_=function(b,a){if(0!=this.state_)throw Error("Cannot settle("+b+", "+a+"): Promise already settled in state"+this.state_);this.state_=b;this.result_=a;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)b.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var b=new c;d.prototype.settleSameAsPromise_=function(b){var a=this.createResolveAndReject_();b.callWhenSettled_(a.resolve,a.reject)};d.prototype.settleSameAsThenable_=function(b,a){var f=this.createResolveAndReject_();try{b.call(a,f.resolve,f.reject)}catch(h){f.reject(h)}};d.prototype.then=function(b,a){function f(b,a){return"function"==typeof b?function(a){try{h(b(a))}catch(r){k(r)}}:
a}var h,k,n=new d(function(b,a){h=b;k=a});this.callWhenSettled_(f(b,h),f(a,k));return n};d.prototype.catch=function(b){return this.then(void 0,b)};d.prototype.callWhenSettled_=function(a,c){function f(){switch(h.state_){case 1:a(h.result_);break;case 2:c(h.result_);break;default:throw Error("Unexpected state: "+h.state_);}}var h=this;null==this.onSettledCallbacks_?b.asyncExecute(f):this.onSettledCallbacks_.push(f)};d.resolve=a;d.reject=function(b){return new d(function(a,f){f(b)})};d.race=function(b){return new d(function(c,
f){for(var h=$jscomp.makeIterator(b),k=h.next();!k.done;k=h.next())a(k.value).callWhenSettled_(c,f)})};d.all=function(b){var c=$jscomp.makeIterator(b),f=c.next();return f.done?a([]):new d(function(b,k){function h(k){return function(a){d[k]=a;m--;0==m&&b(d)}}var d=[],m=0;do d.push(void 0),m++,a(f.value).callWhenSettled_(h(d.length-1),k),f=c.next();while(!f.done)})};return d},"es6","es3");(function(e){(e.SymBfw=e.SymBfw||{}).globals={BROWSER:"Chrome",PRODUCT_GUID:"DC6B1B05-C7B2-43EB-81E3-CBD3896553C2"}})(this);
(function(e){(e.SymBfw=e.SymBfw||{}).logger=function(c){return{debug:function(a){},log:function(a){},error:function(a){console.error(a);var g=c.telemetryWrapper;g.send(g.componentType.LOGGER,g.actionType.ERROR,a)},warn:function(a){console.warn(a);var g=c.telemetryWrapper;g.send(g.componentType.LOGGER,g.actionType.WARN,a)},info:function(a){console.info(a)}}}(e.SymBfw)})(this);
(function(e){e=e.SymBfw;var c={httpStatusCodes:{},localizer:{DEFAULT_MESSAGES_DICTIONARY:"strings",GET_LOCALIZED_STRING:"44F4D54E-AB86-454C-A494-DE3AD87E72F9",GET_LOCALIZED_STRINGS:"0D1C5EEF-749F-4EEB-AD6D-F9C26018EE91",GET_ALL_LOCALIZED_STRINGS:"33445b60-9a88-4d99-829f-564704b2a960",GET_LOCALIZED_STRING_FROM_DICTIONARY:"D15C0B4C-DC1B-403F-A3C8-8BB42137B325",GET_LOCALIZED_STRINGS_FROM_DICTIONARY:"88313974-C371-4A8D-9196-0A2CE43C8327",GET_LOCALIZED_STRING_WITH_FORMAT:"F3D7C8CE-B1A9-425A-AD24-4120C592AF86",
GET_LOCALIZED_STRING_WITH_FORMAT_FROM_DICTIONARY:"9066F4CC-31A4-45F5-A07A-81DDC38E5F99",GET_CURRENT_LANGUAGE_DIRECTION:"C30B2719-DD82-41EC-E93A-8A602444F90A"},clipboard:{messages:{CLEAR_CLIPBOARD:"aa232db5-1dba-473a-ab4b-e9c378b7978b"},DEFAULT_TIMEOUT:6E4}};c.httpStatusCodes.OK=200;c.httpStatusCodes.PARTIAL_CONTENT=206;c.httpStatusCodes.CREATED=201;c.httpStatusCodes.NO_CONTENT=204;c.httpStatusCodes.INCORRECT_URI=302;c.httpStatusCodes.NOT_MODIFIED=304;c.httpStatusCodes.BAD_REQUEST=400;c.httpStatusCodes.UNAUTHORIZED=
401;c.httpStatusCodes.INVALID_SCHEMA=403;c.httpStatusCodes.NOT_FOUND=404;c.httpStatusCodes.HEADER_ERROR=406;c.httpStatusCodes.GONE=410;c.httpStatusCodes.ENTITY_TOO_LARGE=413;c.httpStatusCodes.DATASTORE_RATE_LIMITED=429;c.httpStatusCodes.RATE_LIMITING=503;c.httpStatusCodes.SERVER_ERROR=500;c.DEFAULT_FETCH_TIMEOUT=6E4;c.telemetry={TELEMETRY_ENABLED:"293E0764-AF48-4C52-B675-0161A7B6BECE",TELEMETRY_OPT_OUT_SHOWN:"FE795012-44D6-491D-A8A1-E83633892C9D",BFW_TELEMETRY_SETTINGS_CONTAINER:"233D07C0-6318-4BCE-A36A-82DFB19F3B2A",
USER_RESPONDED_IN_OPT_OUT_PAGE:"8157BC1F-5ED8-4373-A18D-8CD8E0263752",LAST_OFFER_DATE:"9EA53F0C-7F18-44A5-8138-C11F27D66FC1"};c.os={WINDOWS:"Windows",MAC:"Mac",UNKNOWN:"Unknown"};c.uiConstants={NOTIFICATION:{IFRAME_ID:"symc-notification-popup",HTML:"content/ui/notification.html",STYLE:"content/ui/content-page.css",STACK_COUNT:1,DEFAULT_TIMEOUT:1E4,HEIGHT:160,WIDTH:460,TYPE:{QUESTION:0,TIMED:1},BUTTON:{DEFAULT:0,SECONDARY:1},MESSAGES:{DEFAULT_MESSAGE:"8DB8FE17-6F5E-485E-81EE-1112762F48E4",DEFAULT_BUTTON_PRESSED:"209CBB4D-6D6B-46F4-9EA7-303181937BF6",
SECONDARY_LINK_PRESSED:"8881560D-E8A2-41FA-A81D-A90D41311D0D",THIRD_BUTTON_PRESSED:"196F06EB-956E-44EE-A60D-F4741C5CF4D3",NOTIFICATION_CLOSED:"EA7414A5-667F-4459-BAC2-38464F3330A3",NOTIFICATION_QUEUE_MESSAGE:"A88CCFCD-B98D-4607-B780-79A1CF7ADFAD",NOTIFICATIONS_SHOWN:"57C094C2-F0F0-44C2-9BBF-9E147135FB50",UI_INIT:"EE5B61D6-3A55-4ABB-B304-02BDAD9698FE",UI_INIT_PROXY:"0FABE0DB-1C87-475B-D89E-F4EC0EE963DE",HIDE_NOTIFICATIONS:"8211780F-93EC-4E37-8933-E60CB6052E84"}},CONTENT_PAGE_STYLE_ID:"symc-content-stylesheet"};
c.performanceReporter={MESSAGES:{REPORT_START:"2379B4CB-E725-4818-8FCC-A9372EABBF45",REPORT_END:"1F62DD4E-56AD-4528-9A69-BFE9EC135B9F",GET_PERFORMANCE_REPORTER:"2306DE62-ACA8-40AE-9909-517474C1120B"}};c.utils={IP:"ip"};c.NAVIGATION_COMPLETE="complete";e.constants=c})(this);
(function(e){e.SymBfw.utils=function(c){var a={},g=c.constants;a.createNewGuid=function(){var b=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var c=(b+16*Math.random())%16|0;b=Math.floor(b/16);return("x"==a?c:c&7|8).toString(16)})};a.stringUTF16LEToByteArray=function(b){if(!1===this.isString(b))throw Error("Input string cannot be null or is not a string");for(var a=[],c=0;c<b.length;++c){var f=b.charCodeAt(c),h=(f&65280)>>8;a.push(f&255);a.push(h)}return a};
a.arrayBufferToStringUTF16LE=function(b){if(this.isNil(b))return null;b instanceof ArrayBuffer&&(b=new Uint8Array(b));for(var a=[],c=0;c<b.byteLength;c++)a.push(b[c]);return this.byteArrayToStringUTF16LE(a)};a.byteArrayToStringUTF16LE=function(b){if(!1===this.isArray(b))throw Error("Byte array cannot be null or is not an array");if(2>b.length)throw Error("Byte array needs to contain at least two bytes");if(0!==b.length%2)throw Error("Byte array needs to contain even number of bytes");for(var a="",
c=0;c<b.length-1;c+=2){var f=b[c];if(255<f)throw Error("Encoding error: Input contains element larger than a byte.");f&=255;var h=b[c+1];if(255<h)throw Error("Encoding error: Input contains element larger than a byte.");h=h<<8&65280;a+=String.fromCharCode(f+h)}return a};a.downloadFileFromUrl=function(b){var a=document.createElement("iframe");a.style.display="none";a.src=b;a.width="1";a.height="1";a.frameborder="0";document.body.appendChild(a);setTimeout(function(){document.body.removeChild(a)},5E3)};
a.obfuscatePassword=function(b,a){if(!1===this.isString(b))throw Error("password  cannot be null and has to be a string");if(!1===this.isString(a))throw Error("obfuscationKey  cannot be null and has to be a string");b=new Uint8Array(c.utils.stringUTF16LEToByteArray(b));a=new Uint8Array(c.utils.stringUTF16LEToByteArray(a));a=c.utils._obfuscateData(b,a);return a=c.utils.arrayBufferToStringUTF16LE(a)};a._obfuscateData=function(b,c){if(a.isNil(b)||a.isNil(c))return null;b instanceof ArrayBuffer&&(b=new Uint8Array(b));
c instanceof ArrayBuffer&&(c=new Uint8Array(c));for(var d=b.byteLength,f=new Uint8Array(d),h=0;h<d;h++)f[h]=b[h]^c[h%d];return f};a.getOSType=function(){var a=g.os.UNKNOWN;-1!=navigator.appVersion.toLowerCase().indexOf("win")?a=g.os.WINDOWS:-1!=navigator.appVersion.toLowerCase().indexOf("mac")&&(a=g.os.MAC);return a};a.isNil=function(a){return"undefined"===typeof a||null===a?!0:!1};a.isntNil=function(a){return"undefined"!==typeof a&&null!==a?!0:!1};a.isEmptyObject=function(b){return a.isNil(b)||0===
Object.keys(b).length?!0:!1};a.isString=function(b){return a.isntNil(b)&&"string"===typeof b?!0:!1};a.isFunction=function(b){return a.isntNil(b)&&"function"===typeof b?!0:!1};a.isArray=function(a){return Array.isArray(a)};a.isBoolean=function(b){return a.isntNil(b)&&"boolean"===typeof b?!0:!1};var d={ac:{com:!0,gov:!0,mil:!0,net:!0,org:!0,edu:!0},ad:{nom:!0},ae:{ac:!0,co:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,pro:!0,sch:!0},af:{com:!0,edu:!0,gov:!0,net:!0,org:!0},ai:{off:!0,com:!0,net:!0,org:!0},
al:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0,uniti:!0,tirana:!0,soros:!0,upt:!0,inima:!0},an:{com:!0,net:!0,org:!0,edu:!0},ag:{com:!0,org:!0,net:!0,co:!0,nom:!0},ao:{co:!0,ed:!0,gv:!0,it:!0,og:!0,pb:!0},ar:{com:!0,edu:!0,gob:!0,gov:!0,"int":!0,mil:!0,net:!0,org:!0,tur:!0},arpa:{e164:!0,"in-addr":!0,iris:!0,ip6:!0,uri:!0,urn:!0},at:{ac:!0,co:!0,gv:!0,or:!0,priv:!0},au:{asn:!0,com:!0,net:!0,id:!0,org:!0,csiro:!0,oz:!0,info:!0,conf:!0,act:!0,nsw:!0,nt:!0,qld:!0,sa:!0,tas:!0,vic:!0,wa:!0},aw:{com:!0},
az:{com:!0,net:!0,"int":!0,gov:!0,biz:!0,org:!0,edu:!0,mil:!0,pp:!0,name:!0,info:!0},ba:{co:!0,com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0,rs:!0,unbi:!0,unmo:!0,unsa:!0,untz:!0,unze:!0},bb:{biz:!0,co:!0,com:!0,edu:!0,gov:!0,info:!0,net:!0,org:!0,store:!0,tv:!0},bd:{com:!0,edu:!0,net:!0,gov:!0,org:!0,mil:!0},be:{ac:!0},bf:{gov:!0},bh:{biz:!0,cc:!0,com:!0,edu:!0,gov:!0,info:!0,net:!0,org:!0},bm:{com:!0,edu:!0,org:!0,gov:!0,net:!0},bn:{com:!0,edu:!0,gov:!0,net:!0,org:!0},bo:{com:!0,edu:!0,gob:!0,gov:!0,
"int":!0,mil:!0,net:!0,org:!0,tv:!0},br:{adm:!0,adv:!0,agr:!0,am:!0,arq:!0,art:!0,ato:!0,b:!0,bio:!0,blog:!0,bmd:!0,cim:!0,cng:!0,cnt:!0,com:!0,coop:!0,ecn:!0,edu:!0,eng:!0,esp:!0,etc:!0,eti:!0,far:!0,flog:!0,fm:!0,fnd:!0,fot:!0,fst:!0,g12:!0,ggf:!0,gov:!0,imb:!0,ind:!0,inf:!0,jor:!0,jus:!0,lel:!0,mat:!0,med:!0,mil:!0,mus:!0,net:!0,nom:!0,not:!0,ntr:!0,odo:!0,org:!0,ppg:!0,pro:!0,psc:!0,psi:!0,qsl:!0,rec:!0,slg:!0,srv:!0,tmp:!0,trd:!0,tur:!0,tv:!0,vet:!0,vlog:!0,wiki:!0,zlg:!0},bs:{com:!0,edu:!0,
gov:!0,net:!0,org:!0},bt:{com:!0,edu:!0,gov:!0,net:!0,org:!0},bw:{co:!0,org:!0},by:{gov:!0,mil:!0},bz:{du:!0,et:!0,om:!0,ov:!0,rg:!0},ca:{ab:!0,bc:!0,mb:!0,nb:!0,nf:!0,nl:!0,ns:!0,nt:!0,nu:!0,on:!0,pe:!0,qc:!0,sk:!0,yk:!0},cc:{co:!0},ck:{biz:!0,co:!0,edu:!0,gen:!0,gov:!0,info:!0,net:!0,org:!0},cn:{ac:!0,ah:!0,bj:!0,com:!0,cq:!0,edu:!0,fj:!0,gd:!0,gov:!0,gs:!0,gx:!0,gz:!0,ha:!0,hb:!0,he:!0,hi:!0,hl:!0,hn:!0,jl:!0,js:!0,jx:!0,ln:!0,mil:!0,net:!0,nm:!0,nx:!0,org:!0,qh:!0,sc:!0,sd:!0,sh:!0,sn:!0,sx:!0,
tj:!0,tw:!0,xj:!0,xz:!0,yn:!0,zj:!0},co:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,nom:!0,org:!0},cr:{ac:!0,c:!0,co:!0,ed:!0,fi:!0,go:!0,or:!0,sa:!0},cx:{gov:!0},cy:{ac:!0,biz:!0,com:!0,ekloges:!0,gov:!0,ltd:!0,name:!0,net:!0,org:!0,parliament:!0,press:!0,pro:!0,tm:!0},cu:{com:!0,edu:!0,org:!0,net:!0,gov:!0,inf:!0},dm:{com:!0,net:!0,org:!0,edu:!0,gov:!0},"do":{art:!0,com:!0,edu:!0,gob:!0,gov:!0,mil:!0,net:!0,org:!0,sld:!0,web:!0},dz:{art:!0,asso:!0,com:!0,edu:!0,gov:!0,net:!0,org:!0,pol:!0},ec:{com:!0,edu:!0,
fin:!0,gov:!0,info:!0,med:!0,mil:!0,net:!0,org:!0,pro:!0},ee:{com:!0,org:!0,fie:!0,pri:!0},eg:{com:!0,edu:!0,eun:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,sci:!0},er:{com:!0,edu:!0,gov:!0,ind:!0,mil:!0,net:!0,org:!0,rochest:!0,w:!0},es:{com:!0,edu:!0,gob:!0,nom:!0,org:!0},et:{biz:!0,com:!0,edu:!0,gov:!0,info:!0,name:!0,net:!0,org:!0},fi:{aland:!0},fj:{ac:!0,biz:!0,com:!0,info:!0,mil:!0,name:!0,net:!0,org:!0,pro:!0},fk:{ac:!0,co:!0,gov:!0,net:!0,nom:!0,org:!0},fr:{asso:!0,com:!0,f:!0,gouv:!0,nom:!0,prd:!0,
presse:!0,tm:!0},ge:{com:!0,edu:!0,gov:!0,org:!0,mil:!0,net:!0,pvt:!0},gg:{co:!0,net:!0,org:!0},gh:{com:!0,edu:!0,gov:!0,mil:!0,org:!0},gi:{com:!0,ltd:!0,gov:!0,mod:!0,edu:!0,org:!0},gn:{ac:!0,com:!0,gov:!0,net:!0,org:!0},gp:{com:!0,net:!0,edu:!0,asso:!0,org:!0},gr:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},gt:{com:!0,edu:!0,gob:!0,ind:!0,mil:!0,net:!0,org:!0},gu:{com:!0,edu:!0,gov:!0,net:!0,org:!0},hk:{com:!0,edu:!0,gov:!0,idv:!0,net:!0,org:!0},ht:{com:!0,net:!0,firm:!0,shop:!0,info:!0,pro:!0,adult:!0,
org:!0,art:!0,pol:!0,rel:!0,asso:!0,perso:!0,coop:!0,med:!0,edu:!0,gouv:!0},hu:{2E3:!0,agrar:!0,bolt:!0,casino:!0,city:!0,co:!0,erotica:!0,erotika:!0,film:!0,forum:!0,games:!0,hotel:!0,info:!0,ingatlan:!0,jogasz:!0,konyvelo:!0,lakas:!0,media:!0,news:!0,org:!0,priv:!0,reklam:!0,sex:!0,shop:!0,sport:!0,suli:!0,szex:!0,tm:!0,tozsde:!0,utazas:!0,video:!0},id:{ac:!0,co:!0,go:!0,mil:!0,net:!0,or:!0,sch:!0,web:!0},il:{ac:!0,co:!0,gov:!0,idf:!0,k12:!0,muni:!0,net:!0,org:!0},im:{co:!0,"ltd.co":!0,"plc.co":!0,
net:!0,gov:!0,org:!0,nic:!0,ac:!0},"in":{ac:!0,co:!0,edu:!0,ernet:!0,firm:!0,gen:!0,gov:!0,i:!0,ind:!0,mil:!0,net:!0,nic:!0,org:!0,res:!0},iq:{com:!0,edu:!0,gov:!0,i:!0,mil:!0,net:!0,org:!0},ir:{ac:!0,co:!0,dnssec:!0,gov:!0,i:!0,id:!0,net:!0,org:!0,sch:!0},it:{edu:!0,gov:!0},je:{co:!0,net:!0,org:!0},jo:{com:!0,edu:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,sch:!0},jp:{ac:!0,ad:!0,co:!0,ed:!0,go:!0,gr:!0,lg:!0,ne:!0,or:!0},ke:{ac:!0,co:!0,go:!0,info:!0,me:!0,mobi:!0,ne:!0,or:!0,sc:!0},kh:{com:!0,edu:!0,
gov:!0,mil:!0,net:!0,org:!0,per:!0},ki:{biz:!0,com:!0,de:!0,edu:!0,gov:!0,info:!0,mob:!0,net:!0,org:!0,tel:!0},km:{asso:!0,com:!0,coop:!0,edu:!0,gouv:!0,k:!0,medecin:!0,mil:!0,nom:!0,notaires:!0,pharmaciens:!0,presse:!0,tm:!0,veterinaire:!0},kn:{edu:!0,gov:!0,net:!0,org:!0},kr:{ac:!0,busan:!0,chungbuk:!0,chungnam:!0,co:!0,daegu:!0,daejeon:!0,es:!0,gangwon:!0,go:!0,gwangju:!0,gyeongbuk:!0,gyeonggi:!0,gyeongnam:!0,hs:!0,incheon:!0,jeju:!0,jeonbuk:!0,jeonnam:!0,k:!0,kg:!0,mil:!0,ms:!0,ne:!0,or:!0,pe:!0,
re:!0,sc:!0,seoul:!0,ulsan:!0},kw:{com:!0,edu:!0,gov:!0,net:!0,org:!0},ky:{com:!0,edu:!0,gov:!0,net:!0,org:!0},kz:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},lb:{com:!0,edu:!0,gov:!0,net:!0,org:!0},lc:{com:!0,org:!0,edu:!0,gov:!0},li:{com:!0,net:!0,org:!0,gov:!0},lk:{assn:!0,com:!0,edu:!0,gov:!0,grp:!0,hotel:!0,"int":!0,ltd:!0,net:!0,ngo:!0,org:!0,sch:!0,soc:!0,web:!0},lr:{com:!0,edu:!0,gov:!0,net:!0,org:!0},ls:{org:!0,co:!0},lt:{gov:!0,mil:!0},lu:{gov:!0,mil:!0,org:!0,net:!0},lv:{asn:!0,com:!0,conf:!0,
edu:!0,gov:!0,id:!0,mil:!0,net:!0,org:!0},ly:{com:!0,edu:!0,gov:!0,id:!0,med:!0,net:!0,org:!0,plc:!0,sch:!0},ma:{ac:!0,co:!0,gov:!0,m:!0,net:!0,org:!0,press:!0},mc:{asso:!0,tm:!0},me:{ac:!0,co:!0,edu:!0,gov:!0,its:!0,net:!0,org:!0,priv:!0},mg:{com:!0,edu:!0,gov:!0,mil:!0,nom:!0,org:!0,prd:!0,tm:!0},mk:{com:!0,edu:!0,gov:!0,inf:!0,name:!0,net:!0,org:!0,pro:!0},ml:{com:!0,edu:!0,gov:!0,net:!0,org:!0,presse:!0},mn:{edu:!0,gov:!0,org:!0},mo:{com:!0,edu:!0,gov:!0,net:!0,org:!0},mt:{com:!0,edu:!0,gov:!0,
net:!0,org:!0},mv:{aero:!0,biz:!0,com:!0,coop:!0,edu:!0,gov:!0,info:!0,"int":!0,mil:!0,museum:!0,name:!0,net:!0,org:!0,pro:!0},mw:{ac:!0,co:!0,com:!0,coop:!0,edu:!0,gov:!0,"int":!0,museum:!0,net:!0,org:!0},mx:{com:!0,edu:!0,gob:!0,net:!0,org:!0},my:{com:!0,edu:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,sch:!0},nf:{arts:!0,com:!0,firm:!0,info:!0,net:!0,other:!0,per:!0,rec:!0,store:!0,web:!0},ng:{biz:!0,com:!0,edu:!0,gov:!0,mil:!0,mobi:!0,name:!0,net:!0,org:!0,sch:!0},ni:{ac:!0,co:!0,com:!0,edu:!0,gob:!0,
mil:!0,net:!0,nom:!0,org:!0},no:{mil:!0,stat:!0,kommune:!0,herad:!0,priv:!0,vgs:!0,fhs:!0,museum:!0,fylkesbibl:!0,folkebibl:!0,idrett:!0},np:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},nr:{biz:!0,com:!0,edu:!0,gov:!0,info:!0,net:!0,org:!0},om:{ac:!0,biz:!0,co:!0,com:!0,edu:!0,gov:!0,med:!0,mil:!0,museum:!0,net:!0,org:!0,pro:!0,sch:!0},pe:{com:!0,edu:!0,gob:!0,mil:!0,net:!0,nom:!0,org:!0,sld:!0},pf:{com:!0,org:!0,edu:!0},pg:{"com.pg":!0,net:!0},ph:{com:!0,edu:!0,gov:!0,i:!0,mil:!0,net:!0,ngo:!0,org:!0},
pk:{biz:!0,com:!0,edu:!0,fam:!0,gob:!0,gok:!0,gon:!0,gop:!0,gos:!0,gov:!0,net:!0,org:!0,web:!0},pl:{art:!0,bialystok:!0,biz:!0,com:!0,edu:!0,gda:!0,gdansk:!0,gorzow:!0,gov:!0,info:!0,katowice:!0,krakow:!0,lodz:!0,lublin:!0,mil:!0,net:!0,ngo:!0,olsztyn:!0,org:!0,poznan:!0,pwr:!0,radom:!0,slupsk:!0,szczecin:!0,torun:!0,warszawa:!0,waw:!0,wroc:!0,wroclaw:!0,zgora:!0},pr:{ac:!0,biz:!0,com:!0,edu:!0,est:!0,gov:!0,info:!0,isla:!0,name:!0,net:!0,org:!0,pro:!0,prof:!0},pro:{law:!0,med:!0,cpa:!0},ps:{com:!0,
edu:!0,gov:!0,net:!0,org:!0,plo:!0,sec:!0},pt:{com:!0,edu:!0,gov:!0,"int":!0,net:!0,nome:!0,org:!0,publ:!0},pw:{belau:!0,co:!0,ed:!0,go:!0,ne:!0,or:!0},ro:{arts:!0,com:!0,firm:!0,info:!0,nom:!0,nt:!0,org:!0,rec:!0,store:!0,tm:!0,www:!0},rs:{ac:!0,co:!0,edu:!0,gov:!0,"in":!0,org:!0},sb:{com:!0,edu:!0,gov:!0,net:!0,org:!0},sc:{com:!0,edu:!0,gov:!0,net:!0,org:!0},sh:{co:!0,com:!0,edu:!0,gov:!0,net:!0,nom:!0,org:!0},sl:{com:!0,edu:!0,gov:!0,net:!0,org:!0},st:{co:!0,com:!0,consulado:!0,edu:!0,embaixada:!0,
gov:!0,mil:!0,net:!0,org:!0,principe:!0,saotome:!0,store:!0},sv:{com:!0,edu:!0,gob:!0,org:!0,red:!0},sz:{ac:!0,co:!0,org:!0},tr:{av:!0,bbs:!0,bel:!0,biz:!0,com:!0,dr:!0,edu:!0,gen:!0,gov:!0,info:!0,k12:!0,name:!0,net:!0,org:!0,pol:!0,tel:!0,tsk:!0,tv:!0,web:!0},tt:{aero:!0,biz:!0,cat:!0,co:!0,com:!0,coop:!0,edu:!0,gov:!0,info:!0,"int":!0,jobs:!0,mil:!0,mobi:!0,museum:!0,name:!0,net:!0,org:!0,pro:!0,tel:!0,travel:!0},tw:{club:!0,com:!0,ebiz:!0,edu:!0,game:!0,gov:!0,idv:!0,mil:!0,net:!0,org:!0},mu:{ac:!0,
co:!0,com:!0,gov:!0,net:!0,or:!0,org:!0},mz:{ac:!0,co:!0,edu:!0,gov:!0,org:!0},na:{co:!0,com:!0},nz:{ac:!0,co:!0,cri:!0,geek:!0,gen:!0,govt:!0,health:!0,iwi:!0,maori:!0,mil:!0,net:!0,org:!0,parliament:!0,school:!0},pa:{abo:!0,ac:!0,com:!0,edu:!0,gob:!0,ing:!0,med:!0,net:!0,nom:!0,org:!0,sld:!0},py:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},qa:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},re:{asso:!0,com:!0,nom:!0},ru:{ac:!0,adygeya:!0,altai:!0,amur:!0,arkhangelsk:!0,astrakhan:!0,bashkiria:!0,belgorod:!0,
bir:!0,bryansk:!0,buryatia:!0,cbg:!0,chel:!0,chelyabinsk:!0,chita:!0,chukotka:!0,chuvashia:!0,com:!0,dagestan:!0,"e-burg":!0,edu:!0,gov:!0,grozny:!0,"int":!0,irkutsk:!0,ivanovo:!0,izhevsk:!0,jar:!0,"joshkar-ola":!0,kalmykia:!0,kaluga:!0,kamchatka:!0,karelia:!0,kazan:!0,kchr:!0,kemerovo:!0,khabarovsk:!0,khakassia:!0,khv:!0,kirov:!0,koenig:!0,komi:!0,kostroma:!0,kranoyarsk:!0,kuban:!0,kurgan:!0,kursk:!0,lipetsk:!0,magadan:!0,mari:!0,"mari-el":!0,marine:!0,mil:!0,mordovia:!0,mosreg:!0,msk:!0,murmansk:!0,
nalchik:!0,net:!0,nnov:!0,nov:!0,novosibirsk:!0,nsk:!0,omsk:!0,orenburg:!0,org:!0,oryol:!0,penza:!0,perm:!0,pp:!0,pskov:!0,ptz:!0,rnd:!0,ryazan:!0,sakhalin:!0,samara:!0,saratov:!0,simbirsk:!0,smolensk:!0,spb:!0,stavropol:!0,stv:!0,surgut:!0,tambov:!0,tatarstan:!0,tom:!0,tomsk:!0,tsaritsyn:!0,tsk:!0,tula:!0,tuva:!0,tver:!0,tyumen:!0,udm:!0,udmurtia:!0,"ulan-ude":!0,vladikavkaz:!0,vladimir:!0,vladivostok:!0,volgograd:!0,vologda:!0,voronezh:!0,vrn:!0,vyatka:!0,yakutia:!0,yamal:!0,yekaterinburg:!0,"yuzhno-sakhalinsk":!0},
rw:{ac:!0,co:!0,com:!0,edu:!0,gouv:!0,gov:!0,"int":!0,mil:!0,net:!0},sa:{com:!0,edu:!0,gov:!0,med:!0,net:!0,org:!0,pub:!0,sch:!0},sd:{com:!0,edu:!0,gov:!0,info:!0,med:!0,net:!0,org:!0,tv:!0},se:{a:!0,ac:!0,b:!0,bd:!0,c:!0,d:!0,e:!0,f:!0,g:!0,h:!0,i:!0,k:!0,l:!0,m:!0,n:!0,o:!0,org:!0,p:!0,parti:!0,pp:!0,press:!0,r:!0,s:!0,t:!0,tm:!0,u:!0,w:!0,x:!0,y:!0,z:!0},sg:{com:!0,edu:!0,gov:!0,idn:!0,net:!0,org:!0,per:!0},sn:{art:!0,com:!0,edu:!0,gouv:!0,org:!0,perso:!0,univ:!0},sy:{com:!0,edu:!0,gov:!0,mil:!0,
net:!0,news:!0,org:!0},th:{ac:!0,co:!0,go:!0,"in":!0,mi:!0,net:!0,or:!0},tj:{ac:!0,biz:!0,co:!0,com:!0,edu:!0,go:!0,gov:!0,info:!0,"int":!0,mil:!0,name:!0,net:!0,nic:!0,org:!0,test:!0,web:!0},tn:{agrinet:!0,com:!0,defense:!0,edunet:!0,ens:!0,fin:!0,gov:!0,ind:!0,info:!0,intl:!0,mincom:!0,nat:!0,net:!0,org:!0,perso:!0,rnrt:!0,rns:!0,rnu:!0,tourism:!0},tz:{ac:!0,co:!0,go:!0,ne:!0,or:!0},ua:{biz:!0,cherkassy:!0,chernigov:!0,chernovtsy:!0,ck:!0,cn:!0,co:!0,com:!0,crimea:!0,cv:!0,dn:!0,dnepropetrovsk:!0,
donetsk:!0,dp:!0,edu:!0,gov:!0,"if":!0,"in":!0,"ivano-frankivsk":!0,kh:!0,kharkov:!0,kherson:!0,khmelnitskiy:!0,kiev:!0,kirovograd:!0,km:!0,kr:!0,ks:!0,kv:!0,lg:!0,lugansk:!0,lutsk:!0,lviv:!0,me:!0,mk:!0,net:!0,nikolaev:!0,od:!0,odessa:!0,org:!0,pl:!0,poltava:!0,pp:!0,rovno:!0,rv:!0,sebastopol:!0,sumy:!0,te:!0,ternopil:!0,uzhgorod:!0,vinnica:!0,vn:!0,zaporizhzhe:!0,zhitomir:!0,zp:!0,zt:!0},ug:{ac:!0,co:!0,go:!0,ne:!0,or:!0,org:!0,sc:!0},uk:{ac:!0,bl:!0,"british-library":!0,co:!0,cym:!0,gov:!0,govt:!0,
icnet:!0,jet:!0,lea:!0,ltd:!0,me:!0,mil:!0,mod:!0,"national-library-scotland":!0,nel:!0,net:!0,nhs:!0,nic:!0,nls:!0,org:!0,orgn:!0,parliament:!0,plc:!0,police:!0,sch:!0,scot:!0,soc:!0},us:{dni:!0,fed:!0,isa:!0,kids:!0,nsn:!0},uy:{com:!0,edu:!0,gub:!0,mil:!0,net:!0,org:!0},ve:{co:!0,com:!0,edu:!0,gob:!0,info:!0,mil:!0,net:!0,org:!0,web:!0},vi:{co:!0,com:!0,k12:!0,net:!0,org:!0},vn:{ac:!0,biz:!0,com:!0,edu:!0,gov:!0,health:!0,info:!0,"int":!0,name:!0,net:!0,org:!0,pro:!0},ye:{co:!0,com:!0,gov:!0,ltd:!0,
me:!0,net:!0,org:!0,plc:!0},yu:{ac:!0,co:!0,edu:!0,gov:!0,org:!0},za:{ac:!0,agric:!0,alt:!0,bourse:!0,city:!0,co:!0,cybernet:!0,db:!0,edu:!0,gov:!0,grondar:!0,iaccess:!0,imt:!0,inca:!0,landesign:!0,law:!0,mil:!0,net:!0,ngo:!0,nis:!0,nom:!0,olivetti:!0,org:!0,pix:!0,school:!0,tm:!0,web:!0},zm:{ac:!0,co:!0,com:!0,edu:!0,gov:!0,net:!0,org:!0,sch:!0}};a.getSLD=function(b){if(a.isNil(b))return null;var c=b.split("."),g=c.length-2;if(0>g)return null;b=c[g];c=c[g+1];g=d[c];return a.isNil(g)||a.isNil(g[b])?
null:b+"."+c};a.depthOfTLDorSLD=function(b){if(a.isNil(b))return null;b=a.getSLD(b);return a.isntNil(b)?2:1};a.isInteger=function(b){return a.isNil(b)?!1:"number"===typeof b&&isFinite(b)&&Math.floor(b)===b};a.isSuccessCode=function(b){return a.isNil(b)?!1:b===g.httpStatusCodes.OK||b===g.httpStatusCodes.PARTIAL_CONTENT||b===g.httpStatusCodes.CREATED||b===g.httpStatusCodes.NO_CONTENT?!0:!1};a.safeFetch=function(a,c,d){c=void 0===c?{}:c;d=void 0===d?g.DEFAULT_FETCH_TIMEOUT:d;return new Promise(function(b,
h){var k=setTimeout(function(){h(Error("Request timed out "+a))},d);fetch(a,c).then(function(a){clearTimeout(k);b(a)}).catch(function(a){clearTimeout(k);h(a)})})};a.isSuccessCodeLocalFile=function(b){return a.isInteger(b)?"Safari"===c.globals.BROWSER&&0===b||b===g.httpStatusCodes.OK?!0:!1:!1};a.urlWithoutQueryParameters=function(b,c){a.isNil(c)&&(c=!0);if(a.isNil(b))return null;var d=new URI(b),f=d.protocol();if(a.isNil(f)||""===f||"http"!==f&&"https"!==f)f="http",d=new URI(f+"://"+b);b=d.hostname();
d=d.path();if(a.isNil(d)||"/"===d)d="";return c?f+"://"+b+d:b+d};a.baseURL=function(b){return a.isNil(b)?null:(new URI(b)).hostname()};a.pathName=function(b){return a.isNil(b)?null:(new URI(b)).pathname()};a.urlProtocol=function(b){if(a.isNil(b))return null;b=(new URI(b)).protocol();return""===b?null:b};a.getUrlTLD=function(b){if(a.isNil(b))return null;b=(new URI(b)).tld();return""===b?null:b};a.getCompanyDomain=function(b){if(a.isNil(b))return null;var c=(new URI(b)).hostname();b=a.getUrlTLD(b);
return""===c?null:a.isntNil(b)&&0<c.indexOf(b)?(c=c.substring(0,c.indexOf(b)-1).split("."),c[c.length-1]):c};a.getDomain=function(b){if(a.isNil(b))return null;b=(new URI(b)).domain();return""===b?null:b};a.isUrlAnIp=function(b){return a.isNil(b)?null:(new URI(b)).is(g.utils.IP)};a.appendToObject=function(b,c){if(a.isNil(b)||a.isNil(c))throw Error("invalid arguments to appendToObject");Object.keys(c).forEach(function(a){b[a]=c[a]})};a.createCustomHTMLEvent=function(a,c){if(!1===this.isString(a))throw Error("Event name cannot be null and has to be a string");
a=new CustomEvent(a,{detail:c});window.dispatchEvent(a)};a.isTopLevelWindow=function(){return"Edge"===c.globals.BROWSER?window.top.location==window.self.location?!0:!1:window.top==window.self?!0:!1};a.isNewVersionUpdated=function(a,c){c=c.split(".");a=a.split(".");var b=c[1]!==a[1];return c[0]!==a[0]||b?!0:!1};return a}(e.SymBfw)})(this);
(function(e){var c=Math.pow(2,31)-1;e.SymBfw.extensionAdapter=function(a){var g={},d=a.utils.isNil,b=a.utils.isntNil,e=a.utils.isString,l=a.utils.isInteger,f=a.utils.isFunction,h=a.utils.isArray;g.getLastError=function(){return chrome.runtime.lastError};g.getExtensionId=function(){return chrome.runtime.id};g.getBackgroundPage=function(){return d(chrome)||d(chrome.extension)?null:chrome.extension.getBackgroundPage()};g.getExtensionURL=function(k){if(d(chrome)||d(chrome.extension))throw Error("chrome or chrome.extension is null");
if(!e(k))throw Error("extensionAdapter.getExtensionURL expects a string path argument");return chrome.extension.getURL(k)};g.getAllWindows=function(k,a){if(d(chrome)||d(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!f(k))throw Error("invalid arguments to extensionAdapter.getAllWindows");d(a)&&(a={});chrome.windows.getAll(a,k)};g.getCurrentWindow=function(k,a){if(d(chrome)||d(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!f(k))throw Error("invalid arguments to extensionAdapter.getAllWindows");
d(a)&&(a={});chrome.windows.getCurrent(a,k)};g.createWindow=function(k,a,b){b=void 0===b?!0:b;if(d(chrome)||d(chrome.windows))throw Error("chrome is null or chrome.windows is null");b={focused:b};d(k)||(b.url=k);chrome.windows.create(b,a)};g.createAppWindow=function(a,b){if(d(chrome)||d(chrome.windows))throw Error("chrome is null or chrome.windows is null");var k={};k.type=chrome.windows.CreateType.PANEL;d(a)||(k.url=a);chrome.windows.create(k,b)};g.createPrivateWindow=function(a,b,h){h=void 0===
h?!0:h;if(d(chrome)||d(chrome.windows))throw Error("chrome is null or chrome.windows is null");h={incognito:!0,focused:h};d(a)||(h.url=a);chrome.windows.create(h,b)};g.closeWindow=function(a,b){if(d(chrome)||d(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!l(a))throw Error("invalid arguments to extensionAdapter.closeWindow");chrome.windows.remove(a,b)};g.focusWindow=function(a,b){if(d(chrome)||d(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!l(a))throw Error("invalid arguments to extensionAdapter.focusWindow");
chrome.windows.update(a,{focused:!0},b)};g.addWindowRemovedEventListener=function(a){if(d(chrome)||d(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!f(a))throw Error("extensionAdapter.addWindowRemovedEventListener needs a callback");chrome.windows.onRemoved.addListener(a)};g.addWindowFocusedEventListener=function(a){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.windows is null");if(!f(a))throw Error("extensionAdapter.addWindowFocusedEventListener needs a callback");
chrome.windows.onFocusChanged.addListener(a)};g.getTab=function(a,b){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!l(a)||!f(b))throw Error("invalid arguments to extensionAdapter.getTab");chrome.tabs.get(a,b)};g.getActiveTab=function(a,b){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!f(a))throw Error("invalid arguments to extensionAdapter.getActiveTab");var k={active:!0};l(b)?k.windowId=b:k.currentWindow=!0;chrome.tabs.query(k,
function(k){a(k[0])})};g.getAllTabs=function(a){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!f(a))throw Error("invalid arguments to extensionAdapter.getAllTabs");chrome.tabs.query({},a)};g.getTabsWithURL=function(a,b){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!e(a)||!f(b))throw Error("invalid arguments to extensionAdapter.getTabsWithURL");chrome.tabs.query({url:a},b)};g.updateTabUrl=function(a,b,h){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");
if(!l(a)||!e(b))throw Error("invalid arguments to extensionAdapter.updateTabUrl");chrome.tabs.update(a,{url:b},h)};g.activateTab=function(a,b){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(d(a)||!l(a))throw Error("invalid arguments to extensionAdapter.activateTab");chrome.tabs.update(a,{active:!0},b)};g.createTab=function(a,b,h){h=void 0===h?!0:h;if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");d(a)?chrome.tabs.create({},b):chrome.tabs.create({url:a,
active:h},b)};g.closeTab=function(a,b){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!l(a)&&!h(a))throw Error("invalid arguments to extensionAdapter.closeTab");chrome.tabs.remove(a,b)};g.closeTabAndEnsureBrowserIsAlive=function(a,h){if(!l(a)||0>=a||b(h)&&!f(h))throw Error("Invalid arguments to extensionAdapter.closeTabAndEnsureBrowserIsAlive()");g.getAllWindows(function(k){1===k.length?g.getAllTabs(function(k){1===k.length&&g.createTab();g.closeTab(a);b(h)&&
h()}):(g.closeTab(a),b(h)&&h())})};g.addTabRemovedEventListener=function(a){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!f(a))throw Error("extensionAdapter.addTabRemovedEventListener needs a callback");chrome.tabs.onRemoved.addListener(a)};g.addTabActivatedEventListener=function(a){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!f(a))throw Error("extensionAdapter.addTabActivatedEventListener needs a callback");chrome.tabs.onActivated.addListener(a)};
g.addTabReplacedEventListener=function(a){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(d(a)||!f(a))throw Error("extensionAdapter.addTabReplacedEventListener needs a callback");chrome.tabs.onReplaced.addListener(a)};g.addTabUpdatedEventListener=function(a){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!f(a))throw Error("extensionAdapter.addTabUpdatedEventListener needs a callback");chrome.tabs.onUpdated.addListener(a)};
g.addOnBeforeRequestEventListener=function(a,b,h){if(d(chrome)||d(chrome.webRequest))throw Error("chrome is null or chrome.tabs is null");if(!1===f(a))throw Error("Callback cannot be null");chrome.webRequest.onBeforeRequest.addListener(a,{urls:b},h)};g.removeOnBeforeRequestEventListener=function(a){chrome.webRequest.onBeforeRequest.removeListener(a)};g.setBrowserIcon=function(a,b){if(d(chrome)||d(chrome.browserAction))throw Error("chrome is null or chrome.browserAction is null");if(d(a))throw Error("invalid arguments to extensionAdapter.setBrowserIcon");
chrome.browserAction.setIcon(a,b)};g.sendMessage=function(a,b){if(d(chrome)||d(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(d(a))throw Error("invalid arguments to extensionAdapter.sendMessage");chrome.runtime.sendMessage(a,b)};g.sendMessageExternal=function(a,b,h){if(d(chrome)||d(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(d(a))throw Error("invalid arguments to extensionAdapter.sendMessage");if(d(b))throw Error("invalid arguments to extensionAdapter.sendMessage");
chrome.runtime.sendMessage(a,b,h)};g.sendMessageToTab=function(a,b,h,c){if(d(chrome)||d(chrome.tabs))throw Error("chrome or chrome.tabs is null");if(d(b)||d(a))throw Error("invalid arguments to extensionAdapter.sendMessageToTab");chrome.tabs.sendMessage(a.id,b,c,h)};g.addMessageListener=function(a){if(d(chrome)||d(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(!f(a))throw Error("invalid arguments to extensionAdapter.addMessageListener");chrome.runtime.onMessage.addListener(function(b,
h,k){return a(b,k,h.tab)})};g.addMessageExternalListener=function(a){if(d(chrome)||d(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(!f(a))throw Error("invalid arguments to extensionAdapter.addMessageExternalListener");chrome.runtime.onMessageExternal.addListener(function(b,h,k){return a(b,h,k)})};g.addContentScriptMessageListener=function(a){g.addMessageListener(a)};g.addTabCreatedEventListener=function(a){if(d(chrome)||d(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");
if(!f(a))throw Error("extensionAdapter.\u200baddTabCreatedEventListener needs a callback");chrome.tabs.onCreated.addListener(a)};g.addWindowCreatedEventListener=function(a){if(d(chrome)||d(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!f(a))throw Error("extensionAdapter.\u200baddWindowCreatedEventListener needs a callback");chrome.windows.onCreated.addListener(a)};g.getTabID=function(a){return d(a)?null:a.id};g.getWindowIDForTab=function(a){return d(a)?null:a.windowId};
g.getWindowID=function(a){return d(a)?null:a.id};g.i18nGetMessage=function(a,b){if(d(window.chrome)||d(window.chrome.i18n))throw Error("Unsupported api");if(!e(a))throw Error("chrome.i18n.getMessage expects a string messageName argument");return chrome.i18n.getMessage(a,b)};g.hidePopup=function(){window.open("","_self").close()};g.setBadgeText=function(a,h){if(d(chrome)||d(chrome.browserAction))throw Error("chrome or chrome.browserAction is null");if(!e(a)||4<a.length)throw Error("invalid arguments to extensionAdapter.setBadgeText");
a={text:a};b(h)&&(a.tabId=h);chrome.browserAction.setBadgeText(a)};g.setBadgeBackgroundColor=function(a){if(d(chrome)||d(chrome.browserAction))throw Error("chrome or chrome.browserAction is null");if(!e(a))throw Error("invalid arguments to extensionAdapter.setBadgeBackgroundColor");chrome.browserAction.setBadgeBackgroundColor({color:a})};g.onPopoverLoad=function(a){window.addEventListener("load",a)};g.getAllHistory=function(){return new Promise(function(a){chrome.history.search({text:"",startTime:0,
maxResults:c},function(b){var h=[];b=$jscomp.makeIterator(b);for(var c=b.next();!c.done;c=b.next())c=c.value,e(c.url)&&h.push(c.url);a(h)})})};g.addUrlsToHistory=function(a){if(!h(a))throw Error("urls must be an array");var b=[];a=$jscomp.makeIterator(a);for(var c=a.next();!c.done;c=a.next())b.push(g.addUrlToHistory(c.value));return Promise.all(b)};g.clearHistory=function(){return new Promise(function(a){chrome.history.deleteAll(function(){a()})})};g.addUrlToHistory=function(a){if(!e(a))throw Error("url must be a string");
return new Promise(function(b){chrome.history.addUrl({url:a},function(){b()})})};g.getAllCookies=function(){return new Promise(function(a){chrome.cookies.getAll({},function(b){a(b)})})};g.removeCookie=function(a){if(d(a))throw Error("cookie cannot be null");var b=(a.secure?"https://":"http://")+a.domain+a.path;return new Promise(function(h,c){chrome.cookies.remove({name:a.name,url:b},function(a){d(a)&&c(chrome.runtime.lastError);h(a)})})};g.removeCookies=function(a){if(!h(a))throw Error("cookiesArray must be array");
var b=[];a=$jscomp.makeIterator(a);for(var c=a.next();!c.done;c=a.next())b.push(g.removeCookie(c.value));return Promise.all(b)};g.setCookie=function(a){if(d(a))throw Error("cookie cannot be null");var h={url:(new URL((a.secure?"https://":"http://")+a.domain)).toString(),httpOnly:a.httpOnly,name:a.name,sameSite:a.sameSite,secure:a.secure,storeId:a.storeId,value:a.value,path:a.path};e(a.domain)&&"."===a.domain.charAt()&&(h.domain=a.domain);b(a.expirationDate)&&(h.expirationDate=a.expirationDate);return new Promise(function(a,
c){chrome.cookies.set(h,function(h){var f=chrome.runtime.lastError;d(h)&&b(f)&&c(f);a(h)})})};g.setCookies=function(a){if(!h(a))throw Error("cookiesArray must be array");var b=[];a=$jscomp.makeIterator(a);for(var c=a.next();!c.done;c=a.next())b.push(g.setCookie(c.value));return Promise.all(b)};g.init=function(){};g.returnAdapter=function(){var a={};a.getExtensionURL=g.getExtensionURL;a.getBackgroundPage=g.getBackgroundPage;a.sendMessage=g.sendMessage;a.addMessageListener=g.addMessageListener;a.addContentScriptMessageListener=
g.addContentScriptMessageListener;a.getExtensionId=g.getExtensionId;a.init=g.init;try{return chrome.tabs?g:a}catch(n){return a}};return g.returnAdapter()}(e.SymBfw)})(this);
(function(e){e.SymBfw.clipboard=function(c){var a={},g=c.utils.isNil,d=c.logger;a.createDummyTextAreaAndSetText=function(a){var b=document.createElement("textarea");b.style.position="fixed";b.style.top=0;b.style.left=0;b.style.width="2em";b.style.height="2em";b.style.padding=0;b.style.border="none";b.style.outline="none";b.style.boxShadow="none";b.style.background="transparent";b.value=a;document.body.appendChild(b);b.select();return b};a.copyToClipboard=function(b){if(g(b)||""===b)throw Error("Value to copy to clipboard cannot be null");
b=a.createDummyTextAreaAndSetText(b);document.execCommand("copy")||d.error("Failed to copy to clipboard");document.body.removeChild(b)};return a}(e.SymBfw)})(this);
(function(e){(e.SymBfw=e.SymBfw||{}).storage=function(c){var a={},g=c.utils.isNil,d=c.utils.isntNil,b=c.utils.isFunction,e=c.logger,l=function(a,b){this.name=a;this.error=b};l.prototype.toString=function(){return"Name:"+this.name+":Error:"+this.error};a.StorageException=l;a.set=function(a,h,c){if(g(a))throw Error("Key cannot be null");if(g(h))throw Error("Value cannot be null");var f={};f[a]=h;chrome.storage.local.set(f,function(){var f=chrome.runtime.lastError,d=!1,k=null;g(f)?d=!0:(e.log("Storing{"+
a+":"+h+"} caused an error:"+f),k=new l("Browser Exception",f));b(c)&&setTimeout(function(){c(d,k)},1)})};a.get=function(a,h){if(g(a))throw Error("Key cannot be null");if(!b(h))throw Error("Callback cannot be null or is not a function");chrome.storage.local.get(a,function(b){var c=chrome.runtime.lastError,f=!1,k=null,q=null;k=b[a];g(c)&&d(k)?f=!0:(e.log("Getting value for "+a+" caused an error:"+c),q=new l("Browser Exception",c));setTimeout(function(){h(f,k,q)},1)})};a.clear=function(a){chrome.storage.local.clear(function(){var h=
chrome.runtime.lastError,c=null,f=!1;g(h)?f=!0:c=new l("Browser Exception",h);b(a)&&setTimeout(function(){a(f,c)},1)})};a.remove=function(a,h){if(g(a))throw Error("Key cannot be null");chrome.storage.local.remove(a,function(){var a=chrome.runtime.lastError,c=null,f=!1;g(a)?f=!0:c=new l("Browser Exception",a);b(h)&&setTimeout(function(){h(f,c)},1)})};return a}(e.SymBfw)})(this);
(function(e){e.SymBfw.settings=function(c){var a={containers:{}},g=c.storage,d=c.utils.isntNil,b=c.utils.isNil,e=c.utils.isFunction,l=c.logger,f=function(b,c){if(d(a.containers[b]))throw Error("Container name is not unique");this.name=b;this.persist=c;this.collection={};this.initialized=!1};f.prototype.initialize=function(b){var c=this.name,h=this;this.initialized=!0;if(!1===this.persist)a.containers[c]=this;else{var f=function(f,d){f?(a.containers[c]=h,setTimeout(function(){b(!0,h,null)},1)):setTimeout(function(){b(!1,
null,d)},1)};g.get(c,function(d,k,e){d?(h.setCollection(k),a.containers[c]=h,setTimeout(function(){b(!0,h,null)},1)):g.set(c,h.getCollection(),f)})}};f.prototype.setCollection=function(a){this.collection=a};f.prototype.getCollection=function(){return this.collection};f.prototype.setObject=function(a,c,f){if(b(a))throw Error("Key cannot be null");if(b(c))throw Error("Value cannot be null");if(!1===this.initialized)throw Error("Settings not initialized");this.collection[a]=c;!1===this.persist?e(f)&&
setTimeout(function(){f(!0,null)},1):g.set(this.name,this.collection,f)};f.prototype.getObject=function(a){if(b(a))throw Error("Key cannot be null");if(!1===this.initialized)throw Error("Settings not initialized");a=this.collection[a];b(a)&&(a=null);return a};f.prototype.removeObject=function(a,c){if(b(a))throw Error("Key cannot be null");if(!1===this.initialized)throw Error("Settings not initialized");delete this.collection[a];!1===this.persist?e(c)&&setTimeout(function(){c(!0,null)},1):g.set(this.name,
this.collection,c)};f.prototype.serialize=function(){return JSON.stringify(this.collection)};f.prototype.shouldPersist=function(){return this.persist};a.loadSettingsContainer=function(c,g,n){if(b(c))throw Error("Name cannot be null");b(g)&&(g=!1);if(g&&!e(n))throw Error("Callback cannot be null or is not a function");var h=a.containers[c];if(d(h)){if(!g)return h;setTimeout(function(){n(!0,h,null)},1)}else if(c=new f(c,g),c.initialize(n),!g)return c};a.deleteSettingsContainer=function(c,f){if(b(c))throw Error("Name cannot be null");
var h=a.containers[c];d(h)&&(a.containers[c]=null);!1===h.shouldPersist()?e(f)&&setTimeout(function(){f(!0,null)},1):g.remove(c,f)};a.resetSettingsCollection=function(c,f){if(b(c))throw Error("Name cannot be null");c=a.containers[c];if(b(c))throw Error("Container was never previously loaded");var h=c.getCollection();if(b(h))l.info("Collection is empty"),e(f)&&setTimeout(function(){f(!1,Error("Collection is empty"))},1);else{for(var d in h)delete h[d];!1===c.shouldPersist()?e(f)&&setTimeout(function(){f(!0,
null)},1):g.set(c.name,c.collection,f)}};a.Settings=f;return a}(e.SymBfw)})(this);
(function(e){e.SymBfw.secureSettings=function(c){var a={},g=c.settings,d=c.utils.isntNil,b=c.utils.isNil,e=c.utils.isFunction,l=c.utils.isString,f=c.logger,h=function(a){var b=forge.md.sha256.create();b.update(a);return b.digest().toHex()},k=function(a,b){var c=forge.hmac.create();c.start("sha256",b);c.update(a);return c.digest().toHex()},n=function(a,b,c,h,f){b=forge.util.createBuffer(b);a=a?forge.cipher.createCipher(f,c):forge.cipher.createDecipher(f,c);a.start({iv:h});a.update(b);a.finish();return a.output.getBytes()},
p=function(a,b){this.initialized=!1};p.prototype.initialize=function(a,c,h){var e=this;g.loadSettingsContainer(a,!0,function(l,n,q){if(!1===l)setTimeout(function(){h(!1,null,q)},1);else{var m=n.getObject("iv"),p=n.getObject("salt");l=null;if(b(m)||b(p))l=new Promise(function(b,c){g.resetSettingsCollection(a,function(a,h){if(!a)return c(Error("Failed to reset OCL container"));e.iv=forge.random.getBytesSync(128);e.salt=forge.random.getBytesSync(128);n.setObject("iv",JSON.stringify(e.iv));n.setObject("salt",
JSON.stringify(e.salt));b()})});else try{e.iv=JSON.parse(m),e.salt=JSON.parse(p)}catch(u){setTimeout(function(){var a="Failed to intialize: "+u.toString();f.error(u);h(!1,null,a)},1);return}m=function(){e.derivedKey=forge.pkcs5.pbkdf2(c,e.salt,1E3,32);var a=n.getObject("hmac"),b=k(e.salt,e.derivedKey);if(d(a)){if(a!==b){setTimeout(function(){h(!1,null,"Passwords does not match")},1);return}}else n.setObject("hmac",b);e.container=n;e.initialized=!0;setTimeout(function(){h(!0,e,null)},1)};b(l)?m():
l.then(m,function(a){f.error(a);h(!1,null,a)})}})};p.prototype.setObject=function(a,c,f){if(!l(a))throw Error("Key must be a string");if(b(c))throw Error("Value cannot be null");if(!this.initialized)throw Error("SecureSettings not initialized");a=h(a);c=JSON.stringify(c);c=n(!0,c,this.derivedKey,this.iv,"AES-CBC");c=forge.util.encode64(c);var d=k(c,this.derivedKey);this.container.setObject(a,{data:c,hmac:d},f)};p.prototype.getObject=function(a){if(!l(a))throw Error("Key must be a string");if(!this.initialized)throw Error("SecureSettings not initialized");
a=h(a);a=this.container.getObject(a);if(b(a))return null;var c=a.data;if(k(c,this.derivedKey)!==a.hmac)throw Error("The data is corrupted");a=forge.util.decode64(c);a=n(!1,a,this.derivedKey,this.iv,"AES-CBC");try{var d=JSON.parse(a)}catch(t){throw d="Failed to parse data: "+t.toString(),f.error(t),Error(d);}return d};p.prototype.removeObject=function(a,b){if(!l(a))throw Error("Key must be a string");if(!1===this.initialized)throw Error("SecureSettings not initialized");a=h(a);this.container.removeObject(a,
b)};a.loadSecureSettingsContainer=function(a,b,c){if(!l(a))throw Error("name must be a string");if(!l(b))throw Error("password must be a string");if(!e(c))throw Error("callback must be a function");b=h(b);(new p).initialize(a,b,c)};a.deleteSecureSettingsContainer=function(a,b){g.deleteSettingsContainer(a,b)};a.resetSecureSettingsCollection=function(a,c){if(b(a))throw Error("secureSettings container name is null");g.loadSettingsContainer(a,!0,function(a,b,h){if(!1===a)setTimeout(function(){e(c)&&c(!1,
h)},1);else{a=b.collection;for(var f in a)"salt"!==f&&"iv"!==f&&b.removeObject(f);e(c)&&c(!0,null)}})};a.SecureSettings=p;return a}(e.SymBfw)})(this);
(function(e){e.SymBfw.localizer=function(c){var a=c.utils.isNil,g=c.utils.isntNil,d=c.utils.isString,b=c.utils.isBoolean,e=c.utils.isArray,l=c.utils.isFunction,f=c.constants.localizer,h="ar he arc bcc bqi ckb dv fa glk lrc mzn pnb ps sd ug ur yi".split(" "),k={stringsMap:{},initialized:!1,setNavigatorLanguageAndLocale:function(){if(a(this.supportedLocales))throw Error("Supported locales was never set");var c=navigator.language,h=c.split("-"),f=h[0];h=h[1];var d=f.toLowerCase();g(h)&&(h=h.toLowerCase(),
d=d+"_"+h);var e=this.supportedLocales[d];b(e)&&e||(e=this.supportedLocales[f],b(e)&&e?d=f:(e=this.supportedLocales[h],b(e)&&e?d=h:(d="en",c="en-US")));this.locale=d;this.navigatorLanguage=c},getNavigatorLanguage:function(){if(g(this.navigatorLanguage))return this.navigatorLanguage;this.setNavigatorLanguageAndLocale();return this.navigatorLanguage},getLocale:function(){if(g(this.locale))return this.locale;this.setNavigatorLanguageAndLocale();return this.locale},getCurrentLanguageDirection:function(){var a=
k.getLocale(),b="ltr";-1<h.indexOf(a)&&(b="rtl");return b},loadDefaultDictionary:function(a){k.loadDictionary(f.DEFAULT_MESSAGES_DICTIONARY,a)},loadDictionary:function(b,h){if(!1===d(b))throw Error("Dictionary name cannot be null");if(!1===l(h))throw Error("Callback cannot be null");if(a(this.path))throw Error("Path to localized folder is not set. Need to call initialize before using this API");if(g(this.stringsMap[b]))setTimeout(function(){h(!0,null)},1);else{var f=this.getLocale(),e=this.path+"/"+
f+"/"+b+".json";f=new XMLHttpRequest;f.open("GET",e,!0);f.addEventListener("load",function(a){var f=a.target.status;f===("Safari"===c.globals.BROWSER?0:200)?(a=JSON.parse(a.target.response),k.stringsMap[b]=a,h(!0,null),k.initialized=!0):h(!1,Error("File at path:"+e+" does not exist. Status Code:"+f))});f.send()}},getLocalizedString:function(a){return k.getLocalizedStringFromDictionary(a,f.DEFAULT_MESSAGES_DICTIONARY)},getLocalizedStrings:function(a){return k.getLocalizedStringsFromDictionary(a,f.DEFAULT_MESSAGES_DICTIONARY)},
getAllLocalizedStrings:function(){return k.getAllLocalizedStringsFromDictionary(f.DEFAULT_MESSAGES_DICTIONARY)},getLocalizedStringFromDictionary:function(a,b){if(!1===d(a))throw Error("Unlocalized String cannot be null or is not a string");return k.getLocalizedStringsFromDictionary([a],b)[a]},getLocalizedStringsFromDictionary:function(b,c){if(!1===e(b))throw Error("Array of strings cannot be null.");if(0===b.length)throw Error("Array of strings cannot be empty.");if(!1===d(c))throw Error("Dictionary name cannot be null");
var h=this.stringsMap[c];if(a(h))throw Error("Dictionary "+c+" is being used without being loaded");c={};for(var f in b){var g=b[f],k=h[g];a(k)?c[g]=g:(k=k.message,a(k)?c[g]=g:c[g]=k)}return c},getAllLocalizedStringsFromDictionary:function(b){if(!1===d(b))throw Error("Dictionary name cannot be null");var c=this.stringsMap[b];if(a(c))throw Error("Dictionary "+b+" is being used without being loaded");b={};for(var h in c)b[h]=c[h].message;return b},getLocalizedStringWithFormat:function(a,b){return k.getLocalizedStringWithFormatFromDictionary(a,
b,f.DEFAULT_MESSAGES_DICTIONARY)},getLocalizedStringWithFormatFromDictionary:function(b,c,h){if(a(c))throw Error("Format parameters cannot be null");b=k.getLocalizedStringFromDictionary(b,h);for(var f in c)b=b.replace("{"+f+"}",c[f]);return b},getLocalizedStringFromNativeLocalizer:function(a,b){return c.extensionAdapter.i18nGetMessage(a,b)},initialize:function(b,h,f){if(a(b))throw Error("Supported locales cannot be null");a(f)&&(f=c.extensionAdapter.getExtensionURL("content/i18n"));k.path=f;this.supportedLocales=
b;c.extensionAdapter.addMessageListener(k.handleMessage);k.loadDefaultDictionary(h)},handleMessage:function(b,c,h){if(!a(b)){h=b.id;var d=b.payload;if(!a(h)&&!a(d)){var g=null,e=!0;switch(h){case f.GET_LOCALIZED_STRING:g=k.getLocalizedString(d);break;case f.GET_LOCALIZED_STRINGS:g=k.getLocalizedStrings(d);break;case f.GET_ALL_LOCALIZED_STRINGS:g=k.getAllLocalizedStrings(d);break;case f.GET_LOCALIZED_STRING_FROM_DICTIONARY:g=k.getLocalizedStringFromDictionary(d.string,d.name);break;case f.GET_LOCALIZED_STRINGS_FROM_DICTIONARY:g=
k.getLocalizedStringsFromDictionary(d.array,d.name);break;case f.GET_LOCALIZED_STRING_WITH_FORMAT:g=k.getLocalizedStringWithFormat(d.string,d.params);break;case f.GET_LOCALIZED_STRING_WITH_FORMAT_FROM_DICTIONARY:g=k.getLocalizedStringWithFormatFromDictionary(d.string,d.params,d.name);break;case f.GET_CURRENT_LANGUAGE_DIRECTION:g=k.getCurrentLanguageDirection();break;default:e=!1}e&&c({id:b.id,payload:g})}}}};return k}(e.SymBfw)})(this);
(function(e){e=e.SymBfw=e.SymBfw||{};var c={APPLICATION_NAME:"APPLICATION_NAME",APPLICATION_VERSION:"APPLICATION_VERSION",CLIENT_ID:"CLIENT_ID",DATA_SOURCE:"DATA_SOURCE",TRACKING_ID:"TRACKING_ID",USER_AGENT:"USER_AGENT",USER_LANGUAGE:"USER_LANGUAGE",GOOGLE_ANALYTICS_PROTOCOL_VERSION:"GOOGLE_ANALYTICS_PROTOCOL_VERSION",ANONYMIZE_IP:"ANONYMIZE_IP"};c.defaultParametersList=[c.APPLICATION_NAME,c.APPLICATION_VERSION,c.CLIENT_ID,c.DATA_SOURCE,c.TRACKING_ID,c.GOOGLE_ANALYTICS_PROTOCOL_VERSION,c.ANONYMIZE_IP];
c.dataSource={BROWSER_EXTENSION:"web",MOBILE_APP:"app"};c.HIT_TYPE={PAGE_VIEW:"pageview",SCREEN_VIEW:"screenview",EVENT:"event",EXCEPTION:"exception"};c.MESSAGES={SEND_TELEMETRY_TO_BGPROXY:"b021e29a-4fe3-4a60-865f-0cf783318187"};c.parameters={NON_INTERACTION_HIT:"ni",HIT_TYPE:"t",CATEGORY:"ec",ACTION:"ea",LABEL:"el",DOCUMENT_PATH:"dp",DOCUMENT_TITLE:"dt",CUSTOM_DIMENSION1:"cd1",PRODUCT_IMPRESSION_BRAND1:"il1pi1br",ITEM_CATEGORY:"iv",CAMPAIGN_SOURCE:"cs",CAMPAIGN_MEDIUM:"cm"};c.TELEMETRY_CATEGORY=
{BROWSER:"Browser",EXTENSION:"Extension"};c.actionType={BROWSER:{LAUNCH:"launch",UPDATE:"update"},EXTENSION:{INSTALL:"install",UPDATE:"update"}};c.defaultParameters={APPLICATION_NAME:{maxLength:100,key:"an"},APPLICATION_VERSION:{maxLength:100,key:"av"},CLIENT_ID:{maxLength:100,key:"cid"},DATA_SOURCE:{maxLength:50,key:"ds",value:c.dataSource.BROWSER_EXTENSION},TRACKING_ID:{maxLength:100,key:"tid"},USER_AGENT:{maxLength:1E3,key:"ua"},USER_LANGUAGE:{maxLength:20,key:"ul"},GOOGLE_ANALYTICS_PROTOCOL_VERSION:{maxLength:100,
key:"v",value:1},ANONYMIZE_IP:{maxLength:1,key:"aip",value:1}};e.telemetryConstants=c})(this);
(function(e){e.SymBfw.telemetrySettings=function(c){var a={},g=c.settings,d=c.utils.isNil,b=c.utils.isBoolean,e=c.utils.isFunction,l=c.constants,f=c.logger;a.settingsContainer=null;a.initialize=function(b){if(!e(b))throw Error("callback must be a function");g.loadSettingsContainer(l.telemetry.BFW_TELEMETRY_SETTINGS_CONTAINER,!0,function(c,h,g){!1===c||d(h)?(f.error("failed to load BFW_TELEMETRY_SETTINGS_CONTAINER"),b(!1)):(a.settingsContainer=h,b(!0))})};a.isTelemetryEnabled=function(){if(d(this.settingsContainer))return f.log("Settings not initialized"),
!1;var a=this.settingsContainer.getObject(l.telemetry.TELEMETRY_ENABLED);return d(a)?!1:a};a.setTelemetryEnabled=function(a){if(d(this.settingsContainer))throw Error("Settings not initialized");if(!b(a))throw Error("Parameter must be a boolean");this.settingsContainer.setObject(l.telemetry.TELEMETRY_ENABLED,a)};a.isTelemetryOptOutShown=function(){if(d(this.settingsContainer))throw Error("Settings not initialized");var a=this.settingsContainer.getObject(l.telemetry.TELEMETRY_OPT_OUT_SHOWN);return d(a)?
!1:a};a.setTelemetryOptOutShown=function(a){if(d(this.settingsContainer))throw Error("Settings not initialized");if(!b(a))throw Error("Parameter must be a boolean");this.settingsContainer.setObject(l.telemetry.TELEMETRY_OPT_OUT_SHOWN,a)};a.hasUserRespondedInOptOutPage=function(){if(d(this.settingsContainer))return f.log("Settings not initialized"),!1;var a=this.settingsContainer.getObject(l.telemetry.USER_RESPONDED_IN_OPT_OUT_PAGE);return d(a)?!1:a};a.setUserRespondedInOptOutPage=function(a){if(d(this.settingsContainer))throw Error("Settings not initialized");
if(!b(a))throw Error("Parameter must be a boolean");this.settingsContainer.setObject(l.telemetry.USER_RESPONDED_IN_OPT_OUT_PAGE,a,function(a){c.telemetry.flushQueue()})};a.setLastOfferDate=function(a){if(d(a))throw Error("Date cannot be null.");this.settingsContainer.setObject(l.telemetry.LAST_OFFER_DATE,a.getTime())};a.getLastOfferDate=function(){var a=this.settingsContainer.getObject(l.telemetry.LAST_OFFER_DATE);return d(a)||!1===c.utils.isInteger(a)?null:new Date(a)};return a}(e.SymBfw)})(this);
(function(e){(e.SymBfw=e.SymBfw||{}).telemetrySCD=function(c){var a={GOOGLE_ANALYTICS_URL:"https://www.google-analytics.com/collect",REQUEST_TYPE:"POST",COLLECTION_STATE:!0,serialize:function(){return{ga_url:a.GOOGLE_ANALYTICS_URL,request_type:a.REQUEST_TYPE,collection_state:a.COLLECTION_STATE}}};return a}(e.SymBfw)})(this);
(function(e){e.SymBfw.Telemetry=function(c){var a=c.utils.isNil,g=c.utils.isntNil,d=c.utils.isFunction,b=c.telemetryConstants,e=c.logger,l=c.utils.isBoolean,f=function(a,c){this.defaultParameters=null;this.initialized=!1;this._telemetryParamsQueue=[];g(a)?this.message=a:this.message=b.MESSAGES.SEND_TELEMETRY_TO_BGPROXY;this.ignoreTelemetryEnableSettings=!1;l(c)&&!0===c&&(this.ignoreTelemetryEnableSettings=!0)};f.prototype.constructMessageBody=function(b){if(a(b))throw Error("parameters cannot be null");
if(0===Object.keys(b).length)throw Error("parameters object is empty. Need at-least one property");var c="",f;for(f in b)c+=f+"="+b[f]+"&";return c=c.substring(0,c.length-1)};f.prototype.init=function(f,g){var h=this;if(!0!==this.initialized){if(a(f))throw Error("defaultParameters cannot be null");if(!d(g))throw Error("callback is not defined or is not a function");c.telemetryConstants.defaultParametersList.forEach(function(b){if(a(f[b]))throw Error("could not find mandatory parameter "+b+" in parameters list");
});var k={};for(m in f){var l=c.telemetryConstants.defaultParameters[m];a(l.key)||(k[l.key]=f[m])}var m=b.defaultParameters[b.USER_LANGUAGE];a(k[m.key])&&(k[m.key]=navigator.language);var r=this.constructMessageBody(k);if(a(r)||0===r.length)throw Error("constructMessageBody returned an empty string");c.telemetrySettings.initialize(function(a){!1===a?(e.error("failed to initialize BfwTelemetry"),g(!1)):(c.extensionAdapter.addMessageListener(h.handleMessage.bind(h)),h.defaultParameters=r,h.initialized=
!0,g(!0))})}};f.prototype.send=function(b){if(!1===this.ignoreTelemetryEnableSettings&&!1===c.telemetrySettings.isTelemetryEnabled())return!1===c.telemetrySettings.hasUserRespondedInOptOutPage()&&g(this._telemetryParamsQueue)&&this._telemetryParamsQueue.push(b),!1;if(a(this.defaultParameters)||!1===this.initialized)return!1;if(a(b))throw Error("parameters are required for sending telemetry events");var f=new XMLHttpRequest;f.open(c.telemetrySCD.REQUEST_TYPE,c.telemetrySCD.GOOGLE_ANALYTICS_URL,!0);
f.addEventListener("load",function(a){e.debug("xhr load status: "+a.target.status)});f.addEventListener("error",function(a){e.debug("xhr error status: "+a.target.status)});b=this.constructMessageBody(b);if(a(b)||0===b.length)return!1;b+="&"+this.defaultParameters;f.send(b);return!0};f.prototype.handleMessage=function(b,c,f){var h=this;if(b.id===this.message&&(c=b.payload,!a(c)&&!a(c.parameters)))return setTimeout(function(){h.send(b.payload.parameters)}),!0};f.prototype.flushQueue=function(){var a=
this;setTimeout(function(){for(var b in a._telemetryParamsQueue)a.send(a._telemetryParamsQueue[b]);a._telemetryParamsQueue=null},2E3)};return f}(e.SymBfw);e.SymBfw.telemetry=new SymBfw.Telemetry})(this);
(function(e){e.SymBfw.telemetryWrapper=function(c){var a=c.utils.isNil,g=c.utils.isString,d={TELEMETRY_CATEGORY:"bfw",TELEMETRY_TYPE:"event",componentType:{LOGGER:"logger",LOCALIZER:"localizer",STORAGE:"storage",SETTINGS:"settings",SECURE_SETTINGS:"secureSettings"},actionType:{WARN:"warn",ERROR:"error"},parameters:{EVENT:"t",CATEGORY:"ec",ACTION:"ea",PAYLOAD:"el"},send:function(b,e,l){if(!g(b))throw Error("componentType should be a string");if(!g(e))throw Error("actionType should be a string");if(a(l))throw Error("payload should not be Nil");
if(!g(l)){if(!(l instanceof Error))throw Error("payload should be an instanceof Error other than a string");l=l.toString()}var f={};f[d.parameters.EVENT]=d.TELEMETRY_TYPE;f[d.parameters.CATEGORY]=d.TELEMETRY_CATEGORY+"-"+b;f[d.parameters.ACTION]=e;f[d.parameters.PAYLOAD]=l;return(c.telemetry||c.telemetryProxy).send(f)}};return d}(e.SymBfw)})(this);
(function(e){e.SymBfw.Notification=function(c){var a=c.constants.uiConstants,g=c.utils.isNil,d=c.utils.isntNil,b=c.extensionAdapter,e=function(b,f,h,e){if(g(b))throw Error("A description must be provided.");if(g(f))throw Error("A type must be provided.");if(g(h))throw Error("imageUrl must be provided");d(e)?this.title=e:this.title="";switch(f){case a.NOTIFICATION.TYPE.QUESTION:case a.NOTIFICATION.TYPE.TIMED:break;default:throw Error("The notification type passed was not recognized.");}this.description=
b;this.type=f;this.guid=c.utils.createNewGuid();this.imageUrl=h};e.prototype.getDescription=function(){return this.description};e.prototype.setID=function(a){this.guid=a};e.prototype.getID=function(){return this.guid};e.prototype.getType=function(){return this.type};e.prototype.getTitle=function(){return this.title};e.prototype.getImage=function(){return b.getExtensionURL(this.imageUrl)};e.prototype.getRelativeImageURL=function(){return this.imageUrl};e.prototype.handleEvent=function(a){};e.prototype.serialize=
function(){return{description:this.description,type:this.type,notificationID:this.guid,imageUrl:this.getRelativeImageURL(),title:this.title}};e.prototype.onDisplayed=function(){};return e}(e.SymBfw)})(this);
(function(e){e.SymBfw.QuestionNotification=function(c){var a=c.utils.isNil,g=c.utils.isntNil,d=c.utils.isFunction,b=c.logger,e=c.Notification,l=c.constants.uiConstants;c=function(b,c,g,m,p,v,q){q=void 0===q?[]:q;e.call(this,b,l.NOTIFICATION.TYPE.QUESTION,p,v);if(a(c))throw Error("Data cannot be null");if(a(g))throw Error("Default button text cannot be null.");if(!1===d(m))throw Error("Default button action cannot be null.");this.data=c;this.defaultButtonText=g;this.defaultButtonAction=m;this.blockListedUrls=
q};c.prototype=Object.create(e.prototype);c.prototype.addSecondaryLink=function(b,c){if(a(b))throw Error("Secondary link text cannot be null.");if(!1===d(c))throw Error("Secondary link action cannot be null.");this.secondaryLinkText=b;this.secondaryLinkAction=c};c.prototype.addThirdButton=function(b,c){if(a(b))throw Error("Third button text cannot be null");if(!1===d(c))throw Error("Third button action cannot be null.");this._thirdButtonText=b;this._thirdButtonAction=c};c.prototype.addCloseButtonAction=
function(a){if(!1===d(a))throw Error("Close button action cannot be null.");this._closeButtonAction=a};c.prototype.getDefaultButtonAction=function(){return this.defaultButtonAction};c.prototype.getSecondaryLinkAction=function(){return this.secondaryLinkAction};c.prototype.getThirdButtonAction=function(){return this._thirdButtonAction};c.prototype.getCloseButtonAction=function(){return this._closeButtonAction};c.prototype.serialize=function(){return{description:this.getDescription(),type:this.getType(),
title:this.getTitle(),defaultButton:this.defaultButtonText,secondaryLink:this.secondaryLinkText,thirdButton:this._thirdButtonText,notificationID:this.getID(),imageUrl:this.getRelativeImageURL(),blockListedUrls:this.blockListedUrls}};c.prototype.getData=function(){return this.data};c.prototype.handleEvent=function(c){switch(c){case l.NOTIFICATION.MESSAGES.DEFAULT_BUTTON_PRESSED:c=this.getDefaultButtonAction();break;case l.NOTIFICATION.MESSAGES.SECONDARY_LINK_PRESSED:c=this.getSecondaryLinkAction();
break;case l.NOTIFICATION.MESSAGES.THIRD_BUTTON_PRESSED:c=this.getThirdButtonAction();break;case l.NOTIFICATION.MESSAGES.NOTIFICATION_CLOSED:c=a(this.getCloseButtonAction())?null:this.getCloseButtonAction();break;default:return}var f=this.getData();if(g(c))try{c(f)}catch(k){b.error(k)}};return c}(e.SymBfw)})(this);
(function(e){e.SymBfw.TimedNotification=function(c){var a=c.Notification,g=c.constants.uiConstants,d=function(b,c,d){a.call(this,b,g.NOTIFICATION.TYPE.TIMED,c,d)};d.prototype=Object.create(a.prototype);d.prototype.onDisplayed=function(){var a=this.getID();setTimeout(function(){c.notificationCenter.removeNotification(a)},g.NOTIFICATION.DEFAULT_TIMEOUT)};return d}(e.SymBfw)})(this);
(function(e){e.SymBfw.notificationCenter=function(c){var a=c.utils.isNil,g=c.logger,d=c.extensionAdapter,b=c.constants.uiConstants,e={queue:[],addNotification:function(c){if(a(c))throw Error("Notification cannot be null");var f=c.getType();switch(f){case b.NOTIFICATION.TYPE.TIMED:chrome.notifications.create({type:"basic",iconUrl:c.getImage(),title:c.getTitle(),message:c.getDescription()},function(a){c.setID(a);c.onDisplayed()});break;case b.NOTIFICATION.TYPE.QUESTION:this.queue.push(c);e.refreshQueue();
break;default:throw Error("Unsupported notification type: "+f);}},removeNotification:function(b){if(a(b))throw Error("NotificationID cannot be null");for(var c in this.queue)if(this.queue[c].getID()===b){this.queue.splice(c,1);break}try{chrome.notifications.clear(b)}catch(h){g.info(h)}finally{e.refreshQueue()}},getNotification:function(b){if(a(b))throw Error("NotificationID cannot be null");for(var c in this.queue)if(this.queue[c].getID()===b)return this.queue[c]},refreshQueue:function(){d.getActiveTab(function(c){if(!a(c)){var f=
[],h;for(h in e.queue){var g=e.queue[h].serialize();f.push(g)}d.sendMessageToTab(c,{id:b.NOTIFICATION.MESSAGES.DEFAULT_MESSAGE,payload:{eventID:b.NOTIFICATION.MESSAGES.NOTIFICATION_QUEUE_MESSAGE,notificationArray:f}},null,{frameId:0})}})},handleActivate:function(){d.getAllTabs(function(a){a.forEach(function(a){d.sendMessageToTab(a,{id:b.NOTIFICATION.MESSAGES.DEFAULT_MESSAGE,payload:{eventID:b.NOTIFICATION.MESSAGES.HIDE_NOTIFICATIONS}})});e.refreshQueue()})},handleMessage:function(c,f){if(!a(c)){var h=
c.eventID;if(!a(h)){var k=c.notificationID;switch(h){case b.NOTIFICATION.MESSAGES.DEFAULT_BUTTON_PRESSED:case b.NOTIFICATION.MESSAGES.SECONDARY_LINK_PRESSED:case b.NOTIFICATION.MESSAGES.THIRD_BUTTON_PRESSED:case b.NOTIFICATION.MESSAGES.NOTIFICATION_CLOSED:if(a(k)){g.warn("Notification ID cannot be null when eventID is "+b.NOTIFICATION.MESSAGES.DEFAULT_BUTTON_PRESSED);break}c=e.getNotification(k);if(a(c))break;c.handleEvent(h);e.removeNotification(k);break;case b.NOTIFICATION.MESSAGES.NOTIFICATION_QUEUE_MESSAGE:e.refreshQueue();
break;case b.NOTIFICATION.MESSAGES.NOTIFICATIONS_SHOWN:h=c.notificationArray;for(var l in h)if(k=h[l],c=e.getNotification(k),!a(c))c.onDisplayed();break;case b.NOTIFICATION.MESSAGES.HIDE_NOTIFICATIONS:d.sendMessageToTab(f,{id:b.NOTIFICATION.MESSAGES.DEFAULT_MESSAGE,payload:{eventID:b.NOTIFICATION.MESSAGES.HIDE_NOTIFICATIONS}})}}}},getSerializedNotifications:function(){var a=[],b;for(b in e.queue)a.push(e.queue[b]);return a},init:function(){var g=function(){e.handleActivate()};d.addWindowFocusedEventListener(g);
d.addTabActivatedEventListener(g);d.addMessageListener(function(f,h,d){if(!a(f)&&!a(f.id))switch(f.id){case b.NOTIFICATION.MESSAGES.UI_INIT:return f.id=b.NOTIFICATION.MESSAGES.UI_INIT_PROXY,c.extensionAdapter.sendMessageToTab(d,f,function(a){h(a)}),!0;case b.NOTIFICATION.MESSAGES.DEFAULT_MESSAGE:return e.handleMessage(f.payload,d)}})}};e.init();return e}(e.SymBfw)})(this);
(function(e){e.SymBfw.performanceReporterFactory=function(c){var a=c.utils.isNil,e=c.utils.isntNil,d=c.extensionAdapter,b=c.constants.performanceReporter.MESSAGES,m={_reporters:{},AUTOMATION_MODE:!1},l=function(b){if(a(b))throw Error("component cannot be null");this.component=b;this.start=Date.now();this.subComponents={};this.tldReports={}};l.prototype._reportStart=function(a){if(e(this.subComponents[a]))throw Error("type already exists");this.subComponents[a]={};this.subComponents[a].start=Date.now()};
l.prototype._reportEnd=function(b){if(a(this.subComponents[b]))throw Error("type does NOT exists");if(e(this.subComponents[b].stop))console.warn("already reported this type");else{var c=Date.now(),f=this.subComponents[b].start;this.subComponents[b].stop=c;this.subComponents[b].timeTaken=c-f}};l.prototype._reportStartFromProxy=function(b,c,d,g){if(a(b))throw Error("type cannot be null");if(a(c))throw Error("domain cannot be null");if(a(d))throw Error("frameURL cannot be null");if(a(g))throw Error("frameGUID cannot be null");
c=this.tldReports[c][g].subComponents;if(e(c[b]))throw Error("Sub-component Type already started");c[b]={};c[b].start=Date.now()};l.prototype._reportEndFromProxy=function(b,c,d,g){if(a(b))throw Error("type cannot be null");if(a(c))throw Error("domain cannot be null");if(a(d))throw Error("frameURL cannot be null");if(a(g))throw Error("frameGUID cannot be null");if(a(this.tldReports[c]))throw Error("Component for TLD not properly initialized");if(a(this.tldReports[c][g]))throw Error("Component for TLD - frameGUID, not properly initialized");
c=this.tldReports[c][g].subComponents;if(a(c[b].start))throw Error("type did not start");e(c[b].stop)?console.warn("Sub-component Type already ended"):(c[b].stop=Date.now(),c[b].timeTaken=c[b].stop-c[b].start)};l.prototype._createOrGetTLDDict=function(b,c,d){if(a(b))throw Error("domain cannot be NULL");if(a(c))throw Error("frameURL cannot be NULL");if(a(d))throw Error("frameGUID cannot be NULL");a(this.tldReports[b])&&(this.tldReports[b]={});a(this.tldReports[b][d])&&(this.tldReports[b][d]={},this.tldReports[b][d].start=
Date.now(),this.tldReports[b][d].frameURL=c,this.tldReports[b][d].subComponents={})};l.prototype.serialize=function(){var a={};a[this.component]={};a[this.component].start=this.start;a[this.component].stop=Date.now();a[this.component].timeTaken=a[this.component].stop-this.start;a[this.component].subComponents=this.subComponents;for(var b in this.tldReports)a[this.component][b]=this.tldReports[b];return a};m.serialize=function(){var a=[],b;for(b in this._reporters){var c=this._reporters[b].serialize();
a.push(c)}return a};m._getPerformanceReporter=function(a){var b=m._reporters[a];if(e(b))return b;b=new l(a);return m._reporters[a]=b};m.reportStartForComponent=function(b,c){if(!1!==m.AUTOMATION_MODE){if(a(b))throw Error("component cannot be NULL");if(a(c))throw Error("type cannot be NULL");m._getPerformanceReporter(b)._reportStart(c)}};m.reportStopForComponent=function(b,c){if(!1!==m.AUTOMATION_MODE){if(a(b))throw Error("component cannot be NULL");if(a(c))throw Error("type cannot be NULL");m._getPerformanceReporter(b)._reportEnd(c)}};
m._getPerformanceReporterFromProxy=function(b,c,d,e){if(a(d))throw Error("domain cannot be null");if(a(e))throw Error("frameURL cannot be null");if(a(c))throw Error("frameGUID cannot be null");b=m._getPerformanceReporter(b);b._createOrGetTLDDict(d,e,c);return b};m.handleMessage=function(c,d,e){if(!1!==m.AUTOMATION_MODE&&!a(c))switch(d=c.payload,c.id){case b.REPORT_START:var f=d.component;c=d.guid;var g=d.frameURL;f=m._getPerformanceReporterFromProxy(f,c,e.url,g);d=d.type;f._reportStartFromProxy(d,
e.url,g,c);break;case b.REPORT_END:f=d.component,c=d.guid,g=d.frameURL,f=m._getPerformanceReporter(f),d=d.type,f._reportEndFromProxy(d,e.url,g,c)}};d.addMessageListener(m.handleMessage);m.PerformanceReporter=l;return m}(e.SymBfw)})(this);
