var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,a,b){c!=Array.prototype&&c!=Object.prototype&&(c[a]=b.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var c=0;return function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+c++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(c){var a=0;return $jscomp.iteratorPrototype(function(){return a<c.length?{done:!1,value:c[a++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.makeIterator=function(c){$jscomp.initSymbolIterator();var a=c[Symbol.iterator];return a?a.call(c):$jscomp.arrayIterator(c)};$jscomp.arrayFromIterator=function(c){for(var a,b=[];!(a=c.next()).done;)b.push(a.value);return b};$jscomp.arrayFromIterable=function(c){return c instanceof Array?c:$jscomp.arrayFromIterator($jscomp.makeIterator(c))};
$jscomp.polyfill=function(c,a,b,f){if(a){b=$jscomp.global;c=c.split(".");for(f=0;f<c.length-1;f++){var d=c[f];d in b||(b[d]={});b=b[d]}c=c[c.length-1];f=b[c];a=a(f);a!=f&&null!=a&&$jscomp.defineProperty(b,c,{configurable:!0,writable:!0,value:a})}};$jscomp.polyfill("Object.is",function(c){return c?c:function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(c){return c?c:function(a,b){var c=this;c instanceof String&&(c=String(c));var d=c.length;b=b||0;for(0>b&&(b=Math.max(b+d,0));b<d;b++){var h=c[b];if(h===a||Object.is(h,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(c,a,b){if(null==c)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return c+""};$jscomp.polyfill("String.prototype.includes",function(c){return c?c:function(a,b){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,b||0)}},"es6","es3");
$jscomp.iteratorFromArray=function(c,a){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var b=0,f={next:function(){if(b<c.length){var d=b++;return{value:a(d,c[d]),done:!1}}f.next=function(){return{done:!0,value:void 0}};return f.next()}};f[Symbol.iterator]=function(){return f};return f};$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
$jscomp.checkEs6ConformanceViaProxy=function(){try{var c={},a=Object.create(new $jscomp.global.Proxy(c,{get:function(b,f,d){return b==c&&"q"==f&&d==a}}));return!0===a.q}catch(b){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.owns=function(c,a){return Object.prototype.hasOwnProperty.call(c,a)};
$jscomp.polyfill("WeakMap",function(c){function a(){if(!c||!Object.seal)return!1;try{var a=Object.seal({}),b=Object.seal({}),d=new c([[a,2],[b,3]]);if(2!=d.get(a)||3!=d.get(b))return!1;d.delete(a);d.set(b,4);return!d.has(a)&&4==d.get(b)}catch(n){return!1}}function b(a){$jscomp.owns(a,d)||$jscomp.defineProperty(a,d,{value:{}})}function f(a){var k=Object[a];k&&(Object[a]=function(a){b(a);return k(a)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(c&&$jscomp.ES6_CONFORMANCE)return c}else if(a())return c;
var d="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0,l=function(a){this.id_=(h+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};l.prototype.set=function(a,k){b(a);if(!$jscomp.owns(a,d))throw Error("WeakMap key fail: "+a);a[d][this.id_]=k;return this};l.prototype.get=function(a){return $jscomp.owns(a,d)?a[d][this.id_]:void 0};l.prototype.has=
function(a){return $jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)};l.prototype.delete=function(a){return $jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)?delete a[d][this.id_]:!1};return l},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(c){function a(){if($jscomp.ASSUME_NO_NATIVE_MAP||!c||"function"!=typeof c||!c.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),b=new c($jscomp.makeIterator([[a,"s"]]));if("s"!=b.get(a)||1!=b.size||b.get({x:4})||b.set({x:4},"t")!=b||2!=b.size)return!1;var d=b.entries(),g=d.next();if(g.done||g.value[0]!=a||"s"!=g.value[1])return!1;g=d.next();return g.done||4!=g.value[0].x||"t"!=g.value[1]||!d.next().done?!1:!0}catch(v){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(c&&$jscomp.ES6_CONFORMANCE)return c}else if(a())return c;$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=new WeakMap,f=function(a){this.data_={};this.head_=l();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};f.prototype.set=function(a,b){var k=d(this,a);k.list||(k.list=this.data_[k.id]=[]);k.entry?k.entry.value=b:(k.entry={next:this.head_,previous:this.head_.previous,head:this.head_,
key:a,value:b},k.list.push(k.entry),this.head_.previous.next=k.entry,this.head_.previous=k.entry,this.size++);return this};f.prototype.delete=function(a){a=d(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};f.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=l();this.size=0};f.prototype.has=function(a){return!!d(this,a).entry};
f.prototype.get=function(a){return(a=d(this,a).entry)&&a.value};f.prototype.entries=function(){return h(this,function(a){return[a.key,a.value]})};f.prototype.keys=function(){return h(this,function(a){return a.key})};f.prototype.values=function(){return h(this,function(a){return a.value})};f.prototype.forEach=function(a,b){for(var c=this.entries(),k;!(k=c.next()).done;)k=k.value,a.call(b,k[1],k[0],this)};f.prototype[Symbol.iterator]=f.prototype.entries;var d=function(a,c){var k=c&&typeof c;"object"==
k||"function"==k?b.has(c)?k=b.get(c):(k=""+ ++m,b.set(c,k)):k="p_"+c;var d=a.data_[k];if(d&&$jscomp.owns(a.data_,k))for(a=0;a<d.length;a++){var f=d[a];if(c!==c&&f.key!==f.key||c===f.key)return{id:k,list:d,index:a,entry:f}}return{id:k,list:d,index:-1,entry:void 0}},h=function(a,b){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},l=function(){var a={};return a.previous=
a.next=a.head=a},m=0;return f},"es6","es3");$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(c){function a(){this.batch_=null}function b(a){return a instanceof d?a:new d(function(b,c){b(a)})}if(c&&!$jscomp.FORCE_POLYFILL_PROMISE)return c;a.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};a.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var f=$jscomp.global.setTimeout;a.prototype.asyncExecuteFunction=function(a){f(a,
0)};a.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(q){this.asyncThrow_(q)}}}this.batch_=null};a.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var d=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(k){b.reject(k)}};d.prototype.createResolveAndReject_=
function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};d.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof d)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};d.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(k){this.reject_(k);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};d.prototype.reject_=function(a){this.settle_(2,a)};d.prototype.fulfill_=function(a){this.settle_(1,a)};d.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)h.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var h=new a;d.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};d.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(q){c.reject(q)}};d.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{f(a(b))}catch(r){h(r)}}:
b}var f,h,g=new d(function(a,b){f=a;h=b});this.callWhenSettled_(c(a,f),c(b,h));return g};d.prototype.catch=function(a){return this.then(void 0,a)};d.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?h.asyncExecute(c):this.onSettledCallbacks_.push(c)};d.resolve=b;d.reject=function(a){return new d(function(b,c){c(a)})};d.race=function(a){return new d(function(c,
d){for(var k=$jscomp.makeIterator(a),f=k.next();!f.done;f=k.next())b(f.value).callWhenSettled_(c,d)})};d.all=function(a){var c=$jscomp.makeIterator(a),f=c.next();return f.done?b([]):new d(function(a,d){function k(b){return function(c){h[b]=c;e--;0==e&&a(h)}}var h=[],e=0;do h.push(void 0),e++,b(f.value).callWhenSettled_(k(h.length-1),d),f=c.next();while(!f.done)})};return d},"es6","es3");
$jscomp.polyfill("Array.from",function(c){return c?c:function(a,b,c){$jscomp.initSymbolIterator();b=null!=b?b:function(a){return a};var d=[],f=a[Symbol.iterator];if("function"==typeof f)for(a=f.call(a);!(f=a.next()).done;)d.push(b.call(c,f.value));else{f=a.length;for(var l=0;l<f;l++)d.push(b.call(c,a[l]))}return d}},"es6","es3");$jscomp.polyfill("Object.values",function(c){return c?c:function(a){var b=[],c;for(c in a)$jscomp.owns(a,c)&&b.push(a[c]);return b}},"es8","es3");
$jscomp.assign="function"==typeof Object.assign?Object.assign:function(c,a){for(var b=1;b<arguments.length;b++){var f=arguments[b];if(f)for(var d in f)$jscomp.owns(f,d)&&(c[d]=f[d])}return c};$jscomp.polyfill("Object.assign",function(c){return c||$jscomp.assign},"es6","es3");
$jscomp.polyfill("Set",function(c){function a(){if($jscomp.ASSUME_NO_NATIVE_SET||!c||"function"!=typeof c||!c.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),b=new c($jscomp.makeIterator([a]));if(!b.has(a)||1!=b.size||b.add(a)!=b||1!=b.size||b.add({x:4})!=b||2!=b.size)return!1;var h=b.entries(),l=h.next();if(l.done||l.value[0]!=a||l.value[1]!=a)return!1;l=h.next();return l.done||l.value[0]==a||4!=l.value[0].x||l.value[1]!=l.value[0]?!1:h.next().done}catch(m){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(c&&$jscomp.ES6_CONFORMANCE)return c}else if(a())return c;$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.map_.size};b.prototype.add=function(a){this.map_.set(a,a);this.size=this.map_.size;return this};b.prototype.delete=function(a){a=this.map_.delete(a);this.size=this.map_.size;return a};b.prototype.clear=function(){this.map_.clear();
this.size=0};b.prototype.has=function(a){return this.map_.has(a)};b.prototype.entries=function(){return this.map_.entries()};b.prototype.values=function(){return this.map_.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(a,b){var c=this;this.map_.forEach(function(d){return a.call(b,d,d,c)})};return b},"es6","es3");
(function(c){c=c.SymWax=c.SymWax||{};var a={requestType:{},header:{},contentType:{},IN_PAGE_POPUP:"symc-in-page-popup",DEFAULT_XHR_TIMEOUT:6E4};a.requestType.GET_METHOD="GET";a.contentType.JSON="application/json";a.header.CONTENT_TYPE="Content-Type";a.DEFAULT_PARSINGPREFERENCES="DefaultParsingPreferences";a.DOMAIN_RULES="DomainRules";a.URL_RULES="UrlRules";a.COUNTRIES="Countries";a.COUNTRY_DATA="CountryData";a.DATA="data";a.DATA_TYPE="datatype";a.COUNTRY_ATTRIBUTE="CountryAttribute";a.DOMAIN="Domain";
a.LANGUAGES="Languages";a.DOMAIN_MATCH="/";a.FIELD_TYPE="fieldType";a.RULES="rules";a.FORM_SUBMIT_TIMEOUT=100;a.EVENT_OBJECT_SUBMIT_TIMEOUT=100;a.PATTERN="pattern";a.REGEX="regEx";a.MAX_STRING_LENGTH_FOR_REGEX=200;a.NORMALIZE_URL="normalizeUrl";a.ORIGINAL_URL="org";a.NORMALIZED_URL="nor";a.PROXIMITY_THRESHOLD_X=70;a.PROXIMITY_THRESHOLD_Y=50;a.rules={PRE_PARSE:"preparse",POST_PARSE:"postparse",SCRIPTS:"scripts",ON_FILL:"onfill",FETCH_CREDENTIALS:"fetchcredentials",ON_FIELD_FOUND:"onfieldfound",AFTER_FILL:"afterfill",
BEFORE_FILL:"beforefill",OPERATION:"Operation",PROPERTY:"Property",DOM_METHOD:"DomMethod",EXECUTION_CONTEXT:"ExecutionContext",DELAY:"Delay",EVENT_NAME:"EventName",SET_TIMEOUT:"setTimeout",SET_INTERVAL:"setInterval",RETRY_ITERATION:"RetryIteration",operation:{CALL_JAVA_SCRIPT:"calljavascript",FILL_EX:"fillex",FIELD_MAPPING:"FieldMapping",GROUP_MAPPING:"GroupMapping",UPDATE_ATTRIBUTE:"updateAttribute",FETCH_DATA:"fetchData",SPLIT_FILL:"splitFill",CLICK:"Click",CUSTOM_FILL:"CustomFill",ADD_EVENT_LISTENER:"addEventListener"},
property:{NAME:"name",ATTRIBUTES:"attributes",FIELD_TYPE:"FieldType",INPUT_TYPE:"InputType",LOGIN_TYPE:"LoginType",GROUP_TYPE:"GroupType"},domMethod:{GET_ELEMENT_BY_ID:"getElementById",GET_ELEMENT_BY_NAME:"getElementsByName",QUERY_SELECTOR_ALL:"querySelectorAll",QUERY_SELECTOR:"querySelector"}};a.PREFERENCES="preferences";a.URL_BASED_DATA="urlBasedData";a.GLOBAL_DATA="globalData";a.messages={GET_URL_DATA:"F1F837B8-DC04-478A-C9EB-45F87DD3B88F",TRIGGER_AJAX_PARSE_RETRY:"BEE46703-475E-411B-C6CD-6331AC68CB18",
TRIGGER_AJAX_PARSE_RETRY_RESPONSE:"30220307-AB5C-45DA-F586-37894089452E",TRIGGER_FORCED_WAX_ANALYSIS:"577408EC-2807-49D8-B479-E91120B89183",CHECK_ANALYSIS_REQUIRED:"11A574D4-6B97-45D1-BFFE-F23A3036C829",TOP_FRAME_UNLOAD_EVENT:"282955FF-C442-4AD4-A28F-1FA4F6183400",SEND_WAX_TELEMETRY_TO_BG:"319e4246-a421-4a7b-bfa7-faaa7681e45b",SEND_WAX_TELEMETRY_TO_BFW:"0e72ba18-d35c-43e5-a025-91afb1132866"};a.NO_THRESHOLD_CHECK_VALUE=-1;a.htmlTagName={A:"A",BODY:"BODY",BUTTON:"BUTTON",DIV:"DIV",FIELDSET:"FIELDSET",
HEAD:"HEAD",IFRAME:"IFRAME",IMG:"IMG",FORM:"FORM",INPUT:"INPUT",LABEL:"LABEL",META:"META",NOSCRIPT:"NOSCRIPT",OPTION:"OPTION",P:"P",SCRIPT:"SCRIPT",SELECT:"SELECT",SPAN:"SPAN",TABLE:"TABLE",TD:"TD",TEXTAREA:"TEXTAREA",TH:"TH",THEAD:"THEAD",TITLE:"TITLE",TR:"TR",B:"B",I:"I",U:"U",LI:"LI",H1:"H1",H2:"H2",H3:"H3",H4:"H4",H5:"H5",H6:"H6",FONT:"FONT",STRONG:"STRONG",EM:"EM"};a.htmlElementAttributes={ACTION:"action",ALT:"alt",CLASS:"class",CHECKED:"checked",FOR:"for",FORM:"form",FORMACTION:"formaction",
ID:"id",NAME:"name",PLACEHOLDER:"placeholder",READONLY:"readonly",SRC:"src",TYPE:"type",TITLE:"title",VALUE:"value"};a.inputType={UNKNOWN:"Unknown",TEXT:"Text",TEXTAREA:"Textarea",PASSWORD:"Password",SUBMIT:"Submit",IMAGE:"Image",BUTTON:"Button",CHECKBOX:"Checkbox",RADIO:"Radio",RESET:"Reset",FILE:"File",HIDDEN:"Hidden",SELECT:"Select",EVENT_OBJECT:"EventObject",TELEPHONE:"tel",NUMBER:"number",CUSTOM_FILL:"CustomFill"};a.patternTokens={DAY:"dd",MONTH:"mmm",YEAR:"yyyy",PREFIX:"p",SUFFIX:"s",FIRST_NAME:"fn",
MIDDLE_NAME:"mn",LAST_NAME:"ln",CARD_NUMBER:"cc",UNKNOWN:"x",IGNORE:"xx"};a.fieldType={ALL:"All",UNKNOWN:"Unknown",LOGIN_NAME:"LoginName",PASSWORD:"Password",PASSWORD_PLACEHOLDER:"PasswordPlaceHolder",VERIFY_PASSWORD:"VerifyPassword",PASSWORD_HINT:"PasswordHint",LOGIN_BUTTON:"LoginButton",SIGNUP_BUTTON:"SignUpButton",CONTINUE_BUTTON:"ContinueButton",SIGNON_DESTINATION:"SignonDestination",EMAIL:"Email",VERIFY_EMAIL:"VerifyEmail",ALTERNATE_EMAIL:"AlternateEmail",FULL_NAME:"FullName",FIRST_NAME:"FirstName",
LAST_NAME:"LastName",MIDDLE_NAME:"MiddleName",PREFIX:"Prefix",SUFFIX:"Suffix",FULL_NAME_PHONETIC:"FullNamePhonetic",FIRST_NAME_PHONETIC:"FirstNamePhonetic",LAST_NAME_PHONETIC:"LastNamePhonetic",MIDDLE_NAME_PHONETIC:"MiddleNamePhonetic",FULL_NAME_ROMAN:"FullNameRoman",FIRST_NAME_ROMAN:"FirstNameRoman",LAST_NAME_ROMAN:"LastNameRoman",MIDDLE_NAME_ROMAN:"MiddleNameRoman",SSN:"SSN",ADDRESS:"Address",ADDRESS_LINE2:"AddressLine2",ADDRESS_LINE3:"AddressLine3",ADDRESS_PHONETIC:"AddressPhonetic",ADDRESS_LINE2_PHONETIC:"AddressLine2Phonetic",
ADDRESS_LINE3_PHONETIC:"AddressLine3Phonetic",CITY:"City",CITY_PHONETIC:"CityPhonetic",ZIP_CODE:"ZipCode",STATE:"State",REGION:"Region",HOUSE_NUMBER:"HouseNumber",HOUSE_NAME:"HouseName",VILLAGE:"Village",SUB_AREA:"SubArea",BLOCK_NUMBER:"BlockNumber",DISTRICT:"District",APARTMENT_NUMBER:"ApartmentNumber",APARTMENT_FLOOR:"ApartmentFloor",SUITE_NUMBER:"SuiteNumber",BIRTH_DATE:"BirthDate",BIRTH_DAY:"BirthDay",BIRTH_MONTH:"BirthMonth",BIRTH_YEAR:"BirthYear",DATE:"Date",DAY:"Day",MONTH:"Month",YEAR:"Year",
ACCOUNT_NUMBER:"AccountNumber",PIN:"Pin",ROUTING_NUMBER:"RoutingNumber",PHONE_NUMBER_COUNTRY_CODE:"PhoneNumberCountryCode",PHONE_NUMBER_AREA_CODE:"PhoneNumberAreaCode",PHONE_NUMBER_EXTENSION:"PhoneNumberExtension",PHONE_NUMBER:"PhoneNumber",PHONE_NUMBER_WORK:"PhoneNumberWork",PHONE_NUMBER_WORK_FAX:"PhoneNumberWorkFax",PHONE_NUMBER_HOME:"PhoneNumberHome",PHONE_NUMBER_FAX:"PhoneNumberFax",PHONE_NUMBER_CELL:"PhoneNumberCell",SECURITY_QUESTION:"SecurityQuestion",ANSWER:"Answer",GENDER:"Gender",CREDIT_CARD_HOLDER_NAME:"CreditCardHolderName",
CREDIT_CARD_HOLDER_FIRST_NAME:"CreditCardHolderFirstName",CREDIT_CARD_HOLDER_LAST_NAME:"CreditCardHolderLastName",CREDIT_CARD_TYPE:"CreditCardType",CREDIT_CARD_NUMBER:"CreditCardNumber",CREDIT_CARD_EXPIRATION_DATE:"CreditCardExpirationDate",CREDIT_CARD_EXPIRATION_MONTH:"CreditCardExpirationMonth",CREDIT_CARD_EXPIRATION_YEAR:"CreditCardExpirationYear",CREDIT_CARD_SECURITY_CODE:"CreditCardSecurityCode",CREDIT_CARD_START_DATE:"CreditCardStartDate",CREDIT_CARD_START_MONTH:"CreditCardStartMonth",CREDIT_CARD_START_YEAR:"CreditCardStartYear",
CREDIT_CARD_ISSUE_NUMBER:"CreditCardIssueNumber",ADD_CARD_DETAILS:"AddCard",COMPANY:"Company",DEPARTMENT:"Department",WORK_ID:"WorkId",WORK_JOB_TITLE:"WorkJobTitle",WORK_EMAIL:"WorkEmail",WORK_ADDRESS:"WorkAddress",WORK_CITY:"WorkCity",WORK_ZIP_CODE:"WorkZipCode",WORK_STATE:"WorkState",WORK_REGION:"WorkRegion",WORK_WEBSITE:"WorkWebSite",SEARCH:"Search",LANGUAGE:"Language",OPEN_ID:"OpenID",VERIFICATION_CODE:"VerificationCode",WEBSITE:"WebSite",MOTHERS_MAIDEN_NAME:"MothersMaidenName",TIMEZONE:"TimeZone",
DOMAIN:"Domain",AJAX_ACTION:"AjaxAction",BUTTON_ACTION:"ButtonAction",SKIP_FIELD:"SkipField",CHANGE_PASSWORD_BUTTON:"ChangePasswordButton",SUBSCRIBE:"Subscribe",PASSPORT_NUMBER:"PassportNumber",DRIVER_LICENSE:"DriversLicense",SEARCH_ANNOTATION:"SearchAnnotation",APPLY:"Apply",UPDATE:"Update",COMMENT:"Comment",BANK_NAME:"BankName",BANK_ACCOUNT_HOLDER_NAME:"BankAccountHolderName",MAILING_ADDRESS:"MailingAddress",NEW_PASSWORD:"NewPassword",IGNORE_FIELD:"IgnoreField",GENDER_MALE:"GenderMale",GENDER_FEMALE:"GenderFemale",
SEARCH_BUTTON:"SearchButton",MUTLI_SPAN_USERNAME:"MultiSpanUsername",SUBSCRIBE_BUTTON:"SubscribeButton",APPLY_BUTTON:"ApplyButton",UPDATE_BUTTON:"UpdateButton"};a.matchProperties={INVALID:"Invalid",NAME:"Name",VALUE:"Value",CLASS:"Class",ATTACHED_TEXT:"AttachedText",ALTERNATIVE_TEXT:"Alt",ID:"ID",IMAGE_SRC:"Src",TITLE:"Title",INNER_TEXT:"InnerText",HREF:"HREF",CONTENT:"Content",FIRST_LIST_ITEM:"FirstListItem",PLACE_HOLDER:"Placeholder",TYPE:"Type"};a.eventType={ON_CLICK:"onclick",ON_SUBMIT:"onsubmit",
ON_MOUSE_DOWN:"onmousedown",ON_MOUSE_UP:"onmouseup",FORM_ACTION:"formaction",COMMAND:"command",HREF:"href",ROLE:"role",CHANGE:"change",INPUT:"input",HTML_EVENTS:"HTMLEvents",EVENTS:"Events",CLICK:"click",KEYDOWN:"keydown",KEYUP:"keyup",SUBMIT:"submit",MOUSE_OVER:"mouseover",ONFOCUS:"focus"};a.groupType={UNKNOWN:"Unknown",LOGIN:"Login",MULTI_PAGE_LOGIN:"MultiPageLogin",PARTIAL_LOGIN:"PartialLogin",PARTIAL_CARDS_PAGE:"PartialCardsPage",CARDS_PAGE:"CardsPage",PERSONAL_INFO_PAGE:"PersonalInfoPage",CHANGE_PASSWORD_PAGE:"ChangePasswordPage",
REGISTRATION_PAGE:"RegistrationPage",PARTIAL_REGISTRATION_PAGE:"PartialRegistrationPage",PARTIAL_CHANGE_PASSWORD_PAGE:"PartialChangePasswordPage",LIMITED_CHANGE_PASSWORD_PAGE:"LimitedChangePasswordPage"};a.anyFieldTypes={ANY_LOGIN_FIELD:"AnyLoginField",ANY_LOGIN_FIELD_EX:"AnyLoginFieldEx",ANY_LOGIN_BUTTON:"AnyLoginButton",ANY_CHANGE_PASSWORD_BUTTON:"AnyChangePasswordButton",ANY_LOGIN_PASSWORD_FIELD:"AnyLoginPasswordField",ANY_CHANGE_PASSWORD_FIELD:"AnyChangePasswordField"};a.loginType={USERNAME:"Username",
PASSWORD:"Password",LOGIN_BUTTON:"LoginButton"};a.anyInputTypes={ANY_INPUT_BUTTON_TYPE:"AnyInputButtonType"};a.groupCategorization={MAPPING_FIELDS:"MappingFields",INPUT_FIELDS:"InputFields",GROUP_TYPE:"GroupType",FIELD_TYPE:"FieldType",INPUT_TYPE:"InputType",LOGIN_TYPE:"LoginType",PARTIAL:"Partial",LOGIN_CATEGORIZATIONS:"LoginCategorizations",PAGE_CATEGORIZATIONS:"PageCategorizations"};a.telemetry={CATEGORY:"wax",VALIDATION_TIMEOUT:300,ANALYSIS_THRESHOLD:2500,TRACKING_ID:"UA-80690213-3"};a.telemetry.type=
{FILL_FAILURE:"fillfailure",FIELD_CHANGED:"fieldchanged",FILL_SUCCESS:"fillsuccess",DETECTION_FAILURE:"detectionfailure"};a.telemetry.parameters={TAG_NAME:"cd1",INPUT_TYPE:"cd2",ID:"cd3",NAME:"cd4",PLACE_HOLDER:"cd5",CLASS_NAME:"cd6",FIELD_INNER_TEXT:"cd7",FORM_ID:"cd8",FORM_NAME:"cd9",URL:"cd10"};a.parsePreferences={PARSE_CRITERIAS:"ParseCriterias",REGEX_ENABLED_FIELDS:"RegexEnabledFields"};a.parseCriterias={EVENT_OBECTS:"EventObjects",IGNORE_FIELD_SETS:"IgnoreFieldSets",VERIFY_ATTRIBUTE_BY_ATTACHED_TEXT:"VerifyAttributeByAttachedText",
ENABLE_SORTING:"EnableSorting",CHECK_IF_OUT_OF_BOUNDS:"CheckIfOutOfBounds",USE_PATTERN_MATCHING:"UsePatternMatching",IGNORE_HIDDEN_INPUTS:"IgnoreHiddenInputs",ALLOW_PAGE_PORT_VIEW:"AllowPagePortView",ENABLE_AJAX_SUPPORT:"EnableAjaxSupport",USE_GLOBAL_LOOKUP_CACHE:"UseGlobalLookupCache",LOGIN_EVENT_REPLAY:"LoginEventReplay",USE_GROUP_PATTERN_MATCHING:"UseGroupPatternMatching",LOGIN_THREAD_CALLBACK_REPLAY:"LoginThreadCallbackReplay",ATTACHED_TEXT_LENGTH:"AttachedTextLength",ATTACHED_TEXT_PIXEL_SIZE:"AttachedTextPixelSize",
USE_REG_EX_ON_EVENT_OBJECTS:"UseRegExOnEventObjects",USE_REG_EX_ON_IMAGES:"UseRegExOnImages",IGNORE_IMAGES:"IgnoreImages",DETERMINISTIC_EVENT_REPLAY:"DeterministicEventReplay",DONT_VALIDATE_FIELD_TYPE:"DontValidateFieldType",DONT_CATEGORIZE_AS_MULTIPLE_PAGE_LOGIN:"DontCategorizeAsMultiPageLogin",VERIFY_DOCUMENT_WIDTH_AND_HEIGHT:"VerifyDocumentWidthAndHeight",INPUTS_ONLY:"InputsOnly",IGNORE_FORMS:"IgnoreForms",DONT_PERFORM_GROUP_CATEGORIZE:"DontPerformGroupCategorize",DONT_PERFORM_FIELD_MAPPING:"DontPerformFieldMapping",
CHROME_DONT_USE_JAVA_SCRIPT:"ChromeDontUseJavaScript",DONT_PARSE:"DontParse",CARDS_EVENT_REPLAY:"CardsEventReplay",IGNORE_FRAMEWORK_SUBMIT:"IgnoreFrameworkSubmit",SKIP_DOCS_WITH_FEW_ELEMENTS:"SkipDocsWithFewElements",DONT_USE_CUSTOM_SUBMIT_HOOK:"DontUseCustomSubmitHook"};a.keyCode={ENTER:13};a.performanceReporter={COMPONENT:{WAX:"wax"},TYPE:{DO_PARSE:"doParse",INIT:"init",FIELD_MAPPING_PROCESS_PAGE:"fieldMappingProcessPage",FIELD_GROUP_MAPPING_PROCESS_PAGE:"fieldGroupMappingProcessPage",GROUP_CATEGORIZATION_PROCESS_PAGE:"groupCategorizationProcessPage",
PROCESS_GROUP_CATEGORIZATION_RESULTS:"processGroupCategorizationResults",INIT_WITH_THRESHOLD:"waxInitWithThreshold"}};a.formDataPublicKey="-----BEGIN PUBLIC KEY----- MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA55eUNAVhz6OhVq4mWyX3 PUtVSidog8NA0k+kzYzHkc1V8wEAqIjz8ELFmeW1UcczR8gQgrCP66XuSl3D/LV6 qzY6ATCbLrvc8VPR6MG5gKEw8D6DFp2lCAeeMZncCu9jlYohjTIH6pJtN7yfLibJ 5aKlcHpE+IG5ktl9jDKEjICdA7WpcN0HXIB/7j/mSxy32GJ7tVWdGylLk6Wlf+qz YUZ3DrwxkJzMVxOm6EmROD0nVhv6gN728o0Mtl1scPgqKP4LG039eHyNV9fvDARU gWpEkzb5V+Fh/Mspz9NOQaIBEBTyxZ59wsCotRx2zNSatDlxgVOZsXvVFVC2IGEm maTyfpmwxatIBlFGQOewgX30NjVCkXSP3iQdIa7QxaAz0drvEOhNxIHCYz4SdJtt ajGipjsYKg9Sh2bDOfmWCttP2AQ7l32NtJdi9NG1dEbq2D7z4u1SH51Xy2Vm2qgb QMUXdGJGivtul32y1oNJuDMEVfJ2+St8YDEXFbFP36wxrsmXYFm0XUwk1ulREBjI HUoPEAnVONHDxFtYvo2PFDYkxctnksr+SyatlIZcVx03lG68gUOea9s6d5CDN+T/ hqMetpYpdDOwAIk5g417JMRluod7CgIK+CzZ3kdSAPjEKWH4ImP+xbpKBF2JV6Jt 6vopZeo/hiZEbsXLtDLweIECAwEAAQ== -----END PUBLIC KEY-----";
var b={CDN_FORMDATA_BASE_URL:"https://static.nortoncdn.com/idsafe/waxFormdata/v1/"};b.CDN_L10N_JSON_URL=b.CDN_FORMDATA_BASE_URL+"l10n/";b.L10N_US_CODE=11;b.MASKED_PASSWORD_CHAR=8226;a.cloudFormData=b;a.textPosition={Invalid:0,Center:1,Left:2,FarLeft:4,Top:8,Bottom:32,Right:64,FarRight:128,CenterTop:9,LeftTop:10,FarLeftTop:12,RightTop:72,FarRightTop:136,LeftCenter:3,FarLeftCenter:5,RightCenter:65,FarRightCenter:129,CenterBottom:33,LeftBottom:34,FarLeftBottom:36,RightBottom:96,FarRightBottom:160};a.elementType=
{Unknown:0,Label:1,TableCell:2,Header:3,Table:4,TableBody:5,TableRow:6,Input:7,TextArea:8,Button:9,Image:10,Select:11,Link:12,Container:13,SelectOption:14,Generic:15,Form:16,Comments:17,FieldSet:18};a.languageQueryParameterKeys=["lang",".lang","hl"];b={};a.fieldTypeToPIIIdentifiers=(b[a.fieldType.SSN]=27,b[a.fieldType.CREDIT_CARD_HOLDER_NAME]=71,b[a.fieldType.CREDIT_CARD_HOLDER_FIRST_NAME]=72,b[a.fieldType.CREDIT_CARD_HOLDER_LAST_NAME]=73,b[a.fieldType.CREDIT_CARD_TYPE]=74,b[a.fieldType.CREDIT_CARD_NUMBER]=
75,b[a.fieldType.CREDIT_CARD_EXPIRATION_DATE]=76,b[a.fieldType.CREDIT_CARD_EXPIRATION_MONTH]=77,b[a.fieldType.CREDIT_CARD_EXPIRATION_YEAR]=78,b[a.fieldType.CREDIT_CARD_SECURITY_CODE]=79,b[a.fieldType.CREDIT_CARD_START_DATE]=80,b[a.fieldType.CREDIT_CARD_START_MONTH]=81,b[a.fieldType.CREDIT_CARD_START_YEAR]=82,b[a.fieldType.CREDIT_CARD_ISSUE_NUMBER]=83,b[a.fieldType.LOGIN_NAME]=1,b[a.fieldType.PASSWORD]=2,b[a.fieldType.PASSWORD_PLACEHOLDER]=3,b[a.fieldType.VERIFY_PASSWORD]=4,b[a.fieldType.PASSWORD_HINT]=
5,b[a.fieldType.LOGIN_BUTTON]=6,b[a.fieldType.SIGNUP_BUTTON]=7,b[a.fieldType.CONTINUE_BUTTON]=8,b[a.fieldType.SIGNON_DESTINATION]=9,b[a.fieldType.EMAIL]=10,b[a.fieldType.VERIFY_EMAIL]=11,b[a.fieldType.ALTERNATE_EMAIL]=12,b[a.fieldType.FULL_NAME]=13,b[a.fieldType.FIRST_NAME]=14,b[a.fieldType.LAST_NAME]=15,b[a.fieldType.MIDDLE_NAME]=16,b[a.fieldType.PREFIX]=17,b[a.fieldType.SUFFIX]=18,b[a.fieldType.FULL_NAME_PHONETIC]=19,b[a.fieldType.FIRST_NAME_PHONETIC]=20,b[a.fieldType.LAST_NAME_PHONETIC]=21,b[a.fieldType.MIDDLE_NAME_PHONETIC]=
22,b[a.fieldType.FULL_NAME_ROMAN]=23,b[a.fieldType.FIRST_NAME_ROMAN]=24,b[a.fieldType.LAST_NAME_ROMAN]=25,b[a.fieldType.MIDDLE_NAME_ROMAN]=26,b[a.fieldType.ADDRESS]=28,b[a.fieldType.ADDRESS_LINE2]=29,b[a.fieldType.ADDRESS_LINE3]=30,b[a.fieldType.ADDRESS_PHONETIC]=31,b[a.fieldType.ADDRESS_LINE2_PHONETIC]=32,b[a.fieldType.ADDRESS_LINE3_PHONETIC]=33,b[a.fieldType.CITY]=34,b[a.fieldType.CITY_PHONETIC]=35,b[a.fieldType.ZIP_CODE]=36,b[a.fieldType.STATE]=37,b[a.fieldType.REGION]=38,b[a.fieldType.HOUSE_NUMBER]=
39,b[a.fieldType.HOUSE_NAME]=40,b[a.fieldType.VILLAGE]=41,b[a.fieldType.SUB_AREA]=42,b[a.fieldType.BLOCK_NUMBER]=43,b[a.fieldType.DISTRICT]=44,b[a.fieldType.APARTMENT_NUMBER]=45,b[a.fieldType.APARTMENT_FLOOR]=46,b[a.fieldType.SUITE_NUMBER]=47,b[a.fieldType.BIRTH_DATE]=48,b[a.fieldType.BIRTH_DAY]=49,b[a.fieldType.BIRTH_MONTH]=50,b[a.fieldType.BIRTH_YEAR]=51,b[a.fieldType.DATE]=52,b[a.fieldType.DAY]=53,b[a.fieldType.MONTH]=54,b[a.fieldType.YEAR]=55,b[a.fieldType.ACCOUNT_NUMBER]=56,b[a.fieldType.PIN]=
57,b[a.fieldType.ROUTING_NUMBER]=58,b[a.fieldType.PHONE_NUMBER_COUNTRY_CODE]=59,b[a.fieldType.PHONE_NUMBER_AREA_CODE]=60,b[a.fieldType.PHONE_NUMBER_EXTENSION]=61,b[a.fieldType.PHONE_NUMBER]=62,b[a.fieldType.PHONE_NUMBER_WORK]=63,b[a.fieldType.PHONE_NUMBER_WORK_FAX]=64,b[a.fieldType.PHONE_NUMBER_HOME]=65,b[a.fieldType.PHONE_NUMBER_FAX]=66,b[a.fieldType.PHONE_NUMBER_CELL]=67,b[a.fieldType.SECURITY_QUESTION]=68,b[a.fieldType.ANSWER]=69,b[a.fieldType.GENDER]=70,b[a.fieldType.COMPANY]=84,b[a.fieldType.DEPARTMENT]=
85,b[a.fieldType.WORK_ID]=86,b[a.fieldType.WORK_JOB_TITLE]=87,b[a.fieldType.WORK_EMAIL]=88,b[a.fieldType.WORK_ADDRESS]=89,b[a.fieldType.WORK_CITY]=90,b[a.fieldType.WORK_ZIP_CODE]=91,b[a.fieldType.WORK_STATE]=92,b[a.fieldType.WORK_REGION]=93,b[a.fieldType.WORK_WEBSITE]=94,b[a.fieldType.SEARCH]=95,b[a.fieldType.LANGUAGE]=96,b[a.fieldType.OPEN_ID]=97,b[a.fieldType.VERIFICATION_CODE]=98,b[a.fieldType.WEBSITE]=99,b[a.fieldType.MOTHERS_MAIDEN_NAME]=100,b[a.fieldType.TIMEZONE]=101,b[a.fieldType.DOMAIN]=
102,b[a.fieldType.AJAX_ACTION]=103,b[a.fieldType.SKIP_FIELD]=104,b[a.fieldType.IGNORE_FIELD]=124,b[a.fieldType.GENDER_MALE]=155,b[a.fieldType.GENDER_FEMALE]=156,b[a.fieldType.SEARCH_BUTTON]=157,b[a.fieldType.MUTLI_SPAN_USERNAME]=158,b);a.fieldFilter={};a.fieldFilter.type={ALL:"ALL",CATEGORIZED_INPUT_FIELDS:"CATEGORIZED_INPUT_FIELDS",CATEGORIZED_INPUT_AND_NONINPUT_FIELDS:"CATEGORIZED_INPUT_AND_NONINPUT_FIELDS"};c.constants=a})(this);
(function(c){c.SymWax.ParsePreference=function(a,b){var c=a.utils.isNil;a=function(a){if(c(a))throw Error("jsonParsePreference object cannot be null");this._languages=a.Languages;this._overwriteRule=a.OverwriteRule;this._matchFullURLPath=a.MatchFullURLPath;this._parseCriterias=a.ParseCriterias;this._parseCriteriasEx=a.ParseCriteriasEx;this._eventTypes=a.EventTypes;this._matchingProperties=a.MatchingProperties;this._initialParseDelay=a.InitialParseDelay;this._parseRetryInfo=a.ParseRetryInfo;this._ajaxParseRetryInfo=
a.AjaxParseRetryInfo;this._signonDestinations=a.SignonDestinations;this._stringPixelSize=a.StringPixelSize;this._regexEnabledFields=a.RegexEnabledFields;this._browsers=a.Browsers;this._groupSeperatorWidth=a.GroupSeperatorWidth;this._mutationObserverTargetElement=a.MutationObserverTarget};a.prototype.isOverwriteRuleAvailable=function(){return this._overwriteRule};a.prototype.isMatchFullURLPathPresent=function(){return this._matchFullURLPath};a.prototype.getMutationObserverTargetElement=function(){return this._mutationObserverTargetElement};
a.prototype.getParseCriterias=function(){return this._parseCriterias};a.prototype.getParseCriteriasEx=function(){return this._parseCriteriasEx};a.prototype.getEventTypes=function(){return this._eventTypes};a.prototype.getLanguages=function(){return this._languages};a.prototype.getMatchingProperties=function(){return this._matchingProperties};a.prototype.getInitialParseDelay=function(){return this._initialParseDelay};a.prototype.getParseRetryInfo=function(){return this._parseRetryInfo};a.prototype.getAjaxParseRetryInfo=
function(){return this._ajaxParseRetryInfo};a.prototype.getSignonDestinations=function(){return this._signonDestinations};a.prototype.getStringPixelSize=function(){return this._stringPixelSize};a.prototype.getBrowsers=function(){return this._browsers};a.prototype.getRegexEnabledFields=function(){return this._regexEnabledFields};a.prototype.getGroupSeperatorWidth=function(){return this._groupSeperatorWidth};a.prototype.serialize=function(){return{OverwriteRule:this.isOverwriteRuleAvailable(),MatchingProperties:this.getMatchingProperties(),
ParseCriterias:this.getParseCriterias(),EventTypes:this.getEventTypes(),SignonDestinations:this.getSignonDestinations(),ParseCriteriasEx:this.getParseCriteriasEx(),InitialParseDelay:this.getInitialParseDelay(),ParseRetryInfo:this.getParseRetryInfo(),Languages:this.getLanguages(),MatchFullURLPath:this.isMatchFullURLPathPresent(),AjaxParseRetryInfo:this.getAjaxParseRetryInfo(),StringPixelSize:this.getStringPixelSize(),Browsers:this.getBrowsers(),RegexEnabledFields:this.getRegexEnabledFields(),GroupSeperatorWidth:this.getGroupSeperatorWidth(),
MutationObserverTarget:this.getMutationObserverTargetElement()}};return a}(c.SymBfw,c.SymWax)})(this);
(function(c){c.SymWax.formDataFactory=function(a,b){var c=a.utils.isNil,d=a.utils.isntNil,h=a.utils.isArray,l={},m=function(){this._parsePreference={};this._rule={};this._global={};this._urlBasedData={};this._l10n={countries:[],attributes:[]}};m.prototype.getParsePreference=function(){return this._parsePreference};m.prototype.getRule=function(){return this._rule};m.prototype.getGlobal=function(){return this._global};m.prototype.getUrlBasedData=function(){return this._urlBasedData};m.prototype.getL10nCountries=
function(){return this._l10n.countries};m.prototype.getL10nAttributes=function(){return this._l10n.attributes};m.prototype.serialize=function(){return{parsePreference:this.getParsePreference().serialize(),rule:this.getRule(),global:this.getGlobal(),urlBasedData:this.getUrlBasedData(),l10n:{countries:this.getL10nCountries(),attributes:this.getL10nAttributes()}}};m.prototype.setParsePreference=function(a){if(c(a))throw Error("parsePreference cannot be nil");this._parsePreference=new b.ParsePreference(a)};
m.prototype.setRule=function(a){if(c(a))throw Error("rule cannot be nil");this._rule=a};m.prototype.setGlobal=function(a){if(c(a))throw Error("global cannot be nil");this._global=a};m.prototype.setUrlBasedData=function(a){if(c(a))throw Error("urlBasedData cannot be nil");this._urlBasedData=a};m.prototype.setL10nCountries=function(a){if(!h(a))throw Error("countries must be an array");this._l10n.countries=a};m.prototype.setL10nAttributes=function(a){if(!h(a))throw Error("attributes must be an array");
this._l10n.attributes=a};m.prototype.appendL10nCountries=function(a){if(!h(a))throw Error("countries must be an array");this._l10n.countries=this._l10n.countries.concat(a)};m.prototype.appendL10nAttributes=function(a){if(!h(a))throw Error("attributes must be an array");this._l10n.attributes=this._l10n.attributes.concat(a)};m.prototype.prependL10nCountries=function(a){if(!h(a))throw Error("countries must be an array");this._l10n.countries=a.concat(this._l10n.countries)};m.prototype.prependL10nAttributes=
function(a){if(!h(a))throw Error("attributes must be an array");this._l10n.attributes=a.concat(this._l10n.attributes)};l.filterRegexInCountryData=function(a,c){var d=b.constants,g=c||[];return 0<g.length?g.includes(d.fieldType.ALL)?a:a.map(function(a){var b=a[d.FIELD_TYPE],c=[];g.forEach(function(a){a=b.indexOf(a);-1<a&&c.push(a)});var f=a[d.REGEX];0<c.length?Object.keys(f).forEach(function(b){c.includes(f[b])||delete a[d.REGEX][b]}):a[d.REGEX]={};return a}):(a.map(function(a){a[d.REGEX]={};return a}),
a)};l.create=function(a){var b=new m;if(d(a)&&(d(a.parsePreference)&&b.setParsePreference(a.parsePreference),d(a.rule)&&b.setRule(a.rule),d(a.global)&&b.setGlobal(a.global),d(a.urlBasedData)&&b.setUrlBasedData(a.urlBasedData),d(a.l10n))){if(h(a.l10n.countries)){var c=b.getParsePreference().getRegexEnabledFields()||[],g=a.l10n.countries;0<c.length&&(g=l.filterRegexInCountryData(a.l10n.countries,c));b.setL10nCountries(g)}h(a.l10n.attributes)&&b.setL10nAttributes(a.l10n.attributes)}return b};b.FormData=
m;return l}(c.SymBfw,c.SymWax)})(this);
(function(c){c.SymWax.formDataLoader=function(a,b){var c=a.utils.isNil,d=a.utils.isArray,h=a.utils.isString,l=a.utils.isFunction,m=a.utils.appendToObject,k=a.utils.isntNil,q=a.logger,n=a.extensionAdapter,g=b.constants,v=a.utils.isSuccessCodeLocalFile,e={_parsePreferencesData:null,_domainsData:null,_urlBasedData:null,_globalData:null};e._countryMap=new Map;e._rulesJson=null;e._browserLanguage=null;e._overwriteParsePreference=null;e.initialize=function(b,c){k(b)&&(e._browserLanguage=b);k(c)&&c instanceof
Object&&(e._overwriteParsePreference=c);a.extensionAdapter.addMessageListener(e.handleMessage);return new Promise(function(a,b){var c=[];c.push(e._getRulesJson());c.push(e._getParsePreferencesRulesJSON());c.push(e._getURLBasedDataJSON());c.push(e._getDomainsJSON());c.push(e._getGlobalJSON());Promise.all(c).then(function(){return a()},function(a){return b(Error("Failed to load one or more JSON files"))})})};e._getJSON=function(a,b,c){return new Promise(function(d,g){e._FetchJSON(a).then(function(a){d(a)},
function(p){var f="Failed to load the file from cloud:"+a;k(p)&&(f+=" Error: "+p.message);q.error(f);e._FetchJSON(c).then(function(a){d(a)},function(a){b?d():g(a)})})})};e._FetchJSON=function(b){if(c(b))throw Error("invalid arguments to _FetchJSON");return new Promise(function(c,d){a.utils.safeFetch(b).then(function(a){v(a.status)?a.json().then(function(a){e._validateJSON(a)?c(JSON.stringify(a.payload)):d(Error("could not validate json file "+b))}):d(Error("Fetch "+b+" returned status : "+a.status))},
function(a){d(a)})})};e._mergeParsePreference=function(b){if(c(b))throw Error("DefaultPreference cannot be nil");var f=e._overwriteParsePreference,p={},k=(p[g.parsePreferences.PARSE_CRITERIAS]=function(){var c=g.parseCriterias,d=f[g.parsePreferences.PARSE_CRITERIAS];if(!(d instanceof Object))return{};var e=Array.from(b[g.DEFAULT_PARSINGPREFERENCES][g.parsePreferences.PARSE_CRITERIAS]||[]);Object.keys(d).forEach(function(b){var g=Object.values(c).includes(b),f=a.utils.isBoolean;g&&f(d[b])?d[b]?e.includes(b)||
e.push(b):-1<e.indexOf(b)&&e.splice(e.indexOf(b),1):q.debug(g?"Expected Boolean but got unsupported value type for "+b:"Unknown ParseCriteria: "+b);return{}});var p={};return p[g.parsePreferences.PARSE_CRITERIAS]=e,p},p[g.parsePreferences.REGEX_ENABLED_FIELDS]=function(){var a=Object.values(g.fieldType),b=f[g.parsePreferences.REGEX_ENABLED_FIELDS];if(!d(b))return{};var c=[];b.includes(g.fieldType.ALL)?c.push(g.fieldType.ALL):b.forEach(function(b){Object.values(a).includes(b)&&c.push(b)});b={};return b[g.parsePreferences.REGEX_ENABLED_FIELDS]=
c,b},p);p=Object.keys(f).map(function(a){if(k[a])return k[a]();var c=Object.keys(b[g.DEFAULT_PARSINGPREFERENCES]).includes(a);q.debug(c?a+" can't be overwritten":"Unknown ParsePreference: "+a)}).reduce(function(a,b){return Object.assign({},a,b)},b[g.DEFAULT_PARSINGPREFERENCES]);return Object.assign({},b,{DefaultParsingPreferences:p})};e._validateJSON=function(a){return c(a.payload)||c(a.JWT)?!1:e._verifyJson(a.payload,a.JWT)?!0:!1};e._verifyJson=function(a,b){try{var c=forge.md.sha256.create();c.update(JSON.stringify(a));
var d=c.digest().toHex(),e=KEYUTIL.getKey(g.formDataPublicKey);if(!0===KJUR.jws.JWS.verify(b,e,["RS256"])){var f=b64utoutf8(b.split(".")[1]);if(KJUR.jws.JWS.readSafeJSONString(f).hash===d)return!0}return!1}catch(w){return q.error(w),!1}};e._getParsePreferencesRulesJSON=function(){return new Promise(function(a,b){if(k(e._parsePreferencesData))return a();e._getJSON(g.cloudFormData.CDN_FORMDATA_BASE_URL+"parsepreferences.json",!1,n.getExtensionURL("content/formdata/parsepreferences.json")).then(function(d){if(c(d))return q.error("could not load parsepreferences.json"),
b(Error("could not parse preference "));d=JSON.parse(d);k(e._overwriteParsePreference)?e._parsePreferencesData=e._mergeParsePreference(d):e._parsePreferencesData=d;return a(e._parsePreferencesData)},function(a){b(a)})})};e._getParsePreferencesRulesForURL=function(b){if(!h(b))throw Error("invalid arguments to _getParsePreferencesRulesForURL");return new Promise(function(d,f){e._getParsePreferencesRulesJSON().then(function(){if(c(e._parsePreferencesData))return f(Error("could not parse preference "));
var p;e._parsePreferencesData.hasOwnProperty(g.DEFAULT_PARSINGPREFERENCES)&&(p=JSON.parse(JSON.stringify(e._parsePreferencesData[g.DEFAULT_PARSINGPREFERENCES])));var h=a.utils.getDomain(b);k(h)&&e._parsePreferencesData.hasOwnProperty(g.DOMAIN_RULES)&&e._parsePreferencesData[g.DOMAIN_RULES].hasOwnProperty(h)&&m(p,e._parsePreferencesData[g.DOMAIN_RULES][h]);h=a.utils.urlWithoutQueryParameters(b,!1);k(h)&&e._parsePreferencesData.hasOwnProperty(g.URL_RULES)&&e._parsePreferencesData[g.URL_RULES].hasOwnProperty(h)&&
m(p,e._parsePreferencesData[g.URL_RULES][h]);return d(p)},function(a){return f(Error("could not parse preference "+a))})})};e._getRules=function(a){if(!h(a))throw Error("Invalid arguments passed to _getRules");return new Promise(function(b,d){e._getRulesJson().then(function(){if(c(e._rulesJson))return q.error("unable to load rules.json file"),d(Error("Failed to parse rules json"));var g=e._processRulesJson(a);if(c(g))return d(Error("Failed to parse rules json"));b(g)},function(a){d(Error("Failed to parse rules json"))})})};
e._getRulesJson=function(){return new Promise(function(a,b){if(k(e._rulesJson))return a(e._rulesJson);e._getJSON(g.cloudFormData.CDN_FORMDATA_BASE_URL+"rules.json",!1,n.getExtensionURL("content/formdata/rules.json")).then(function(d){if(c(d))return b(Error("Failed to parse rules json"));e._rulesJson=JSON.parse(d);a()},function(a){b(a)})})};e._processRulesJson=function(b){if(!h(b))q.error("Invalid parameters passed to _processRulesJson");else if(!c(e._rulesJson)){var d={},f=a.utils.baseURL(b);if(!c(f)){b=
a.utils.pathName(b);if(e._rulesJson.hasOwnProperty(f)){if(e._rulesJson[f].hasOwnProperty(g.NORMALIZE_URL)){var k=e._rulesJson[f][g.NORMALIZE_URL];if(k){k=$jscomp.makeIterator(k);for(var p=k.next();!p.done;p=k.next()){p=p.value;var l=p[g.ORIGINAL_URL].replace(/\//g,"\\/");l=new RegExp(l);if(-1!==b.search(l)){b=b.replace(l,p[g.NORMALIZED_URL]);break}}}}e._rulesJson[f].hasOwnProperty(b)&&m(d,e._rulesJson[f][b][g.RULES])}return d}}};e._getCountryJSONSForGivenCodes=function(a,b,f){if(!d(a)||!d(b)||!h(f))throw Error("invalid arguments to _getCountryJSONSForGivenCodes");
return new Promise(function(d,h){for(var p=[],l=[],m=[],r={},t=0;t<a.length;r={l10FileName:r.l10FileName},t++){r.l10FileName=g.cloudFormData.CDN_L10N_JSON_URL+b[a[t]];var u="/content/formdata/l10n/"+b[a[t]];l.push(b[a[t]]);if(f===g.COUNTRY_DATA)r.l10FileName+=".json",u+=".json";else if(f===g.COUNTRY_ATTRIBUTE)r.l10FileName+=".att.json",u+=".att.json";else return h("Invalid type");var v=e._countryMap.get(r.l10FileName);c(v)?(u=e._getJSON(r.l10FileName,!0,n.getExtensionURL(u)),u.then(function(a){return function(b){k(b)&&
(e._countryMap.set(a.l10FileName,JSON.parse(b)),p.push(JSON.parse(b)))}}(r),function(a){h(a)}),m.push(u)):p.push(v)}0<l.length&&q.debug("languages loaded: "+l.join(",")+".");Promise.all(m).then(function(){return d(p)}).catch(function(){return h(Error("Could not load all country json for given URL"))})})};e._getDomainsJSON=function(){return new Promise(function(a,b){if(k(e._domainsData))return a();e._getJSON(g.cloudFormData.CDN_FORMDATA_BASE_URL+"domains.json",!1,n.getExtensionURL("content/formdata/domains.json")).then(function(d){if(c(d))return q.error("could not load domains.json"),
b(Error("could not domains"));e._domainsData=JSON.parse(d);return a()},function(a){b(a)})})};e._getGlobalJSON=function(){return new Promise(function(a,b){if(k(e._globalData))return a(e._globalData);e._getJSON(g.cloudFormData.CDN_FORMDATA_BASE_URL+"global.json",!1,n.getExtensionURL("content/formdata/global.json")).then(function(d){if(c(d))return q.error("could not load global.json"),b(Error("could not get global data"));e._globalData=JSON.parse(d);return a(e._globalData)},function(a){b(a)})})};e._getCountryData=
function(b,f,l){if(!h(b))throw Error("invalid arguments to _getCountryData");if(!(f instanceof Promise))throw Error("Type Error: preferencePromise has to be of type Promise");if(c(l)||!d(l))throw Error("Type Error: languagesFromHTML has to be of type Array<Languages>");return new Promise(function(c,d){var h=e._getDomainsJSON();Promise.all([f,h]).then(function(f){var h=[],p=[],m=a.utils.getUrlTLD(b),r=e._domainsData[g.COUNTRIES],n=e._domainsData[g.DOMAIN],q=n[m]||[];m=f[0];f=[];var t=function(a){if(k(a)&&
0<a.length){var b=[];a.forEach(function(a){n[a]&&b.push.apply(b,$jscomp.arrayFromIterable(n[a]))});q=Array.from(new Set(q.concat(b)))}};k(m)&&k(m[g.LANGUAGES])&&t(m[g.LANGUAGES]);t(l);-1===q.indexOf(g.cloudFormData.L10N_US_CODE)&&q.push(g.cloudFormData.L10N_US_CODE);k(q)&&0<q.length&&(m=e._getCountryJSONSForGivenCodes(q,r,g.COUNTRY_DATA),m.then(function(a){0<a.length&&(h=h.concat(a))},function(a){return d(a)}),f.push(m),m=e._getCountryJSONSForGivenCodes(q,r,g.COUNTRY_ATTRIBUTE),m.then(function(a){0<
a.length&&(p=p.concat(a))},function(a){return d(a)}),f.push(m));k(e._browserLanguage)&&k(n[e._browserLanguage])&&(m=e._getCountryJSONSForGivenCodes(n[e._browserLanguage],r,g.COUNTRY_DATA),m.then(function(a){0<a.length&&(h=h.concat(a))},function(a){return d(a)}),f.push(m),r=e._getCountryJSONSForGivenCodes(n[e._browserLanguage],r,g.COUNTRY_ATTRIBUTE),r.then(function(a){0<a.length&&(p=p.concat(a))},function(a){return d(a)}),f.push(r));Promise.all(f).then(function(){return c({countries:h,attributes:p})})},
function(a){return d(a)})})};e._getURLBasedDataJSON=function(){return new Promise(function(a,b){if(k(e._urlBasedData))return a();e._getJSON(g.cloudFormData.CDN_FORMDATA_BASE_URL+"urlbaseddata.json",!1,n.getExtensionURL("content/formdata/urlbaseddata.json")).then(function(d){if(c(d))return q.error("could not load parse urlbaseddata.json"),b(Error("could not url based data"));e._urlBasedData=JSON.parse(d);return a()},function(a){b(a)})})};e._getURLBasedDataForURL=function(b){if(!h(b))throw Error("invalid arguments to _getURLBasedDataForURL");
return new Promise(function(d,f){e._getURLBasedDataJSON().then(function(){if(c(e._urlBasedData))return f(Error("could not load urlbaseddata.json "));var h={},p=a.utils.baseURL(b);if(k(p)&&e._urlBasedData[g.DATA].hasOwnProperty(p)){var l={};l[e._urlBasedData[g.DATA_TYPE][e._urlBasedData[g.DATA][p]]]=!0;m(h,l)}return d(h)},function(a){return f(Error("could not urlbaseddata "+a))})})};e._getDataForURL=function(a,c){if(!h(a))throw Error("Invalid parameter passed to _getDataForURL");return new Promise(function(d,
f){var h={};h[g.RULES]=e._getRules(a);h[g.PREFERENCES]=e._getParsePreferencesRulesForURL(a);h[g.COUNTRY_DATA]=e._getCountryData(a,h[g.PREFERENCES],c);h[g.URL_BASED_DATA]=e._getURLBasedDataForURL(a);h[g.GLOBAL_DATA]=e._getGlobalJSON();Promise.all(Object.values(h)).then(function(a){var c=Object.keys(h),e=b.formDataFactory.create();e.setRule(a[c.indexOf(g.RULES)]);e.setParsePreference(a[c.indexOf(g.PREFERENCES)]);e.setL10nCountries(a[c.indexOf(g.COUNTRY_DATA)].countries);e.setL10nAttributes(a[c.indexOf(g.COUNTRY_DATA)].attributes);
e.setUrlBasedData(a[c.indexOf(g.URL_BASED_DATA)]);e.setGlobal(a[c.indexOf(g.GLOBAL_DATA)]);return d(e.serialize())},function(a){return f(Error("unable to fetch all the JSON contents for the URL. "+a))})})};e.handleMessage=function(a,b){if(!c(a)&&l(b)&&!c(a.payload)&&!c(a.payload.url))switch(a.id){case g.messages.GET_URL_DATA:return e._getDataForURL(a.payload.url,a.payload.lang).then(function(a){b(a)},function(a){q.info("Invalid promise return for _getDataForURL, with error:"+a);b(null)}),!0}};return e}(c.SymBfw,
c.SymWax)})(this);(function(c){c.SymWax.messageHandler=function(a,b){var c={},d=a.utils.isNil,h=a.extensionAdapter,l=b.constants.messages;c._handleMessage=function(a,b,c){if(!d(a))switch(a.id){case l.TRIGGER_AJAX_PARSE_RETRY:h.sendMessageToTab(c,{id:l.TRIGGER_AJAX_PARSE_RETRY_RESPONSE})}};h.addMessageListener(c._handleMessage);h.addTabUpdatedEventListener(function(a,b,c){h.sendMessageToTab(c,{id:l.TRIGGER_FORCED_WAX_ANALYSIS})});return c}(c.SymBfw,c.SymWax)})(this);
(function(c){c.SymWax.init=function(a){var b={},c=SymBfw.logger;b.initializeWaxFormDataLoaderSettings=function(b,f,l){f=void 0===f?null:f;l=void 0===l?null:l;return new Promise(function(d,h){a.formDataLoader.initialize(b,l).then(function(b){d("Form data loader settings initialized");a.manager.initialize(f)},function(a){c.error("Failed to completely initialize Form data loader settings, with error: "+a);h("Failed to initialize Form data loader settings")})})};return b}(c.SymWax)})(this);
(function(c){c.SymWax.telemetryWrapperBG=function(a,b){var c=a.utils.isNil,d=b.constants,h=b.constants.messages,l=a.utils,m=a.telemetryConstants,k=a.logger,q=a.utils.urlWithoutQueryParameters,n={_defaultParameters:null,setDefaultParameter:function(a){c(a)&&k.error("telemetry param is null");n._defaultParameters=a},_handleMessage:function(a,b,d){if(!c(a))switch(a.id){case h.SEND_WAX_TELEMETRY_TO_BG:n.sendDetectionFailureTelemetry(d.url,a.payload)}},sendDetectionFailureTelemetry:function(b,f){if(!c(n._defaultParameters)){var e=
new a.Telemetry(h.SEND_WAX_TELEMETRY_TO_BFW,!0),g=n._defaultParameters;g[m.TRACKING_ID]=d.telemetry.TRACKING_ID;g[m.CLIENT_ID]=l.createNewGuid();e.init(g,function(a){if(!0===a)a={},a[m.parameters.HIT_TYPE]=m.HIT_TYPE.EVENT,a[m.parameters.CATEGORY]=d.telemetry.CATEGORY,a[m.parameters.ACTION]=d.telemetry.type.DETECTION_FAILURE,a[m.parameters.LABEL]=q(b),a=Object.assign({},a,f.customDimensions),e.send(a);else return!1})}}};a.extensionAdapter.addMessageListener(n._handleMessage);return n}(c.SymBfw,c.SymWax)})(this);
(function(c){c.SymWax.manager=function(a,b){var c=b.extensionAdapter,d=a.constants.messages,h=b.utils.isNil,l=b.utils.isntNil,m=b.utils.isInteger,k=b.utils.isEmptyObject,q=a.constants,n={};n._maxThreshold=q.NO_THRESHOLD_CHECK_VALUE;n._processedTabInfos=new Map;n.initialize=function(a){c.addMessageListener(n._handleMessage);l(a)&&m(a)&&(n._maxThreshold=a)};n._getThresholdInfo=function(a){var b=n._processedTabInfos.get(a);k(b)&&(b={processedFramesCount:0,maxThreshold:n._maxThreshold},n._processedTabInfos.set(a,
b));return b};n._handleMessage=function(a,b,e){if(!h(a)&&!h(a.id))switch(e=c.getTabID(e),a.id){case d.CHECK_ANALYSIS_REQUIRED:a=n._getThresholdInfo(e);var f=n._isAnalysisNeeded(a,e);!0===f&&(a.processedFramesCount+=1,n._processedTabInfos.set(e,a));b(f);break;case d.TOP_FRAME_UNLOAD_EVENT:n._processedTabInfos.delete(e)}};n._isAnalysisNeeded=function(a,b){var c=a.processedFramesCount,d=a.maxThreshold;if(d===q.NO_THRESHOLD_CHECK_VALUE)return!0;h(c)&&(c=0);if(c>=d)return!1;n._processedTabInfos.set(b,
a);return!0};return n}(c.SymWax,c.SymBfw)})(this);
