var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,d,b){c!=Array.prototype&&c!=Object.prototype&&(c[d]=b.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var c=0;return function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+c++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(c){var d=0;return $jscomp.iteratorPrototype(function(){return d<c.length?{done:!1,value:c[d++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.iteratorFromArray=function(c,d){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var b=0,a={next:function(){if(b<c.length){var p=b++;return{value:d(p,c[p]),done:!1}}a.next=function(){return{done:!0,value:void 0}};return a.next()}};a[Symbol.iterator]=function(){return a};return a};
$jscomp.polyfill=function(c,d,b,a){if(d){b=$jscomp.global;c=c.split(".");for(a=0;a<c.length-1;a++){var p=c[a];p in b||(b[p]={});b=b[p]}c=c[c.length-1];a=b[c];d=d(a);d!=a&&null!=d&&$jscomp.defineProperty(b,c,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(d){return d})}},"es6","es3");
$jscomp.polyfill("Object.is",function(c){return c?c:function(d,b){return d===b?0!==d||1/d===1/b:d!==d&&b!==b}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(c){return c?c:function(d,b){var a=this;a instanceof String&&(a=String(a));var c=a.length;b=b||0;for(0>b&&(b=Math.max(b+c,0));b<c;b++){var f=a[b];if(f===d||Object.is(f,d))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(c,d,b){if(null==c)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return c+""};$jscomp.polyfill("String.prototype.includes",function(c){return c?c:function(d,b){return-1!==$jscomp.checkStringArgs(this,d,"includes").indexOf(d,b||0)}},"es6","es3");
$jscomp.polyfill("String.prototype.startsWith",function(c){return c?c:function(d,b){var a=$jscomp.checkStringArgs(this,d,"startsWith");d+="";var c=a.length,f=d.length;b=Math.max(0,Math.min(b|0,a.length));for(var l=0;l<f&&b<c;)if(a[b++]!=d[l++])return!1;return l>=f}},"es6","es3");$jscomp.makeIterator=function(c){$jscomp.initSymbolIterator();var d=c[Symbol.iterator];return d?d.call(c):$jscomp.arrayIterator(c)};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(c){function d(){this.batch_=null}function b(a){return a instanceof p?a:new p(function(b,d){b(a)})}if(c&&!$jscomp.FORCE_POLYFILL_PROMISE)return c;d.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};d.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var a=$jscomp.global.setTimeout;d.prototype.asyncExecuteFunction=function(b){a(b,
0)};d.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var d=a[b];a[b]=null;try{d()}catch(m){this.asyncThrow_(m)}}}this.batch_=null};d.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var p=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}};p.prototype.createResolveAndReject_=
function(){function a(a){return function(g){d||(d=!0,a.call(b,g))}}var b=this,d=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};p.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof p)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};p.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(h){this.reject_(h);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};p.prototype.reject_=function(a){this.settle_(2,a)};p.prototype.fulfill_=function(a){this.settle_(1,a)};p.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};p.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)f.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var f=new d;p.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};p.prototype.settleSameAsThenable_=function(a,b){var d=this.createResolveAndReject_();try{a.call(b,d.resolve,d.reject)}catch(m){d.reject(m)}};p.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(y){g(y)}}:
b}var e,g,n=new p(function(a,b){e=a;g=b});this.callWhenSettled_(d(a,e),d(b,g));return n};p.prototype.catch=function(a){return this.then(void 0,a)};p.prototype.callWhenSettled_=function(a,b){function d(){switch(e.state_){case 1:a(e.result_);break;case 2:b(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?f.asyncExecute(d):this.onSettledCallbacks_.push(d)};p.resolve=b;p.reject=function(a){return new p(function(b,d){d(a)})};p.race=function(a){return new p(function(d,
c){for(var e=$jscomp.makeIterator(a),g=e.next();!g.done;g=e.next())b(g.value).callWhenSettled_(d,c)})};p.all=function(a){var d=$jscomp.makeIterator(a),c=d.next();return c.done?b([]):new p(function(a,g){function e(b){return function(g){u[b]=g;f--;0==f&&a(u)}}var u=[],f=0;do u.push(void 0),f++,b(c.value).callWhenSettled_(e(u.length-1),g),c=d.next();while(!c.done)})};return p},"es6","es3");
(function(c){(c.NSSS=c.NSSS||{}).nfmEvents={NAVIGATE_COMPLETE:"89DF66E0-4A4C-4ECE-800B-AA2048A97207",FRAME_BEGIN:"0740B756-B9DF-4D5E-9BBA-14971AF77194",FRAME_END:"73785734-1E75-4E5D-A6D7-2169F43A9F6E",ONCLOSE:"4B42DBE4-7E80-4851-A19C-98D3903AA93C",DOMCONTENT_LOADED:"951DBC0F-E1DB-4E76-8986-A1339B795123",ANALYZE_SEARCH_DOMAIN:"12837E8F-766E-4DC8-84FF-A2231D728B4A",SEARCH_URLS:"A33AD401-A1BC-40B9-B140-555B0FCC3052",SEARCH_URLS_ANALYZED:"5C5556F8-BDE2-45FD-8991-D65AF9322322",PAGE_ANALYZED:"43139813-E528-4C9F-BD20-BFABABCCB53A",
SETTINGS_REQUEST:"902B1CBB-74A2-4500-98B8-075E7E44B0E5",SETTINGS_RESPONSE:"47839CBC-9CC3-4212-B971-C7D1E745FF84",REPORT_SITE:"CAB9C059-62F4-4D3E-964C-13791B476D7C",SEND_PING:"219E396C-E16C-4C49-B182-71486A6B167B",DOWNLOAD_URL_ANALYZED:"8FC606EB-0821-4420-8875-5FF41ED26C9D",DOWNLOAD_EVENT:"5407DEDE-8008-4EFC-A624-AEAFD95A3F9A"}})(this);
(function(c){var d=c.NSSS=c.NSSS||{},b={DEFAULT_HOMEPAGE:"defaultHomepage",DEFAULT_SEARCH:"defaultSearch",TABID:"tabID",TAB_OVERALLSTATUS:"tabstatus",DID_ONBOARDINGFLOW:"didOnBoardingFlow",SHOW_FULLREPORT:"showFullReport",SHOW_REPORTSITE:"showReportSite",NSSS_GLOBAL_SETTINGS_CONTAINER:"44CB4D75-FAD1-449D-9C9E-B0A3090B18B8",NSSS_INSTALLDATEKEY:"extensionInstalldate",BLOCKPAGE:"blockPage",CGUIDKEY:"cutomerGuid",PARAMSTRINGKEY:"paramstring",DS_OCODE:"APN12174",DHP_OCODE:"APN12175",SEARCH_OCODE:"APN12173",
BLOCKEDPAGE_SEARCH_OCODE:"15528",TPR:"111",PRT:"SSS",VERSION:"2.11.0.30",PARTNERIDKEY:"chn",CAMPAIGN_MEDIUM:"campaignMedium",IS_FLAVORIZED:"flavorized",DEFAULT_PARTNER_ID:"store",PRODUCT_NAME:"Norton Safe Web",TELEMETRY_TRACKING_ID:"UA-12436054-58",BACKUP_HOMEPAGE:"backupHomePage"};b.PRODUCT_LABEL=c.SymBfw.extensionAdapter.getExtensionId()+"-"+b.VERSION;b.TELEMETRY_OPTOUT_URL="https://##TELEMETRY_OPTOUT_URI##.norton.com/xbp-tour";b.TELEMETRY_OPTOUT_TIMEOUT="##TELEMETRYTIMEOUT##";b.DEFAULT_INFO_ICON=
"ic-safeweb-info-50.svg";b.IS_HP_FIRST_LAUNCH="isHPFirstLaunch";b.IS_DSP_FIRST_LAUNCH="isDSPFirstLaunch";b.HP_ID="ophopjonlomiomjdjphigoapegkicmih";b.SHOULD_BLOCK_KEY="shouldBlock";b.CONTINUE_SITE_LOADED_KEY="blockedSiteLoaded";b.NORTONSAFE_HOSTNAME="nortonsafe.search.ask.com";b.SAFE_WEB_EXTENSION="Norton Safe Web";b.SEARCHBOX_VISIBLE="false";b.NATIVE_TAB_PREFIX=["chrome://","about:"];b.ABOUT_BLANK="about:blank";b.SETTINGS_PAGE="/content/ui/settings.html";b.BUTTON_GLOBAL_CHECKED="../images/btn-global-checked.svg";
b.BUTTON_GLOBAL_UNCHECKED="../images/btn-global-unchecked.svg";b.DEFAULT_COUNTRY="US";b.CAUTION_IMAGE="safe-web-icon-norton-caution";b.WARNING_IMAGE="safe-web-icon-warning";b.UNTESTED_IMAGE="safe-web-icon-norton-untested";b.SAFE_IMAGE="safe-web-icon-norton-safe";b.RETINAL_UNTESTED_IMAGE="safe-web-icon-norton-untested@2x";b.RETINAL_SAFE_IMAGE="safe-web-icon-norton-safe@2x";b.SETTINGS_KEY_DS="defaultSearchEnabled";b.PRIVACY_POLICY_SSDCAT=150;b.SITE_DIRECTOR_URL="http://sitedirector.symantec.com/932743328?ssdcat=SSDCAT_VALUE&env=prod&origin=nsss&displang=iso3:ISO3_LAN_CODE&displocale=iso3:ISO3_COUNTRY_CODE";
b.ISO2_ISO3_LANGUAGE={AB:"ABK",AA:"AAR",AF:"AFR",AK:"AKA",SQ:"SQI",AM:"AMH",AR:"ARA",AN:"ARG",HY:"HYE",AS:"ASM",AV:"AVA",AE:"AVE",AY:"AYM",AZ:"AZE",BM:"BAM",BA:"BAK",EU:"EUS",BE:"BEL",BN:"BEN",BH:"BIH",BI:"BIS",BS:"BOS",BR:"BRE",BG:"BUL",MY:"MYA",CA:"CAT",CH:"CHA",CE:"CHE",NY:"NYA",ZH:"ZHO",CV:"CHV",KW:"COR",CO:"COS",CR:"CRE",HR:"HRV",CS:"CES",DA:"DAN",DV:"DIV",NL:"NLD",DZ:"DZO",EN:"ENG",EO:"EPO",ET:"EST",EE:"EWE",FO:"FAO",FJ:"FIJ",FI:"FIN",FR:"FRA",FF:"FUL",GL:"GLG",KA:"KAT",DE:"DEU",EL:"ELL",GN:"GRN",
GU:"GUJ",HT:"HAT",HA:"HAU",HE:"HEB",HZ:"HER",HI:"HIN",HO:"HMO",HU:"HUN",IA:"INA",ID:"IND",IE:"ILE",GA:"GLE",IG:"IBO",IK:"IPK",IO:"IDO",IS:"ISL",IT:"ITA",IU:"IKU",JA:"JPN",JV:"JAV",KL:"KAL",KN:"KAN",KR:"KAU",KS:"KAS",KK:"KAZ",KM:"KHM",KI:"KIK",RW:"KIN",KY:"KIR",KV:"KOM",KG:"KON",KO:"KOR",KU:"KUR",KJ:"KUA",LA:"LAT",LB:"LTZ",LG:"LUG",LI:"LIM",LN:"LIN",LO:"LAO",LT:"LIT",LU:"LUB",LV:"LAV",GV:"GLV",MK:"MKD",MG:"MLG",MS:"MSA",ML:"MAL",MT:"MLT",MI:"MRI",MR:"MAR",MH:"MAH",MN:"MON",NA:"NAU",NV:"NAV",ND:"NDE",
NE:"NEP",NG:"NDO",NB:"NOB",NN:"NNO",NO:"NOR",II:"III",NR:"NBL",OC:"OCI",OJ:"OJI",CU:"CHU",OM:"ORM",OR:"ORI",OS:"OSS",PA:"PAN",PI:"PLI",FA:"FAS",PL:"POL",PS:"PUS",PT:"POR",QU:"QUE",RM:"ROH",RN:"RUN",RO:"RON",RU:"RUS",SA:"SAN",SC:"SRD",SD:"SND",SE:"SME",SM:"SMO",SG:"SAG",SR:"SRP",GD:"GLA",SN:"SNA",SI:"SIN",SK:"SLK",SL:"SLV",SO:"SOM",ST:"SOT",ES:"SPA",SU:"SUN",SW:"SWA",SS:"SSW",SV:"SWE",TA:"TAM",TE:"TEL",TG:"TGK",TH:"THA",TI:"TIR",BO:"BOD",TK:"TUK",TL:"TGL",TN:"TSN",TO:"TON",TR:"TUR",TS:"TSO",TT:"TAT",
TW:"TWI",TY:"TAH",UG:"UIG",UK:"UKR",UR:"URD",UZ:"UZB",VE:"VEN",VI:"VIE",VO:"VOL",WA:"WLN",CY:"CYM",WO:"WOL",FY:"FRY",XH:"XHO",YI:"YID",YO:"YOR",ZA:"ZHA",ZU:"ZUL"};b.ISO2_ISO3_COUNTRY={AX:"ALA",AF:"AFG",AL:"ALB",DZ:"DZA",AS:"ASM",AD:"AND",AO:"AGO",AI:"AIA",AQ:"ATA",AG:"ATG",AR:"ARG",AM:"ARM",AW:"ABW",AU:"AUS",AT:"AUT",AZ:"AZE",BS:"BHS",BH:"BHR",BD:"BGD",BB:"BRB",BY:"BLR",BE:"BEL",BZ:"BLZ",BJ:"BEN",BM:"BMU",BT:"BTN",BO:"BOL",BA:"BIH",BW:"BWA",BV:"BVT",BR:"BRA",IO:"IOT",BN:"BRN",BG:"BGR",BF:"BFA",BI:"BDI",
KH:"KHM",CM:"CMR",CA:"CAN",CV:"CPV",KY:"CYM",CF:"CAF",TD:"TCD",CL:"CHL",CN:"CHN",CX:"CXR",CC:"CCK",CO:"COL",KM:"COM",CD:"COD",CG:"COG",CK:"COK",CR:"CRI",CI:"CIV",HR:"HRV",CU:"CUB",CY:"CYP",CZ:"CZE",DK:"DNK",DJ:"DJI",DM:"DMA",DO:"DOM",EC:"ECU",EG:"EGY",SV:"SLV",GQ:"GNQ",ER:"ERI",EE:"EST",ET:"ETH",FK:"FLK",FO:"FRO",FJ:"FJI",FI:"FIN",FR:"FRA",GF:"GUF",PF:"PYF",TF:"ATF",GA:"GAB",GM:"GMB",GE:"GEO",DE:"DEU",GH:"GHA",GI:"GIB",GR:"GRC",GL:"GRL",GD:"GRD",GP:"GLP",GU:"GUM",GT:"GTM",GN:"GIN",GW:"GNB",GY:"GUY",
HT:"HTI",HM:"HMD",HN:"HND",HK:"HKG",HU:"HUN",IS:"ISL",IN:"IND",ID:"IDN",IR:"IRN",IQ:"IRQ",IE:"IRL",IL:"ISR",IT:"ITA",JM:"JAM",JP:"JPN",JO:"JOR",KZ:"KAZ",KE:"KEN",KI:"KIR",KP:"PRK",KR:"KOR",KW:"KWT",KG:"KGZ",LA:"LAO",LV:"LVA",LB:"LBN",LS:"LSO",LR:"LBR",LY:"LBY",LI:"LIE",LT:"LTU",LU:"LUX",MO:"MAC",MK:"MKD",MG:"MDG",MW:"MWI",MY:"MYS",MV:"MDV",ML:"MLI",MT:"MLT",MH:"MHL",MQ:"MTQ",MR:"MRT",MU:"MUS",YT:"MYT",MX:"MEX",FM:"FSM",MD:"MDA",MC:"MCO",MN:"MNG",MS:"MSR",MA:"MAR",MZ:"MOZ",MM:"MMR",NA:"NAM",NR:"NRU",
NP:"NPL",NL:"NLD",AN:"ANT",NC:"NCL",NZ:"NZL",NI:"NIC",NE:"NER",NG:"NGA",NU:"NIU",NF:"NFK",MP:"MNP",NO:"NOR",OM:"OMN",PK:"PAK",PW:"PLW",PS:"PSE",PA:"PAN",PG:"PNG",PY:"PRY",PE:"PER",PH:"PHL",PN:"PCN",PL:"POL",PT:"PRT",PR:"PRI",QA:"QAT",RE:"REU",RO:"ROU",RU:"RUS",RW:"RWA",SH:"SHN",KN:"KNA",LC:"LCA",PM:"SPM",VC:"VCT",WS:"WSM",SM:"SMR",ST:"STP",SA:"SAU",SN:"SEN",CS:"SCG",SC:"SYC",SL:"SLE",SG:"SGP",SK:"SVK",SI:"SVN",SB:"SLB",SO:"SOM",ZA:"ZAF",GS:"SGS",ES:"ESP",LK:"LKA",SD:"SDN",SR:"SUR",SJ:"SJM",SZ:"SWZ",
SE:"SWE",CH:"CHE",SY:"SYR",TW:"TWN",TJ:"TJK",TZ:"TZA",TH:"THA",TL:"TLS",TG:"TGO",TK:"TKL",TO:"TON",TT:"TTO",TN:"TUN",TR:"TUR",TM:"TKM",TC:"TCA",TV:"TUV",UG:"UGA",UA:"UKR",AE:"ARE",GB:"GBR",US:"USA",UM:"UMI",UY:"URY",UZ:"UZB",VU:"VUT",VA:"VAT",VE:"VEN",VN:"VNM",VG:"VGB",VI:"VIR",WF:"WLF",EH:"ESH",YE:"YEM",ZM:"ZMB",ZW:"ZWE"};b.ONBOARDING_URL="https://identitysafe.norton.com/";b.URL_PARAMS_KEY={PARTNERID:"partnerid",CGUID:"guid",DATE_OF_INSTALL:"doi",OCODE:"o",PRT:"prt",VERSION:"ver",TPR:"tpr",PARTNER_UNIT_ID:"puid",
PRODUCT_NAME:"product",LAYOUT_TYPE:"layouttype",TRACK_ID:"trackid"};b.ONBOARDING_PORTAL_DOMAIN="norton.com";b.ONBOARDING_PORTAL_SUBDOMAIN=["identitysafe","search","searchsafe"];b.telemetryOptOut={REOFFER_TIME_WINDOW:7776E6,NOTIFICATION_LEEWAY:3E5};b.IS_WCID_HEURISTICS_LOW_PRIORITY=!0;b.SCAM_INSIGHT_BLOCK_PAGE_PATH="content/ui/scam-insight-block-page.html";b.BLOCK_PAGE_PATH="content/ui/blockedPage.html";b.webProtectionPolicy={WEB_PROTECTION_POLICY_CONTAINER:"62517E4C-BFAD-46DE-977B-1A388E5399C7",SAFEWEB_STATUS:"AEE8B6DB-FB95-46D2-9C21-B594440BDF91",
WCID_HEURISTICS_STATUS:"B0E77D14-7B68-477E-981C-21EB2E65A7C9",WCID_CHECK_URL_STATUS:"4621C921-C4C1-4813-9F24-83FF7800471F"};b.performanceReporter={NSSS:"NSSS"};b.scamInsightAgeRating={VERY_NEW:"verynew",NEW:"new"};b.scamInsightPrevalenceRating={NO_USERS:"nousers",FEW_USERS:"fewusers"};b.scamInsightScore={LOWER_LIMIT:25,UPPER_LIMIT:49};b.WCID_ANALYSIS_WAIT_TIME=2E3;b.CHROME_STORE_URL="https://chrome.google.com/webstore/detail/";d.constants=b})(this);
(function(c){(c.NSSS=c.NSSS||{}).uiConstants={MESSAGES:{BLOCKEDPAGE_SEARCH:"93D3C1B6-E181-48DA-8841-EB995ADC5D48",BLOCKEDPAGE_INIT:"049B762D-F8CB-4BB1-93AB-F9D55E13D65E",BEFORE_UNLOAD_EVENT:"6D54B993-F098-4C47-B4CC-596C3D22E402",DOMEVENT:"4BEBC3FD-7552-4AE9-9FB1-717AA14B650A",SHOW_ANNOTATION_POPUP:"9BBDD5C9-4BAF-44EC-9F29-67AD5E2CF524",CLOSE_ANNOATION_POPUP:"47420986-DBE5-471F-8D64-64DCEBDF8541",COLLECT_URL_RESPONSE:"0AD25128-5D2A-422C-88F8-3F50E8579C69",OPEN_FULLREPORT:"FAAABCAF-50C5-4EE5-B18B-4E4FA9425B70",
FLAVOR_RETRIEVED:"554E40BF-48A3-416D-8988-9661B90F94CC",OPEN_DO_NOT_BLOCK_PAGE:"54E66C14-3E30-4F16-B4BC-259C662FF64B",HANDLE_UI_EVENTS:"B2C77321-D8F4-47A8-DCCF-D99BE95F4BC9",UPDATE_POPOVER_UI:"642A1139-910F-4D9A-B15F-12BBB6AA6276",SCAM_INSIGHT_BLOCKPAGE_INIT:"de656873-852a-4c10-8698-be4040be18ff",SCAM_EXIT_SITE:"da5f0029-7869-41af-bfc6-cd5138f13c07",SCAM_CONTINUE_TO_SITE:"9e7cd3d3-759c-49f6-87ae-4c49180d6118",SCAM_REPORT_ISSUE:"97d7cc47-bfdd-480e-9d28-0d069d965283",SET_TELEMETRY_ENABLED:"6213A0CF-075B-42BB-861A-0E54D62DE44E",
SETTINGS_PRIVACY_POLICY:"53E7B83C-CB55-463F-91B0-41F125589605",SIGN_OUT:"5CC02BA4-A79E-4451-B64A-B61217EC6B16",SETTINGS_PAGE_UI_INIT:"99534CCC-1303-4135-B98F-2B57FB3C2115"},BLOCKPAGE:{TYPE:{KNOWNBAD:"knownbad",SUSPECTEDBAD:"suspectedbad",MALICIOUS:"malicious",MALICIOUSSHOP:"maliciousshop"},HTML:"blockedPage.html",parameterKeys:{ORIGINAL_URL:"originalURL",REPORT_URL:"reportURL",BLOCK_PAGE_TYPE:"blockPageType"}},SCAM_INSIGHT_BLOCK_PAGE:{strings:"Safe Web;Scam Insight: Personal Information Risk;This site is safe, but\u2026;It asks for personal information and is not well established with the Norton Community. Use caution when entering any of your information on this site. ;Visit ;Norton ;to learn more about personal information risk on Web sites.;Age: ;Very New;This website was published very recently.;New;This website has been available for a short time.;Prevalence: ;No Users;No Norton community members have used this site.;Few Users;Very few Norton community members have used this site.;Continue to Site;Exit Site;If you think this website is categorized incorrectly, ;Report Issue.".split(";")},
SETTINGS_UI:{strings:"Home Page;Safe Web;Safe Search;Settings;Share Data with Norton;Share usage and error data anonymously with Norton and help us make our products even better;Privacy Policy;Signed in as;Sign out".split(";")},BROWSER_NOTIFICATION:{strings:["You have successfully logged out of your Norton Account","Sorry, something went wrong. Please try again."]},EXTENSION_TYPE:"__EXTNTYPE__",SAFEWEB_EXTENSION:"sw",BROWSER_NOTIFICATION_IMAGE:"../../icon-48.png"}})(executionContext);
(function(c){(c.NSSS=c.NSSS||{}).uiHelper=function(d,b){var a={},c=d.utils.isNil,f={untested:0,safe:1,caution:2,warn:3},l=b.constants,e=d.localizer,h=b.uiConstants.BLOCKPAGE.TYPE,m={};m.Safe=f.safe;m.Caution=f.caution;m.Untested=f.untested;m["Safe Web is off"]=f.untested;m.Warning=f.warn;m["Not Licensed"]=f.warn;m["Unsafe to Shop"]=f.warn;m.Monitoring=f.untested;m["Page not analyzed"]=f.untested;a.siteStatusRatingMap=m;a.rating=f;a.messageType={SEARCH:0,FULLREPORT:1,REPORTSITE:2,SETTINGS:3,ONLOAD:4};
a.ratingStyle=["untested","safe","caution","warn"];a.uiEvents="UI-Event";a.settingsEvent="Settings-Event";a.setupUI="Setup-UI";a.updateUI="Update-UI";a.updateUIComplete="Update-UI-Complete";a.setupSettingsUI="Setup-Settings-UI";a.FULL_REPORT_EVENTID="2786E625-7D87-4997-AB8B-DB46539A48F8";a.REPORTSITE_EVENTID="76DAED94-D538-4C07-909D-8C7C0442FA5C";a.SETTINGS_CLICKED_EVENTID="D33EEEAD-B101-4A69-8B71-564E69FD5880";a.SEARCH_EVENTID="5C57C303-1C69-4C07-850C-062563BE3C1D";a.DEFAULT_SEARCH_EVENTID="FD6141FE-3E11-40E1-88A9-ED2EECC2E052";
a.DEFAULT_HOMEPAGE_EVENTID="D266FC01-E845-4292-8890-30AE32FE48E2";a.showFullReportForSessionID=function(a){a=d.settings.loadSettingsContainer(a);if(0===Object.keys(a.collection).length)return!1;a=a.getObject(l.SHOW_FULLREPORT);c(a)&&(a=!0);return a};a.setShowReportSiteForSessionID=function(a,b){d.settings.loadSettingsContainer(a).setObject(l.SHOW_REPORTSITE,b)};a.showReportSiteForSessionID=function(a){a=d.settings.loadSettingsContainer(a);if(0===Object.keys(a.collection).length)return!1;a=a.getObject(l.SHOW_REPORTSITE);
c(a)&&(a=!0);return a};a.toolbarStatusForSessionID=function(a){var g=d.settings,e=b.nfmEvents;if(c(g))return logger.log("Settings API unavailable. Context incorrect."),null;if(c(a))return null;a=g.loadSettingsContainer(a);if(0===Object.keys(a.collection).length)return null;e=a.getObject(e.PAGE_ANALYZED);return c(e)?null:e.getRating()};a.uiStatusForSessionID=function(g,d){var n=b.helperUtils.getFeatureFlavorization();if(b.helperUtils.isURLWhitelisted(d))return a.uiStatusForUntestedSite(d);var f=a.toolbarStatusForSessionID(g);
if(c(f))return a.uiStatusForUntestedSite(d);d=f.siteStatus;var p=a.showFullReportForSessionID(g),h=a.showReportSiteForSessionID(g);a.setShowReportSiteForSessionID(g,h);g=e.getLocalizedString(f.siteStatus);return{uiStatus:{sitename:f.url,rating:m[d],ratingText:g,computerThreats:f.computerThreatAttributes,identityThreats:f.identityThreatAttributes,annoyanceThreats:f.annoyanceFactorAttributes,totalThreats:f.computerThreatAttributes+f.identityThreatAttributes+f.annoyanceFactorAttributes,showSafeWebSearchbox:n.showSafeWebSearchbox},
regularIcon:f.siteIcon+".png",retinaIcon:f.siteIcon+"@2x.png",showFullReport:p,showReportSite:h,siteRating:f.siteRating,fullReportURL:f.fullReportURL}};a.privateUIStatusForSafeOrUntestedOrMonitoringSite=function(a,d){var g=b.helperUtils.getFeatureFlavorization(),n=e.getLocalizedString(d);if(c(a)||""===a)a=l.ABOUT_BLANK;a={sitename:a,rating:f.untested,ratingText:n,computerThreats:0,identityThreats:0,annoyanceThreats:0,totalThreats:0,showSafeWebSearchbox:g.showSafeWebSearchbox};g=l.UNTESTED_IMAGE+".png";
n=l.RETINAL_UNTESTED_IMAGE+".png";"Safe"===d&&(g=l.SAFE_IMAGE+".png",n=l.RETINAL_SAFE_IMAGE+".png",a.rating=f.safe);return{uiStatus:a,regularIcon:g,retinaIcon:n,showFullReport:!1,showReportSite:!1}};a.uiStatusForSafeSite=function(b){return a.privateUIStatusForSafeOrUntestedOrMonitoringSite(b,"Safe")};a.uiStatusForUntestedSite=function(b){return a.privateUIStatusForSafeOrUntestedOrMonitoringSite(b,"Untested")};a.uiStatusForMonitoringSite=function(b){return a.privateUIStatusForSafeOrUntestedOrMonitoringSite(b,
"Monitoring")};a.getBlockPageString=function(b){var g=a.blockPageStrings();switch(b){case h.KNOWNBAD:var d=a.knownbadWindowStrings(g);break;case h.SUSPECTEDBAD:d=a.suspectedbadWindowStrings(g);break;case h.MALICIOUS:d=a.maliciousWindowStrings(g);break;case h.MALICIOUSSHOP:d=a.maliciousshopWindowStrings(g)}return d};a.popoverWindowStrings=function(){return{search:e.getLocalizedString("Search the Web Safely"),rating:{nortonRating:e.getLocalizedString("Norton Rating"),computerThreats:e.getLocalizedString("Computer Threats"),
identityThreats:e.getLocalizedString("Identity Threats"),annoyanceThreats:e.getLocalizedString("Annoyance Threats"),totalThreats:e.getLocalizedString("Total Threats"),fullReport:e.getLocalizedString("Full Safe Web report"),reportSite:e.getLocalizedString("Report this site"),nortonSafeWeb:e.getLocalizedString("Norton Safe Web")}}};a.blockPageStrings=function(){return{blockedBy:e.getLocalizedString("BLOCKED BY"),line2:e.getLocalizedString("You attempted to access:"),description2:e.getLocalizedString("It is highly recommended that you do NOT visit this page."),
visit_symc1:e.getLocalizedString("Visit"),symantec:e.getLocalizedString("Norton"),visit_symc2:e.getLocalizedString("to learn more about phishing and internet security."),linkToSite:e.getLocalizedString("Continue to the site"),reportSite:e.getLocalizedString("View Full Report"),searchBoxText:e.getLocalizedString("Search for a safer site")}};a.knownbadWindowStrings=function(a){a.title=e.getLocalizedString("Fraudulent Web Page Blocked");a.description1=e.getLocalizedString("This web page is a known fraudulent web page.");
return a};a.maliciousWindowStrings=function(a){a.title=e.getLocalizedString("Dangerous Web Page Blocked");a.description1=e.getLocalizedString("This is a known dangerous web page.");return a};a.maliciousshopWindowStrings=function(a){a.title=e.getLocalizedString("Dangerous Web Page Blocked");a.description1=e.getLocalizedString("This is a known dangerous web page.");return a};a.suspectedbadWindowStrings=function(a){a.title=e.getLocalizedString("Suspicious Website Blocked");a.description1=e.getLocalizedString("For your protection, this web page has been blocked and submitted for review.");
return a};a.keepAssistWindowStrings=function(a){var b=!0===a?e.getLocalizedString("Norton Safe Search"):e.getLocalizedString("Norton Home Page");a=!0===a?e.getLocalizedString("Safe Search"):e.getLocalizedString("Home Page");return{title1:e.getLocalizedString("Welcome to"),title2:e.getLocalizedString("Norton"),title3:a,desc1:e.getLocalizedString("Thank you for choosing Norton. When a Chrome message appears at the top right of the screen, click"),desc2:e.getLocalizedString("Keep changes"),desc3:e.getLocalizedStringWithFormat("to maintain your {0} protection in Chrome.",
[b]),btnContinue:e.getLocalizedString("Continue")}};return a}(c.SymBfw,c.NSSS)})(executionContext);
(function(c){(c.NSSS=c.NSSS||{}).globalSettings=function(d,b){var a={},c=d.settings,f=d.utils.isNil,l=d.utils.isntNil,e=d.utils.isFunction,h=b.constants,m=d.logger;a.settingsContainer=null;a.initialize=function(b){if(!e(b))throw Error("callback must be a function");c.loadSettingsContainer(h.NSSS_GLOBAL_SETTINGS_CONTAINER,!0,function(g,d,e){!1===g||f(d)?(m.error("failed to load NSSS_GLOBAL_SETTINGS_CONTAINER"),b(!1)):(a.settingsContainer=d,a.getCGuid(),b(!0))})};a.getValue=function(a){return f(this.settingsContainer)?
(m.error("settings not initialized"),null):this.settingsContainer.getObject(a)};a.setValue=function(a,b){f(this.settingsContainer)?m.error("settings not initialized"):this.settingsContainer.setObject(a,b)};a.getDefaultHomepage=function(){return a.getValue(h.DEFAULT_HOMEPAGE)};a.getDefaultSearch=function(){return a.getValue(h.DEFAULT_SEARCH)};a.setDefaultHomepage=function(b){a.setValue(h.DEFAULT_HOMEPAGE,b)};a.setDefaultSearch=function(b){a.setValue(h.DEFAULT_SEARCH,b)};a.getInstallDate=function(){var b=
a.getValue(h.NSSS_INSTALLDATEKEY);f(b)&&(b=new Date,b=[b.getFullYear(),b.getMonth()+1,b.getDate()].join("-"),a.setInstallDate(b));return b};a.setInstallDate=function(b){l(b)&&a.setValue(h.NSSS_INSTALLDATEKEY,b)};a.setPUID=function(b){l(b)&&a.setValue(h.URL_PARAMS_KEY.PARTNER_UNIT_ID,b)};a.setProduct=function(b){l(b)&&a.setValue(h.URL_PARAMS_KEY.PRODUCT_NAME,b)};a.getProduct=function(){var b=a.getValue(h.URL_PARAMS_KEY.PRODUCT_NAME);f(b)&&(b=h.PRT);return b};a.setVersion=function(b){l(b)&&a.setValue(h.URL_PARAMS_KEY.VERSION,
b)};a.getVersion=function(){var b=a.getValue(h.URL_PARAMS_KEY.VERSION);f(b)&&(b=h.VERSION);return b};a.setLayoutType=function(b){l(b)&&a.setValue(h.URL_PARAMS_KEY.LAYOUT_TYPE,b)};a.getPUID=function(){return a.getValue(h.URL_PARAMS_KEY.PARTNER_UNIT_ID)};a.getLayoutType=function(){return a.getValue(h.URL_PARAMS_KEY.LAYOUT_TYPE)};a.getCGuid=function(){var b=a.getValue(h.CGUIDKEY);f(b)&&(b=d.utils.createNewGuid(),a.setCGuid(b));return b};a.setCGuid=function(b){l(b)&&a.setValue(h.CGUIDKEY,b)};a.getPartnerId=
function(){var b=a.getValue(h.PARTNERIDKEY);f(b)&&(b=h.DEFAULT_PARTNER_ID);return b};a.setPartnerId=function(b){l(b)&&a.setValue(h.PARTNERIDKEY,b)};a.getCampaignMedium=function(){var b=a.getValue(h.CAMPAIGN_MEDIUM);return f(b)?h.DEFAULT_PARTNER_ID:b};a.setCampaignMedium=function(b){f(b)||a.setValue(h.CAMPAIGN_MEDIUM,b)};a.setFlavorized=function(b){var d=a.getValue(h.IS_FLAVORIZED);f(d)&&a.setValue(h.IS_FLAVORIZED,b)};a.getFlavorized=function(){var b=a.getValue(h.IS_FLAVORIZED);return b=f(b)?!1:b};
a.getParamsString=function(){var b=a.getValue(h.PARAMSTRINGKEY);return f(b)?"":b};a.setParamsString=function(b){l(b)&&0<b.length&&a.setValue(h.PARAMSTRINGKEY,b)};a.getTrackId=function(){return a.getValue(h.URL_PARAMS_KEY.TRACK_ID)};a.setTrackID=function(b){l(b)&&a.setValue(h.URL_PARAMS_KEY.TRACK_ID,b)};return a}(c.SymBfw,c.NSSS)})(executionContext);
(function(c){c.NSSS.telemetryWrapper=function(d,b){var a={},c=d.utils.isntNil,f=d.utils.isNil,l=d.utils.isString,e=d.telemetryConstants,h=b.globalSettings,m=b.constants,g=b.uiConstants.BLOCKPAGE.TYPE;a.blockPage={};a.blockPage.parameters={};a.TELEMETRY_CATEGORY={SEARCH:"search",POPUP_UI:"popupui",KEEP_ASSIST_UI:"keep_assist_ui",WEB_PROTECTION:"web_protection",SCAM_INSIGHT:"Scam_Insight",BLOCKPAGE:{knownbad:"antiphishing",suspectedbad:"antiphishing",IPS:"ips",malicious:"shasta",maliciousshop:"shasta"}};
a.actionType={SEARCH:{SEARCH_ENTITLEMENTS:"searchEntitlements",DEFAULT_SEARCH:"ds",DEFAULT_HOMEPAGE:"dhp",HOME_PAGE_LOADED:"homepage_loaded",SEARCH_QUERY:"search_query",UI_SEARCH_QUERY:"ui_search_query",BLOCKEDPAGE_SEARCH_QUERY:"blockedPage_search_query",ACTION_CLICKED:"action_clicked"},UI:{SHOW_POPUP_UI:"show_popup_ui",KEEP_ASSIST_UI_SHOWN:"keep_assist_shown",KEEP_ASSIST_CONTINUE_BUTTON_CLICKED:"continue_button_clicked",SCAM_INSIGHT_CONTINUE_TO_SITE:"scam_insight_continue_to_site",SCAM_INSIGHT_REPORT_ISSUE:"scam_insight_report_issue"},
PAGE:{WCID_RELOAD:"wcid_reload",SCAM_INSIGHT_PAGE_DISPLAYED:"scam_insight_page_displayed",WCID_BLOCK_PAGE_DISPLAYED_AFTER_SCAM_BLOCK_PAGE:"wcid_blockpage_displayed_after_scam_block_page"},BLOCKPAGE:{CONTINUE_TO_SITE:"continue_to_site_clicked",BLOCK_PAGE_SHOWN:"block_page_shown"}};a.searchFeature={DEFAULT_HOMEPAGE:"hp",DEFAULT_SEARCH_PROVIDER:"dsp"};a.sendExtensionInstall=function(){a.send(e.TELEMETRY_CATEGORY.EXTENSION,e.actionType.EXTENSION.INSTALL,m.PRODUCT_LABEL)};a.sendExtensionUpdate=function(){a.send(e.TELEMETRY_CATEGORY.EXTENSION,
e.actionType.EXTENSION.UPDATE,m.PRODUCT_LABEL)};a.sendSearchStatus=function(b,d){b=f(b)?!1:b;d=f(d)?!1:d;a.send(a.TELEMETRY_CATEGORY.SEARCH,a.actionType.SEARCH.SEARCH_ENTITLEMENTS,a.actionType.SEARCH.DEFAULT_SEARCH+"-"+b+"-"+a.actionType.SEARCH.DEFAULT_HOMEPAGE+"-"+d)};a.sendDefaultSearchEvent=function(){a.send(a.TELEMETRY_CATEGORY.SEARCH,a.actionType.SEARCH.SEARCH_QUERY,m.VERSION)};a.sendUISearchEvent=function(){a.send(a.TELEMETRY_CATEGORY.SEARCH,a.actionType.SEARCH.UI_SEARCH_QUERY,m.VERSION)};a.sendBlockedPageSearchEvent=
function(){a.send(a.TELEMETRY_CATEGORY.SEARCH,a.actionType.SEARCH.BLOCKEDPAGE_SEARCH_QUERY,m.VERSION)};a.sendActionClickEvent=function(){a.send(a.TELEMETRY_CATEGORY.SEARCH,a.actionType.SEARCH.ACTION_CLICKED,m.VERSION)};a.sendShowPopupUIEvent=function(b){if(f(b))throw Error("Page URL cannot be null");var d=a.TELEMETRY_CATEGORY.POPUP_UI,e=a.actionType.UI.SHOW_POPUP_UI;b=new URI(b);var c=b.pathname();b.domain();a.send(d,e,c)};a.sendKeepAssistShownEvent=function(b){if(f(b)||!l(b))throw Error("extn_name is not valid.");
if(b!==a.searchFeature.DEFAULT_HOMEPAGE&&b!==a.searchFeature.DEFAULT_SEARCH_PROVIDER)throw Error("extn_name should be either '"+a.searchFeature.DEFAULT_HOMEPAGE+"' or '"+a.searchFeature.DEFAULT_SEARCH_PROVIDER+"'. ");a.send(a.TELEMETRY_CATEGORY.KEEP_ASSIST_UI,a.actionType.UI.KEEP_ASSIST_UI_SHOWN,b)};a.sendKeepAssistContinueButtonClickedEvent=function(b){if(f(b)||!l(b))throw Error("extn_name is not valid.");if(b!==a.searchFeature.DEFAULT_HOMEPAGE&&b!==a.searchFeature.DEFAULT_SEARCH_PROVIDER)throw Error("extn_name should be either '"+
a.searchFeature.DEFAULT_HOMEPAGE+"' or '"+a.searchFeature.DEFAULT_SEARCH_PROVIDER+"'. ");a.send(a.TELEMETRY_CATEGORY.KEEP_ASSIST_UI,a.actionType.UI.KEEP_ASSIST_CONTINUE_BUTTON_CLICKED,b)};a.sendWcidReloadPageEvent=function(){a.send(a.TELEMETRY_CATEGORY.WEB_PROTECTION,a.actionType.PAGE.WCID_RELOAD,m.VERSION)};a.sendBlockPageTelemetry=function(b,e,c){if(f(b)||f(e))throw Error("URL or blockPageType cannot be null");b=d.utils.urlWithoutQueryParameters(b,!0);var n=e===g.KNOWNBAD?"fraudulent":"suspicious";
c=!0===c?a.actionType.BLOCKPAGE.CONTINUE_TO_SITE:a.actionType.BLOCKPAGE.BLOCK_PAGE_SHOWN;e=a.TELEMETRY_CATEGORY.BLOCKPAGE[e];a.send(e,e===a.TELEMETRY_CATEGORY.BLOCKPAGE.knownbad?n+"_"+c:e+"_"+c,b)};a.checkStringIsValid=function(a){if(!l(a))throw Error(a+" must be of type string");};a.sendScamBlockPageVisitedEvent=function(b){this.checkStringIsValid(b);var e=null;try{e=d.utils.urlWithoutQueryParameters(b,!0)}catch(x){d.logger.debug("Failed to get URL without params"),e=d.utils.getDomain(b)}if(f(e))return null;
a.send(a.TELEMETRY_CATEGORY.SCAM_INSIGHT,a.actionType.PAGE.SCAM_INSIGHT_PAGE_DISPLAYED,e)};a.sendScamContinueToSiteEvent=function(){a.send(a.TELEMETRY_CATEGORY.SCAM_INSIGHT,a.actionType.UI.SCAM_INSIGHT_CONTINUE_TO_SITE,m.PRODUCT_LABEL)};a.sendScamReportIssueEvent=function(){a.send(a.TELEMETRY_CATEGORY.SCAM_INSIGHT,a.actionType.UI.SCAM_INSIGHT_REPORT_ISSUE,m.PRODUCT_LABEL)};a.sendWCIDBlockPageDisplayAfterScamBlockPageEvent=function(){a.send(a.TELEMETRY_CATEGORY.SCAM_INSIGHT,a.actionType.PAGE.WCID_BLOCK_PAGE_DISPLAYED_AFTER_SCAM_BLOCK_PAGE,
m.PRODUCT_LABEL)};a.send=function(a,b,g,f){this.checkStringIsValid(a);this.checkStringIsValid(b);this.checkStringIsValid(g);var n={};n[e.parameters.CAMPAIGN_SOURCE]=h.getPartnerId();n[e.parameters.CAMPAIGN_MEDIUM]=h.getCampaignMedium();n[e.parameters.HIT_TYPE]=e.HIT_TYPE.EVENT;n[e.parameters.CATEGORY]=a;n[e.parameters.ACTION]=b;n[e.parameters.LABEL]=g;if(c(f))for(var p in f)n[p]=f[p];(d.telemetry||d.telemetryProxy).send(n)};return a}(c.SymBfw,c.NSSS)})(executionContext);
(function(c){(c.NSSS=c.NSSS||{}).wpsHelperUtils=function(d,b,a){var c=b.Rating,f=d.utils.isNil,l=a.uiConstants.BLOCKPAGE,e=a.constants,h={toolbarStatus:function(a){var b={};switch(a){case c.SITE_RATING.SW_UNTRUSTED_TRANSACTION_STATE:b.statusImage=e.CAUTION_IMAGE;b.statusString="Unsafe to Shop";break;case c.SITE_RATING.SW_KNOWN_PHISHING_STATE:case c.SITE_RATING.SW_SUSPECTED_PHISHING_STATE:case c.SITE_RATING.SW_KNOWN_MALICIOUS_STATE:case c.SITE_RATING.SW_PAGE_BAD_UNTRUSTED_TRANSACTION_STATE:case c.SITE_RATING.SW_ERROR_STATE:b.statusImage=
e.WARNING_IMAGE;b.statusString="Warning";break;case c.SITE_RATING.SW_NEUTRAL_STATE:b.statusImage=e.UNTESTED_IMAGE;b.statusString="Untested";break;case c.SITE_RATING.SW_CAUTION_MALICIOUS_STATE:b.statusImage=e.CAUTION_IMAGE;b.statusString="Caution";break;case c.SITE_RATING.SW_PENDING_STATE:b.statusImage=e.UNTESTED_IMAGE;b.statusString="Monitoring";break;case c.SITE_RATING.SW_TRUSTED_STATE:case c.SITE_RATING.SW_TRUSTED_TRANSACTION_STATE:case c.SITE_RATING.SW_NORTON_CERTIFIED:b.statusImage=e.SAFE_IMAGE;
b.statusString="Safe";break;case c.SITE_RATING.SW_DISABLED_STATE:b.statusImage=e.UNTESTED_IMAGE;b.statusString="Safe Web is off";break;default:b.statusImage=e.UNTESTED_IMAGE,b.statusString="Page not analyzed"}return b},createRedirectURL:function(a,b,d){a=h.blockPageType(a);if(!f(a))return l.HTML+"?originalURL="+b+"&reportURL="+d+"/&blockPageType="+a},blockPageType:function(a){switch(a){case c.SITE_RATING.SW_ERROR_STATE:case c.SITE_RATING.SW_KNOWN_PHISHING_STATE:var b=l.TYPE.KNOWNBAD;break;case c.SITE_RATING.SW_SUSPECTED_PHISHING_STATE:b=
l.TYPE.SUSPECTEDBAD;break;case c.SITE_RATING.SW_KNOWN_MALICIOUS_STATE:b=l.TYPE.MALICIOUS;break;case c.SITE_RATING.SW_PAGE_BAD_UNTRUSTED_TRANSACTION_STATE:b=l.TYPE.MALICIOUSSHOP}return b},getAnnotationStatusImage:function(a){switch(a){case c.SITE_RATING.SW_TRUSTED_STATE:case c.SITE_RATING.SW_TRUSTED_TRANSACTION_STATE:case c.SITE_RATING.SW_NORTON_CERTIFIED:a="sb_safeAnnotation.svg";break;case c.SITE_RATING.SW_KNOWN_MALICIOUS_STATE:a="sb_unsafeAnnotation.svg";break;case c.SITE_RATING.SW_CAUTION_MALICIOUS_STATE:a=
"sb_webnuisanceAnnotation.svg";break;case c.SITE_RATING.SW_PAGE_BAD_UNTRUSTED_TRANSACTION_STATE:a="sb_unsafeShoppagebadAnnotation.png";break;case c.SITE_RATING.SW_UNTRUSTED_TRANSACTION_STATE:a="sb_unsafeShopAnnotation.png";break;default:a="sb_unknownAnnotation.svg"}return a},getSearchTextForAnnotationURL:function(a){var b;"nortonsafe.search.ask.com"===(new URI(a)).hostname()&&(b=h.getQueryString("q",a));return b},getQueryString:function(a,b){b=URI(b).query(!0);return f(b[a])?null:b[a]},flavorizeFullReportUrl:function(b){if(f(b))return null;
if(!1===a.helperUtils.getFeatureFlavorization().showNortonLinks){var d=a.globalSettings.getPUID();b+="&siteName="+d+"&pid="+d}return b}};return h}(c.SymBfw,c.SafeWeb,c.NSSS)})(executionContext);
(function(c){c.NSSS.Rating=function(d,b,a){var c=d.utils.isNil,f=d.utils.isntNil,l=d.utils.isFunction,e=a.constants,h=b.constants.RATING_TYPE,m=a.wpsHelperUtils,g=b.Rating;b=function(){this._wcidCheckURLResult=this._wcidHeuristicsResult=this._safeWebResult=null;this._wcidCheckWaitingCount=0;this._isScamInsight=this._reloadPage=this._isHeuristicsFalseNegative=!1};b.prototype.getRating=function(){if(c(this._safeWebResult)&&c(this._wcidHeuristicsResult)&&c(this._wcidCheckURLResult))return null;var a=
this._getOverallPageRating(),b=null,e=null;f(this._safeWebResult)?(b=this._safeWebResult.fullURL,e=m.flavorizeFullReportUrl(this._safeWebResult.getFullReportURL())):f(this._wcidHeuristicsResult)&&(b=this._wcidHeuristicsResult.fullURL);var g={},h=m.toolbarStatus(a);g.siteStatus=h.statusString;g.siteIcon=h.statusImage;g.siteRating=a;g.url=b;g.redirectPage=m.createRedirectURL(a,b,e);g.computerThreatAttributes=0;g.identityThreatAttributes=0;g.annoyanceFactorAttributes=0;g.shoppingRiskAttributes=0;g.phishingThreatAttributes=
0;f(this._safeWebResult)&&(g.fullReportURL=e,g.searchText=m.getSearchTextForAnnotationURL(this._safeWebResult.fullURL),g.computerThreatAttributes=this._safeWebResult.computerThreats,g.identityThreatAttributes=this._safeWebResult.identityThreats,g.annoyanceFactorAttributes=this._safeWebResult.annoyanceFactors,g.shoppingRiskAttributes=this._safeWebResult.shoppingRisks,g.phishingThreatAttributes=this._safeWebResult.phishingThreats);c(g.redirectPage)&&!0===this._isScamInsight&&(g.scamInsightBlockPage=
d.extensionAdapter.getExtensionURL("/content/ui/scam-insight-block-page.html"));return g};b.prototype.reloadPage=function(a){if(this._reloadPage){this._reloadPage=!1;var b=this;setTimeout(function(){c(b._safeWebResult)?a(!0):b._getSiteRatingPriority(b._safeWebResult.siteRating)<=b._getSiteRatingPriority(g.SITE_RATING.SW_CAUTION_MALICIOUS_STATE)?a(!0):a(!1)},500)}else a(!1)};b.prototype.setRating=function(b,d){switch(d){case h.SAFEWEB:if(!1===a.webProtectionPolicy.isEnabled(d))break;this._safeWebResult=
b;break;case h.WCID_HEURISTICS:if(!1===a.webProtectionPolicy.isEnabled(d))break;if(!1===e.IS_WCID_HEURISTICS_LOW_PRIORITY){d=this._getSiteRatingPriority(g.SITE_RATING.SW_SUSPECTED_PHISHING_STATE);b.isCheckRequestNeed&&this._getSiteRatingPriority(b.siteRating)>=d&&++this._wcidCheckWaitingCount;if(this._isHeuristicsFalseNegative)break;if(f(this._wcidHeuristicsResult)&&(d=this._wcidHeuristicsResult.siteRating,this._getSiteRatingPriority(d)>this._getSiteRatingPriority(b.siteRating)))break}this._wcidHeuristicsResult=
b;break;case h.WCID_CHECK_URL:if(!1===a.webProtectionPolicy.isEnabled(d))break;if(f(this._wcidCheckURLResult)){d=this._wcidCheckURLResult.siteRating;var c=this._getSiteRatingPriority(b.siteRating);this._getSiteRatingPriority(d)<c&&(this._wcidCheckURLResult=b)}else this._wcidCheckURLResult=b;this._getSiteRatingPriority(this._wcidCheckURLResult.siteRating)>=this._getSiteRatingPriority(g.SITE_RATING.SW_SUSPECTED_PHISHING_STATE)&&f(this._timerIdForWCIDResponse)&&clearTimeout(this._timerIdForWCIDResponse);
if(e.IS_WCID_HEURISTICS_LOW_PRIORITY)break;--this._wcidCheckWaitingCount;0>=this._wcidCheckWaitingCount&&!1===this._isHeuristicsFalseNegative&&(b=this._getSiteRatingPriority(this._wcidCheckURLResult.siteRating),d=this._getSiteRatingPriority(g.SITE_RATING.SW_TRUSTED_STATE),c=this._getSiteRatingPriority(g.SITE_RATING.SW_CAUTION_MALICIOUS_STATE),b>=d&&b<=c&&(this._reloadPage=this._isHeuristicsFalseNegative=!0));break;case h.SCAM_INSIGHT:this._isScamInsight=!0}};b.prototype._getSiteRatingPriority=function(a){var b=
{};b[g.SITE_RATING.SW_INVALID_STATE]=1;b[g.SITE_RATING.SW_NEUTRAL_STATE]=1;b[g.SITE_RATING.SW_TRUSTED_STATE]=2;b[g.SITE_RATING.SW_TRUSTED_TRANSACTION_STATE]=2;b[g.SITE_RATING.SW_NORTON_CERTIFIED]=2;b[g.SITE_RATING.SW_UNTRUSTED_TRANSACTION_STATE]=3;b[g.SITE_RATING.SW_CAUTION_MALICIOUS_STATE]=4;b[g.SITE_RATING.SW_ERROR_STATE]=5;b[g.SITE_RATING.SW_SUSPECTED_PHISHING_STATE]=6;b[g.SITE_RATING.SW_PAGE_BAD_UNTRUSTED_TRANSACTION_STATE]=7;b[g.SITE_RATING.SW_KNOWN_MALICIOUS_STATE]=7;b[g.SITE_RATING.SW_KNOWN_PHISHING_STATE]=
8;a=b[a];return c(a)?-1:a};b.prototype._getOverallPageRating=function(){var a=null;f(this._safeWebResult)&&(a=this._safeWebResult.siteRating);var b=this._getWCIDRating();return c(b)?a:c(this._safeWebResult)||this._getSiteRatingPriority(b)>this._getSiteRatingPriority(a)?b:a};b.prototype._getWCIDRating=function(){if(e.IS_WCID_HEURISTICS_LOW_PRIORITY)return f(this._wcidCheckURLResult)?this._wcidCheckURLResult.siteRating:null;if(c(this._wcidHeuristicsResult))return null;var a=this._wcidHeuristicsResult.siteRating;
if(f(this._wcidCheckURLResult)&&(0>=this._wcidCheckWaitingCount||this._isHeuristicsFalseNegative)){var b=this._getSiteRatingPriority(this._wcidCheckURLResult.siteRating),d=this._getSiteRatingPriority(g.SITE_RATING.SW_TRUSTED_STATE);b>=d&&(a=this._wcidCheckURLResult.siteRating)}return a};b.prototype.processScamResultPostWCIDAnalysis=function(a){l(a)&&(this._timerIdForWCIDResponse=setTimeout(a,e.WCID_ANALYSIS_WAIT_TIME))};return b}(c.SymBfw,c.SafeWeb,c.NSSS)})(executionContext);
(function(c){c.NSSS.webProtectionPolicy=function(d){var b=d.settings,a=d.utils.isNil,c=d.logger,f=NSSS.constants.webProtectionPolicy,l=SafeWeb.constants.RATING_TYPE,e={_policyContainer:null,initialize:function(){e._policyContainer=b.loadSettingsContainer(f.WEB_PROTECTION_POLICY_CONTAINER,!1);e._setDefaultStatus()},_setDefaultStatus:function(){e._policyContainer.setObject(f.SAFEWEB_STATUS,!0);e._policyContainer.setObject(f.WCID_HEURISTICS_STATUS,!0);e._policyContainer.setObject(f.WCID_CHECK_URL_STATUS,
!0)},setSafeWebStatus:function(b){if(a(e._policyContainer))throw Error("Policy Settings not initialized");e._policyContainer.setObject(f.SAFEWEB_STATUS,b)},setWcidHeuristicsStatus:function(b){if(a(e._policyContainer))throw Error("Policy Settings not initialized");e._policyContainer.setObject(f.WCID_HEURISTICS_STATUS,b)},setWcidCheckUrlStatus:function(b){if(a(e._policyContainer))throw Error("Policy Settings not initialized");e._policyContainer.setObject(f.WCID_CHECK_URL_STATUS,b)},isEnabled:function(b){if(a(e._policyContainer))return c.error("Policy Settings not initialized"),
!0;switch(b){case l.SAFEWEB:return e._policyContainer.getObject(f.SAFEWEB_STATUS);case l.WCID_HEURISTICS:return e._policyContainer.getObject(f.WCID_HEURISTICS_STATUS);case l.WCID_CHECK_URL:return e._policyContainer.getObject(f.WCID_CHECK_URL_STATUS)}return!0}};return e}(c.SymBfw)})(executionContext);
(function(c){(c.NSSS=c.NSSS||{}).helperUtils=function(d,b){var a={},c=b.uiHelper,f=d.settings,l=d.logger,e=d.utils.isNil,h=d.utils.isntNil,m=d.utils.isString,g=b.constants,n=b.globalSettings,u=b.nfmEvents,x=b.telemetryWrapper,r=d.extensionAdapter,y=d.performanceReporterFactory,A=b.wpsHelperUtils;a.getTabIDForSessionID=function(a){if(e(a))throw Error("SessionID cannot be null");return f.loadSettingsContainer(a).getObject(g.TABID)};a.getSessionIDForTabID=function(a){var b=null;for(b in f.containers){var d=
f.loadSettingsContainer(b);if(a===d.getObject(g.TABID))return b}return null};a.tabURL=function(a){a=a.url;if(e(a)||""===a)a=g.ABOUT_BLANK;return a};a.updateButton=function(d,n,m){m=void 0===m?!1:m;r.getTab(n,function(q){r.getLastError();e(q)?l.log("No tab exists with tabID: "+n):(q=r.getWindowIDForTab(q),r.getActiveTab(function(k){var w=r.getLastError();if(h(w))l.log("Tab is not available"),l.log(w);else if(e(k))l.log("there are no active tabs at the moment");else if(w=r.getTabID(k),n===w){a.updateActionButton(d,
w,k.url);var B=r.getExtensionURL("");if(!m||-1===k.url.indexOf(B)){var q=c.toolbarStatusForSessionID(d),v=f.loadSettingsContainer(d),t=v.getObject(u.PAGE_ANALYZED);h(t)&&t._safeWebResult&&t._wcidHeuristicsResult&&y.reportStopForComponent(g.performanceReporter.NSSS,b.main.pageAnalysisTime);!h(q)||e(q.redirectPage)&&e(q.scamInsightBlockPage)||(v=v.getObject(b.constants.SHOULD_BLOCK_KEY),h(v)&&!1===v)||k.url!==q.url&&-1===k.url.indexOf(B)||(B=h(q.redirectPage)?r.getExtensionURL("content/ui/"+q.redirectPage):
q.scamInsightBlockPage,v=A.blockPageType(q.siteRating),B!==k.url&&(-1!==B.indexOf(g.BLOCK_PAGE_PATH)&&-1!==k.url.indexOf(g.SCAM_INSIGHT_BLOCK_PAGE_PATH)&&(b.telemetryWrapper.sendWCIDBlockPageDisplayAfterScamBlockPageEvent(),l.debug("WCID block page is displayed after scam insight block page")),r.updateTabUrl(w,B),-1===B.indexOf(g.SCAM_INSIGHT_BLOCK_PAGE_PATH)&&b.telemetryWrapper.sendBlockPageTelemetry(q.url,v,!1)))}}},q))})};a.updateActionButton=function(a,b,d){a=c.uiStatusForSessionID(a,d);a=r.getExtensionURL("content/images/")+
a.regularIcon;r.setBrowserIcon({path:a,tabId:b})};a.handleUIEvents=function(f,n){if(f===c.FULL_REPORT_EVENTID)r.getActiveTab(function(b){var d=r.getLastError();h(d)?(l.log("Tab is not available"),l.log(d)):(b=a.getSessionIDForTabID(r.getTabID(b)),b=c.toolbarStatusForSessionID(b),e(b)||r.createTab(b.fullReportURL))});else if(f===c.SETTINGS_CLICKED_EVENTID){var q=d.extensionAdapter.getExtensionURL(g.SETTINGS_PAGE);r.getTabsWithURL(q,function(a){h(r.getLastError())||(h(a[0])?(r.activateTab(r.getTabID(a[0])),
r.focusWindow(r.getWindowIDForTab(a[0]))):d.extensionAdapter.createTab(q))})}else f===c.REPORTSITE_EVENTID?r.getActiveTab(function(d){var k=r.getLastError();if(h(k))l.log("Tab is not available"),l.log(k);else{k=a.getSessionIDForTabID(r.getTabID(d));var e=c.uiStatusForSessionID(k,d.url);d=e.siteRating;e=e.uiStatus.sitename;c.setShowReportSiteForSessionID(k,!1);b.webProtection.reportURLToSymantecServer(e,d)}}):f!==c.SEARCH_EVENTID||e(n)||(f=a.getSearchURL(b.ocodeMgr.getUISearchOCode(),n),r.createTab(f,
function(a){}),b.telemetryWrapper.sendUISearchEvent())};a.getFeatureFlavorization=function(){var a="false"===g.SEARCHBOX_VISIBLE?!1:!0,d=!0,c=b.partnerConstants,e=n.getPartnerId(),k=n.getPUID(),f=n.getLayoutType();e=c.searchboxExclusionList[e];h(e)&&-1!==e.puid.indexOf(k)&&(a=!1);h(f)&&-1!==c.excludeNortonLinks.indexOf(f)&&(d=!1);return{showSafeWebSearchbox:a,showNortonLinks:d}};a.getQueryTemplate=function(a){var d=n.getParamsString(),c=b.URLSearchParams;if(!e(c)){d=new c(d);c=n.getInstallDate();
var f=n.getCGuid(),k=n.getPartnerId(),w=n.getProduct(),B=n.getVersion();d.append(g.URL_PARAMS_KEY.OCODE,a);d.append(g.URL_PARAMS_KEY.PRT,w);d.append(g.URL_PARAMS_KEY.VERSION,B);d.append(g.URL_PARAMS_KEY.TPR,g.TPR);d.append(g.PARTNERIDKEY,k);d.append(g.URL_PARAMS_KEY.CGUID,f);d.append(g.URL_PARAMS_KEY.DATE_OF_INSTALL,c);a=n.getTrackId();h(a)&&d.append(g.URL_PARAMS_KEY.TRACK_ID,a);return d.toString()}};a.getSearchURLTemplate=function(b){return"https://nortonsafe.search.ask.com/web?q=$$TEMPLATE$$&"+
a.getQueryTemplate(b)};a.getSearchURL=function(b,d){return a.getSearchURLTemplate(b).replace("$$TEMPLATE$$",encodeURIComponent(d))};a.setFlavor=function(a,d){if(!n.getFlavorized()){var c=d.enableHomePage;d=d.enableSafeSearch;c=e(c)?!1:c;d=e(d)?!1:d;a=URI(a.toLowerCase());var f=a._parts.query,k=b.URLSearchParams;"undefined"!==typeof URLSearchParams&&(k=URLSearchParams);f=new k(f);k=f.get(g.URL_PARAMS_KEY.PARTNERID);h(k)&&n.setPartnerId(k);f.delete(g.URL_PARAMS_KEY.PARTNERID);k=f.get(g.URL_PARAMS_KEY.CGUID);
h(k)&&(n.setCGuid(k),f.delete(g.URL_PARAMS_KEY.CGUID));k=f.get(g.URL_PARAMS_KEY.DATE_OF_INSTALL);h(k)&&(n.setInstallDate(k),f.delete(g.URL_PARAMS_KEY.DATE_OF_INSTALL));k=f.get(g.URL_PARAMS_KEY.PARTNER_UNIT_ID);h(k)&&(n.setPUID(k),f.delete(g.URL_PARAMS_KEY.PARTNER_UNIT_ID));k=f.get(g.URL_PARAMS_KEY.PRODUCT_NAME);h(k)&&(n.setProduct(k),f.delete(g.URL_PARAMS_KEY.PRODUCT_NAME));k=f.get(g.URL_PARAMS_KEY.VERSION);h(k)&&(n.setVersion(k),f.delete(g.URL_PARAMS_KEY.VERSION));k=f.get(g.URL_PARAMS_KEY.LAYOUT_TYPE);
h(k)&&(n.setLayoutType(k),f.delete(g.URL_PARAMS_KEY.LAYOUT_TYPE));k=f.get(g.URL_PARAMS_KEY.TRACK_ID);h(k)&&(n.setTrackID(k),f.delete(g.URL_PARAMS_KEY.TRACK_ID));k=a.subdomain();if(e(k)||0===k.length||"www"===k)a=a.domain(),k=a.substring(0,a.indexOf("."));(h(k)||0!==k.length)&&n.setCampaignMedium(k);c&&n.setDefaultHomepage(c);d&&n.setDefaultSearch(d);f=f.toString();n.setParamsString(f);x.sendSearchStatus(d,c);n.setFlavorized(!0)}};a.getQueryString=function(a,b){b=URI(b.toLowerCase()).query(!0);return e(b[a])?
null:b[a]};a.isLandingPageURL=function(a){if(e(a)||!m(a))return!1;a=new URI(a);return"https"!==a.protocol()||a.domain()!==b.constants.ONBOARDING_PORTAL_DOMAIN||!1===b.constants.ONBOARDING_PORTAL_SUBDOMAIN.includes(a.subdomain())?!1:!0};a.isURLWhitelisted=function(a){if(e(a)||""===a)return!0;for(var b=0;b<g.NATIVE_TAB_PREFIX.length;b++)if(a.startsWith(g.NATIVE_TAB_PREFIX[b]))return!0};return a}(c.SymBfw,c.NSSS)})(executionContext);
(function(c){(c.NSSS=c.NSSS||{}).webProtection=function(d,b,a,c){var f={},l=a.nfmEvents,e=d.utils.isNil,h=d.utils.isFunction,m=d.utils.isInteger,g=d.logger,n=a.wpsHelperUtils,u=a.helperUtils,p=a.Rating,r=d.settings,y=b.constants,A=b.constants.RATING_TYPE,q=d.extensionAdapter,v=d.utils,D=d.performanceReporterFactory,E=a.constants;f._registeredEvents={};f.registerEventCallback=function(a,b){if(e(a))throw Error("EventID cannot be null or undefined");if(!1===h(b))throw Error("Callback function cannot be null.");
this._registeredEvents[a]=b};f.handleScamExitSite=function(a){if(e(a))throw Error("Invalid tab ID");f._submitSIPIIData(y.PII_FLAGS.EXIT_SITE,a);q.updateTabUrl(a,"about:blank",function(a){})};f.handleScamContinueSite=function(a){if(v.isNil(b))throw Error("Safeweb is not defined");if(v.isNil(a))throw Error("Invalid tab ID");var d=f._getSIBlockPageData(a);e(d)||(f._submitSIPIIData(y.PII_FLAGS.CONTINUE_TO_SITE,a),d=d.url,b.scamInsightUtility.addToViewAnywayCache(d),q.updateTabUrl(a,d,function(a){}))};
f.handleSIBlockPageInit=function(a,b,c){if(!h(a))throw Error("sendResponse should be a valid function");if(d.utils.isEmptyObject(b)||e(b.strings))throw Error("scamInsightBlockPage is not a valid Object");if(e(c))throw Error("Invalid tab ID");c=f._getSIBlockPageData(c);e(c)||(b.ageScore=c.ageScore,b.prevalenceScore=c.prevalenceScore,b.url=c.url,a(b))};f._submitSIPIIData=function(a,d){if(v.isNil(b)||v.isNil(b.scamInsightMgr))return null;b.scamInsightMgr.sendPIISubmission(a,d)};f._getSIBlockPageData=
function(a){return v.isNil(b)||v.isNil(b.scamInsightMgr)?null:b.scamInsightMgr.getBlockPageData(a)};f.handleWCIDEvent=function(b,d,c){if(e(b))throw Error("rating cannot be null");if(e(d))throw Error("tabID cannot be null");if(e(c))throw Error("type cannot be null");var k=a.helperUtils.getSessionIDForTabID(d);e(k)&&(k=a.main.createSessionForTab(d));d=r.loadSettingsContainer(k).getObject(l.PAGE_ANALYZED);e(d)&&(d=new p);d.setRating(b,c);f.handleResponse(k,l.PAGE_ANALYZED,d)};f.handleEvent=function(a,
b,d,c){c=void 0===c?null:c;if(e(a))throw Error("Session ID cannot be null");if(e(b))throw Error("Event cannot be null");if(e(d))throw Error("eventData cannot be null");b===l.FRAME_BEGIN||b===l.DOWNLOAD_EVENT?f.getProtectionRatingForURL(a,d,b):b===l.SEARCH_URLS&&f.getProtectionRatingsForURLs(a,d,c)};f.getProtectionRatingForURL=function(a,d,g){var k="SafeWeb lookup time for block page: "+Date.now();if(e(d))throw Error("URL cannot be null");var w=function(d){f.handleShastaPageStatus(a,d,g);if(y.IS_SCAM_INSIGHT_ENABLED){var c=
u.getTabIDForSessionID(a);b.scamInsightMgr.setWrsResponse(c,d)}};D.reportStartForComponent(E.performanceReporter.NSSS,k);b.manager.getRatingForURL(d,function(a){D.reportStopForComponent(E.performanceReporter.NSSS,k);e(a)||c.manager.handleShastaResultAndPerformWCIDLookup(a,w)})};f.handleShastaPageStatus=function(a,b,d){if(!e(b)){var c=r.loadSettingsContainer(a),k=c.getObject(l.PAGE_ANALYZED);e(k)&&(k=new p);k.setRating(b,A.SAFEWEB);c.setObject(l.PAGE_ANALYZED,k);d===l.FRAME_BEGIN?f.handleResponse(a,
l.PAGE_ANALYZED,k):d===l.DOWNLOAD_EVENT&&f.handleResponse(a,l.DOWNLOAD_URL_ANALYZED,k)}};f.getProtectionRatingsForURLs=function(a,d,c){c=void 0===c?null:c;if(e(d))throw Error("urlArray cannot be null");b.manager.getRatingsForURLs(d,function(b){f.handleAnnotationResult(a,b,c)})};f.handleAnnotationResult=function(a,b,d){d=void 0===d?null:d;var c={annotationResults:[],fullReportURLArray:[]},k;for(k in b){var g=b[k];if(e(g))c.annotationResults[k]=null,c.fullReportURLArray[k]=null;else{var h={},w=n.toolbarStatus(g.siteRating);
h.siteStatus=w.statusString;h.siteIcon=w.statusImage;h.url=g.fullURL;h.computerThreatAttributes=g.computerThreats;h.identityThreatAttributes=g.identityThreats;h.annoyanceFactorAttributes=g.annoyanceFactors;h.shoppingRiskAttributes=g.shoppingRisks;h.phishingThreatAttributes=g.phishingThreats;h.fullReportURL=n.flavorizeFullReportUrl(g.getFullReportURL());h.srcImage=n.getAnnotationStatusImage(g.siteRating);h.normalizedURL=g.normalizedURL;c.annotationResults[k]=h;c.frameId=d;c.fullReportURLArray[k]=h.fullReportURL}}f.handleResponse(a,
l.SEARCH_URLS_ANALYZED,c)};f.handleResponse=function(a,b,d){if(e(a))throw Error("Session ID cannot be null");if(e(d))throw g.log("response cannot be null for eventID:"+b),Error("response cannot be null");var c=this._registeredEvents[b];e(c)?g.error("Could not find callback method for eventID:"+b):setTimeout(function(){c(a,b,d)},1)};f.reportURLToSymantecServer=function(a,b){c.manager.reportURLToSymantec(a,b,function(a,b){})};f.handleScamInsightEvent=function(b){if(m(b)){var d=a.helperUtils.getSessionIDForTabID(b);
if(!e(d)){b=r.loadSettingsContainer(d);var c=b.getObject(l.PAGE_ANALYZED);e(c)||(c.processScamResultPostWCIDAnalysis(function(){c.setRating({},A.SCAM_INSIGHT);f.handleResponse(d,l.PAGE_ANALYZED,c)}),b.setObject(l.PAGE_ANALYZED,c))}}};return f}(c.SymBfw,c.SafeWeb,c.NSSS,c.WCID)})(executionContext);
(function(c){c.NSSS.URLSearchParams=function(d){d=function(b){this._queryDict=URI.parseQuery(b)};d.prototype.get=function(b){return this._queryDict[b]};d.prototype.append=function(b,a){this._queryDict[b]=a};d.prototype.delete=function(b){delete this._queryDict[b]};d.prototype.toString=function(){var b="",a;for(a in this._queryDict)b+=a+"="+this._queryDict[a]+"&";return b.replace(/&$/,"")};return d}(c.SymBfw)})(executionContext);
(function(c){c.NSSS.ocodeMgr=function(d,b){var a={},c=b.globalSettings,f=d.logger;a._lifeLockOCodes={DS:"APN12312",HP:"APN12313",UI_SEARCH:"APN12311"};a._lifeLockTestPartnerID="tiacll";a.getDSOCode=function(){return a._getOCode("DS")};a.getHPOCode=function(){return a._getOCode("HP")};a.getUISearchOCode=function(){return a._getOCode("UI_SEARCH")};a._getOCode=function(d){var e=c.getPartnerId()===a._lifeLockTestPartnerID;switch(d){case "DS":d=e?a._lifeLockOCodes.DS:b.constants.DS_OCODE;break;case "HP":d=
e?a._lifeLockOCodes.HP:b.constants.DHP_OCODE;break;case "UI_SEARCH":d=e?a._lifeLockOCodes.UI_SEARCH:b.constants.SEARCH_OCODE;break;default:throw f.error("Default ocode requested. Likely a bug"),Error("There is no default OCode. Likely a bug");}return d};return a}(c.SymBfw,c.NSSS)})(executionContext);
(function(c){(c.NSSS=c.NSSS||{}).main=function(d,b){var a={},c=!1,f=b.uiConstants.BLOCKPAGE.TYPE,l=d.logger,e=d.utils,h=d.settings,m=b.helperUtils,g=b.uiHelper,n=b.nfmEvents,u=d.utils.isNil,x=d.utils.isntNil,r=b.constants,y=b.webProtection,A=d.localizer,q=d.extensionAdapter,v=b.uiConstants.MESSAGES,D=b.uiConstants.SCAM_INSIGHT_BLOCK_PAGE.strings,E=d.performanceReporterFactory;a.popoverWindowStrings=function(){return g.popoverWindowStrings()};a.handleUIEvents=function(a,b){return m.handleUIEvents(a,
b)};a.searchURLsAnalyzedCallback=function(a,b,d){var c=h.loadSettingsContainer(a);if(e.isEmptyObject(c.collection))l.log("Tab has been closed by the time search annotation results came back:"+a);else{var f=d.annotationResults;c.setObject(b,d.fullReportURLArray);a=m.getTabIDForSessionID(a);var k={name:"annotate-urls",annotationResults:f,frameId:d.frameId};q.getTab(a,function(a){q.sendMessageToTab(a,k)})}};a.flavorizeAndReloadOnBoarding=function(){if("Safari"===d.globals.BROWSER||"Edge"===d.globals.BROWSER)b.globalSettings.getFlavorized()||
q.getAllTabs(function(a){a.forEach(function(a){var b=a.url;u(b)||-1===b.indexOf(r.ONBOARDING_URL)||(b=q.getTabID(a),q.updateTabUrl(b,a.url),q.activateTab(b),m.setFlavor(a.url,{}))})})};a.performCollectURLs=function(a){a=m.getTabIDForSessionID(a);q.getTab(a,function(a){var b=q.getLastError();x(b)?(l.log("Tab is not available"),l.log(b)):u(a)?l.log("Tab is not available so come back when tabReplaced has occurred"):q.sendMessageToTab(a,{name:"collectURLs"})})};a.handleTelemetryOptOut=function(){if(!d.telemetrySettings.isTelemetryEnabled()){var c=
d.telemetrySettings.getLastOfferDate(),e=!1;u(c)?e=!0:"Firefox"!==d.globals.BROWSER&&new Date-c>b.constants.telemetryOptOut.REOFFER_TIME_WINDOW&&(e=!0);e&&a._showTelemetryNoitifcation(b.constants.telemetryOptOut.NOTIFICATION_LEEWAY+1E3*Math.random())}};a._showTelemetryNoitifcation=function(c){setTimeout(function(){if(!d.telemetrySettings.isTelemetryEnabled()){var c=A.getLocalizedStringWithFormat("Thank you for using {0}! Share usage and error data anonymously with Norton to help make our products even better.",
[r.PRODUCT_NAME]),e=A.getLocalizedString("OK"),f=A.getLocalizedString("Learn More"),k=A.getLocalizedString("No, thanks");c=new d.QuestionNotification(c,{},e,function(a){d.telemetrySettings.setTelemetryEnabled(!0);d.telemetrySettings.setUserRespondedInOptOutPage(!0)},"content/images/"+b.constants.DEFAULT_INFO_ICON);c.addSecondaryLink(f,function(b){d.extensionAdapter.createTab("https://www.symantec.com/privacy/product-privacy-statements/norton-browser-extensions-privacy-notice");a._showTelemetryNoitifcation(50)});
c.addThirdButton(k,function(a){d.telemetrySettings.setTelemetryEnabled(!1);d.telemetrySettings.setUserRespondedInOptOutPage(!0)});c.addCloseButtonAction(function(a){d.telemetrySettings.setTelemetryEnabled(!1);d.telemetrySettings.setUserRespondedInOptOutPage(!0)});d.telemetrySettings.setLastOfferDate(new Date);d.notificationCenter.addNotification(c)}},c)};a.handleOnUpdated=function(c,e,f){l.log("Handle on updated:"+c);"Chrome"===d.globals.BROWSER&&chrome.runtime.getPlatformInfo(function(a){"win"===
a.os&&(a=b.globalSettings.getValue(r.IS_HP_FIRST_LAUNCH),(a=u(a)?!0:a)&&e.url&&(-1!=e.url.indexOf("chrome://extensions/?id="+b.constants.HP_ID)||-1!=e.url.indexOf("https://search.norton.com/?"))&&(l.log("HP First launch detected..."),a=!1,b.globalSettings.setValue(r.IS_HP_FIRST_LAUNCH,!1),q.getTab(c,function(a){q.sendMessageToTab(a,{ShowGoogleAssist:"HP"},function(a){l.log(a.status)})})))});var k=m.getSessionIDForTabID(c);if(m.isURLWhitelisted(f.url))m.updateActionButton(k,c,f.url);else{var h=g.toolbarStatusForSessionID(k);
if(!u(h)){var n=q.getExtensionURL("");-1!==f.url.indexOf(n)&&u(h.redirectPage)&&u(h.scamInsightBlockPage)&&a.deleteSessionForTab(c);m.updateActionButton(k,c,h.url)}}};a.handleMessage=function(e,l,p){var k=q.getTabID(p),w=m.getSessionIDForTabID(k);u(w)&&(w=a.createSessionForTab(k));var t=e.message,B=e.name;e=h.loadSettingsContainer(w);var A=null,z=null;switch(B){case "GetisDSPFirstLaunch":-1!=p.url.indexOf("o="+b.ocodeMgr.getDSOCode())&&(c=b.globalSettings.getValue(r.IS_DSP_FIRST_LAUNCH),c=u(c)?!0:
c,l({isDSPFirstLaunch:c}),c&&(b.globalSettings.setValue(r.IS_DSP_FIRST_LAUNCH,!1),c=!1));break;case v.BEFORE_UNLOAD_EVENT:z=e.getObject("queueCollectUrls");if(u(z))break;for(var G in z)if(z[G].tabID===k){z.splice(G,1);e.setObject("queueCollectUrls",z);break}break;case v.DOMEVENT:t.eventID===n.FRAME_BEGIN&&(a.pageAnalysisTime="Overall time taken for page analysis: "+Date.now(),E.reportStartForComponent(r.performanceReporter.NSSS,a.pageAnalysisTime),a._deleteOldSession(w,k,t.url)&&(w=a.createSessionForTab(k),
e=h.loadSettingsContainer(w)));y.handleEvent(w,t.eventID,t.url);t.isTop&&(k=t.hidden,x(k)&&e.setObject("hidden",k),e.setObject(t.eventID,!0),t.eventID===n.NAVIGATE_COMPLETE&&(A=e.getObject(n.PAGE_ANALYZED),u(A)||x(A.searchText)&&b.main.performCollectURLs(w)));break;case v.SHOW_ANNOTATION_POPUP:case v.CLOSE_ANNOATION_POPUP:q.sendMessageToTab(p,{name:B,data:t});break;case v.COLLECT_URL_RESPONSE:if(0===t.search_urls.length)break;var C=e.getObject("timeoutCollectUrls");C&&(window.clearTimeout(C),C=0);
t.tabID=k;z=e.getObject("queueCollectUrls");u(z)&&(z=[]);l=!1;for(var F in z)z[F].tabID===k&&(-1!==p.url.indexOf("https://nortonsafe.search.ask.com")?z[F].search_urls.length<t.search_urls.length&&(z[F]=t):z[F]=t,l=!0);l||z.push(t);e.setObject("queueCollectUrls",z);-1!==p.url.indexOf("https://nortonsafe.search.ask.com")?C=window.setTimeout(function(){for(var a in z){var b=z[a];y.handleEvent(w,b.eventID,b.search_urls)}C=0},200):(C=0,y.handleEvent(w,t.eventID,t.search_urls,t.frameId));e.setObject("timeoutCollectUrls",
C);break;case "collectURLs":if(u(e))break;A=e.getObject(n.PAGE_ANALYZED);if(u(A))break;x(A.searchText)&&b.main.performCollectURLs(w);break;case v.OPEN_FULLREPORT:k=t.index;k=e.getObject(n.SEARCH_URLS_ANALYZED)[k];q.createTab(k);break;case "flavor-retrieved":if(u(p.url))break;m.setFlavor(p.url,t);break;case v.BLOCKEDPAGE_SEARCH:d.utils.isString(t.searchText)&&(a.handleClose(k),t=m.getSearchURL(b.constants.BLOCKEDPAGE_SEARCH_OCODE,t.searchText),q.updateTabUrl(k,t),b.telemetryWrapper.sendBlockedPageSearchEvent());
break;case v.HANDLE_UI_EVENTS:a.handleUIEvents(t.eventID,t.eventData);break;case v.UPDATE_POPOVER_UI:return b.telemetryWrapper.sendShowPopupUIEvent(q.getExtensionURL("content/ui/popup.html")),b.chromeGlobal.updatePopoverUI(l),!0;case v.BLOCKEDPAGE_INIT:u(t.pageType)&&(t.pageType=f.MALICIOUS);k={};k.string=g.getBlockPageString(t.pageType);e=b.helperUtils.getFeatureFlavorization();k.showSafeWebSearchbox=e.showSafeWebSearchbox;k.showNortonLinks=e.showNortonLinks;k.pageType=t.pageType;t=g.uiStatusForSessionID(w,
p.url);x(t)&&(k.fullReportURL=t.fullReportURL);l(k);break;case "sendKeepAssistForDSPShownTelemetry":!0===b.chromeGlobal.THREE_IN_ONE_EXTENSION&&b.telemetryWrapper.sendKeepAssistShownEvent(b.telemetryWrapper.searchFeature.DEFAULT_SEARCH_PROVIDER);break;case "sendKeepAssistForDSPContinueBtnClickedTelemetry":!0===b.chromeGlobal.THREE_IN_ONE_EXTENSION&&b.telemetryWrapper.sendKeepAssistContinueButtonClickedEvent(b.telemetryWrapper.searchFeature.DEFAULT_SEARCH_PROVIDER);break;case "sendKeepAssistForHPShownTelemetry":!0===
b.chromeGlobal.THREE_IN_ONE_EXTENSION&&b.telemetryWrapper.sendKeepAssistShownEvent(b.telemetryWrapper.searchFeature.DEFAULT_HOMEPAGE);break;case "sendKeepAssistForHPContinueBtnClickedTelemetry":!0===b.chromeGlobal.THREE_IN_ONE_EXTENSION&&b.telemetryWrapper.sendKeepAssistContinueButtonClickedEvent(b.telemetryWrapper.searchFeature.DEFAULT_HOMEPAGE);break;case v.OPEN_DO_NOT_BLOCK_PAGE:l=t.url;t=t.blockPageType;e=h.loadSettingsContainer(w);e.setObject(b.constants.SHOULD_BLOCK_KEY,!1);q.updateTabUrl(k,
l,function(a){});b.telemetryWrapper.sendBlockPageTelemetry(l,t,!0);break;case v.SCAM_INSIGHT_BLOCKPAGE_INIT:t={};t.direction=d.localizer.getCurrentLanguageDirection();t.strings=d.localizer.getLocalizedStrings(D);y.handleSIBlockPageInit(l,t,k);b.telemetryWrapper.sendScamBlockPageVisitedEvent(t.url);break;case v.SCAM_EXIT_SITE:y.handleScamExitSite(k);break;case v.SCAM_CONTINUE_TO_SITE:y.handleScamContinueSite(k);e.setObject(b.constants.SHOULD_BLOCK_KEY,!1);b.telemetryWrapper.sendScamContinueToSiteEvent();
break;case v.SCAM_REPORT_ISSUE:b.telemetryWrapper.sendScamReportIssueEvent()}};a._deleteOldSession=function(b,c,e){var f=h.loadSettingsContainer(b);b=f.getObject(n.PAGE_ANALYZED);if(x(b))if(b=b.getRating(),e=new URI(e),b=new URI(b.url),e.hostname()===b.hostname()){if(e.hostname()===r.NORTONSAFE_HOSTNAME&&e.query()!==b.query())return a.deleteSessionForTab(c),!0;e=f.getObject(r.SHOULD_BLOCK_KEY);if(u(e)||!0===e)return!1;e=f.getObject(r.CONTINUE_SITE_LOADED_KEY);if(x(e)&&!0===e)return a.deleteSessionForTab(c),
!0;"Edge"===d.globals.BROWSER?setTimeout(function(){q.getTab(c,function(a){u(a)||a.url.includes("ms-appx-web")||f.setObject(r.CONTINUE_SITE_LOADED_KEY,!0)})},1E3):f.setObject(r.CONTINUE_SITE_LOADED_KEY,!0)}else return a.deleteSessionForTab(c),!0;return!1};a.pageAnalyzedCallback=function(a,d,c){var f=h.loadSettingsContainer(a);l.log(f);if(e.isEmptyObject(f.collection))l.log("Tab has been closed by the time page annotation results came back:"+a);else{l.log("Inside pageAnalyzedCallback");f.setObject(d,
c);var k=m.getTabIDForSessionID(a);c.reloadPage(function(a){a&&(a=c.getRating(),q.updateTabUrl(k,a.url),b.telemetryWrapper.sendWcidReloadPageEvent())});m.updateButton(a,k)}};a.createSessionForTab=function(a){var b=m.getSessionIDForTabID(a);if(x(b))return b;b=e.createNewGuid();h.loadSettingsContainer(b).setObject(r.TABID,a);return b};a.deleteSessionForTab=function(a){a=m.getSessionIDForTabID(a);u(a)?l.log("Tab has no sessionID associated with it. Seems like a bug"):h.deleteSettingsContainer(a)};a.handleTabReplaced=
function(b){var d=b.replacedTabId;h.deleteSettingsContainer(d);b=b.tabId;a.deleteSessionForTab(d);d=m.getSessionIDForTabID(b);var c=h.loadSettingsContainer(d);m.updateButton(d,b);e.isEmptyObject(c.collection)};a.handleActivate=function(a,b){a=a.tabId;l.log("Inside handleActivate");l.log(a);b=m.getSessionIDForTabID(a);u(b)?m.updateActionButton(b,a,""):m.updateButton(b,a,!0)};a.analyzeDownloadPage=function(a){"in_progress"===a.state&&y.handleEvent(a.id,n.DOWNLOAD_EVENT,a.url)};a.handleOmniSearchEvent=
function(a){a=m.getQueryString("q",a.url);a=m.getSearchURL(b.ocodeMgr.getDSOCode(),a);b.telemetryWrapper.sendDefaultSearchEvent();return{redirectUrl:a}};a.handleClose=function(b,d){a.deleteSessionForTab(b)};a.reloadOnboardingPageIfAvailable=function(){"Safari"!==d.globals.BROWSER&&"Edge"!==d.globals.BROWSER||q.getAllTabs(function(a){a.forEach(function(a){if(m.isLandingPageURL(a.url)){var b=q.getTabID(a);q.updateTabUrl(b,a.url,null);q.activateTab(b)}})})};a.injectWebCommunication=function(){q.getAllTabs(function(a){a.forEach(function(a){var c=
a.url;!1!==m.isLandingPageURL(c)&&(a=a&&a.id,"Chrome"===d.globals.BROWSER&&a&&chrome.tabs.executeScript(a,{file:"content/scripts/webCommunication.js"},function(){q.getTabsWithURL(b.constants.CHROME_STORE_URL+"*"+d.extensionAdapter.getExtensionId()+"*",function(a){(a=a&&a[0]&&a[0].id)&&q.closeTab(a)})}),c=(new URI(c)).query(!0),b.portalCguid=c[b.constants.URL_PARAMS_KEY.CGUID])})})};a.handleInstall=function(a){var c=a.reason,e=d.globals.BROWSER;"install"===c&&b.main.injectWebCommunication();b.init.ready().then(function(){var a=
b.telemetryWrapper;switch(c){case "install":("Edge"===e||"Safari"===e?b.main.flavorizeAndReloadOnBoarding:b.chromeGlobal.flavorizeExtension)();b.main.reloadOnboardingPageIfAvailable();a.sendExtensionInstall();break;case "update":a.sendExtensionUpdate()}},function(a){l.error(a)})};a.checkIfFirstInstall=function(){var a=b.globalSettings.getValue(b.constants.NSSS_INSTALLDATEKEY);d.utils.isNil(a)&&b.main.handleInstall({reason:"install"});b.globalSettings.getInstallDate()};return a}(c.SymBfw,c.NSSS)})(executionContext);
(function(c){c.NSSS.init=function(d,b,a,c,f,l){var e={},h=b.constants,m=d.utils.isntNil,g=d.utils.isNil;e.supported_languages={el:!0,en:!0,pt_br:!0,it:!0,ar:!0,cs:!0,es:!0,ru:!0,nl:!0,pt:!0,no:!0,nb:!0,tr:!0,ro:!0,pl:!0,fr:!0,zh_tw:!0,de:!0,da:!0,fi:!0,hu:!0,ja:!0,he:!0,zh_cn:!0,ko:!0,sv:!0};e.initializeLocalizer=function(){return new Promise(function(a,b){d.localizer.initialize(e.supported_languages,function(d,c){!0===d?a("localizer is ready"):b("localizer initialize failed: "+c)})})};e.getClientID=
function(){if(g(b.portalCguid))var a=b.globalSettings.getCGuid();else a=b.portalCguid.toLowerCase(),b.globalSettings.setCGuid(a);return a};e.initializeTelemetry=function(){return new Promise(function(a,b){var c=d.telemetryConstants;c={APPLICATION_NAME:h.PRODUCT_NAME+"_"+d.extensionAdapter.getExtensionId(),APPLICATION_VERSION:h.VERSION,CLIENT_ID:e.getClientID(),DATA_SOURCE:c.dataSource.BROWSER_EXTENSION,TRACKING_ID:h.TELEMETRY_TRACKING_ID,USER_LANGUAGE:navigator.language,ANONYMIZE_IP:1,GOOGLE_ANALYTICS_PROTOCOL_VERSION:1};
try{d.telemetry.init(c,function(c){!0===c?a("Telemetry initialized"):b("Failed to initialize telemetry")})}catch(r){b("Failed to initialize telemetry. "+r)}})};e.initializeGlobalSettings=function(){return new Promise(function(a,c){b.globalSettings.initialize(function(b){b?a("Global settings initialized"):c("Failed to initialize global settings")})})};e._initializeWebProtectionPolicy=function(){return new Promise(function(a,c){try{m(b.webProtectionPolicy)&&b.webProtectionPolicy.initialize(),a("Web Protection Policy initialized")}catch(x){c("Error initializing Web Protection Policy: "+
x.message)}})};e._initializeWCID=function(){return new Promise(function(c,d){try{m(a)&&m(a.manager)&&a.manager.initialize(b.webProtection.handleWCIDEvent),c("WCID initialized")}catch(x){d("Error initializing WCID: "+x.message)}})};e._initializeOCL=function(){return new Promise(function(a,b){try{g(l)||g(l.init)?a("OCL not needed"):l.init.ready().then(function(){l.session.initialize(["email"],"https://identitysafe.norton.com/nsss-login-interstitial.html","EXDXP5M0MS/safeweb.symantec.com/symantec");
a("OCL Initialized")}).catch(function(){b("OCL initilization failed")})}catch(x){b("Error initializing OCL: "+x.message)}})};e._initializeWAX=function(a){if(m(c)&&m(c.init)){var b=c.constants,d={},e={};return c.init.initializeWaxFormDataLoaderSettings(a,null,(e[b.parsePreferences.PARSE_CRITERIAS]=(d[b.parseCriterias.ALLOW_PAGE_PORT_VIEW]=!0,d),e[b.parsePreferences.REGEX_ENABLED_FIELDS]=[b.fieldType.EMAIL,b.fieldType.PASSWORD,b.fieldType.PIN,b.fieldType.SSN,b.fieldType.CREDIT_CARD_NUMBER],e))}return Promise.resolve("Wax not needed")};
e._registerSI=function(){return new Promise(function(a,c){try{m(f)&&m(f.scamInsightMgr)&&(f.scamInsightMgr.registerEventCallback(b.webProtection.handleScamInsightEvent),f.scamInsightMgr.setVersion(b.constants.VERSION)),a("ScamInsight callback registered and extension version is set")}catch(x){c("Error registering ScamInsight callback or setting extension version: "+x.message)}})};e.ready=function(){if(m(e.readyPromise))return e.readyPromise;e.readyPromise=new Promise(function(a,b){d.extensionAdapter.init();
Promise.all([e.initializeGlobalSettings(),e.initializeLocalizer(),e._initializeWebProtectionPolicy(),e._initializeWCID(),e._initializeOCL()]).then(function(){var c=d.localizer.getLocale();Promise.all([e.initializeTelemetry(),e._initializeWAX(c),e._registerSI()]).then(function(){a("NSSS is ready")},function(a){b("NSSS initialize failed: "+a)})},function(a){b("NSSS initialize failed: "+a)})});return e.readyPromise};return e}(c.SymBfw,c.NSSS,c.WCID,c.SymWax,c.SafeWeb,c.SymO2)})(executionContext);
(function(c){(c.NSSS=c.NSSS||{}).partnerConstants={searchboxExclusionList:{1001:{puid:["1251","59"]},1013:{puid:"6990 10000001 6498 6251 1339 1314 1312 1308 1301 1270 1113 130 129".split(" ")},1005:{puid:"20000002 20000001 6412 1394 1393 1392 1391 1390 1389 1388 1387 1386 1385 1384 1383 1325 1313 1298 1284 1283 1282 1281 1280 1278 1276 1271 1235 1154 1133 1131 1129 1128 1127 1121 1120 1119 1103 126 125 124 123 122 120 115 114 109 107 106 104 101 86 83 79 77".split(" ")},1118:{puid:["1193"]}},excludeNortonLinks:"sos oem ppo cto tt ttda".split(" ")}})(executionContext);
(function(c){(c.NSSS=c.NSSS||{}).settingsManager=function(c,b,a){var d={},f=c.utils.isntNil,l=c.utils.isNil,e=c.utils.isBoolean,h=b.constants,m=c.localizer,g=c.extensionAdapter,n=b.uiConstants,u=n.MESSAGES,x=n.SETTINGS_UI.strings,r=n.BROWSER_NOTIFICATION.strings,y=c.telemetrySettings;d._postSignOut=function(a){var b=m.getLocalizedStrings(r),d=null;a?d=b["You have successfully logged out of your Norton Account"]:d=b["Sorry, something went wrong. Please try again."];a=new c.TimedNotification(d,n.BROWSER_NOTIFICATION_IMAGE);
c.notificationCenter.addNotification(a)};d.handleMessage=function(b,c,g){g=b.message;switch(b.name){case u.SET_TELEMETRY_ENABLED:e(g)&&y.setTelemetryEnabled(g);break;case u.SETTINGS_PRIVACY_POLICY:d.openSiteDirector(h.PRIVACY_POLICY_SSDCAT);break;case u.SETTINGS_PAGE_UI_INIT:var l={};l.direction=m.getCurrentLanguageDirection();l.strings=m.getLocalizedStrings(x);l.isLoggedIn=!1;l.email=null;l.isTelemetryEnabled=y.isTelemetryEnabled();if(f(a)&&f(a.session)){var n=a.session;n.isLoggedIn(function(a){var b=
n.getEmail();a&&f(b)&&(l.isLoggedIn=!0,l.email=b);c(l)});return!0}c(l);break;case u.SIGN_OUT:if(f(a)&&f(a.session))return a.session.logout(function(a){c({isLogoutSuccess:a});d._postSignOut(a)}),!0}};d.openSiteDirector=function(a){var b=h.SITE_DIRECTOR_URL,d=c.localizer.getNavigatorLanguage().split("-"),e=d[0];d=d[1];l(d)&&(d=h.DEFAULT_COUNTRY);d=h.ISO2_ISO3_COUNTRY[d.toUpperCase()];e=h.ISO2_ISO3_LANGUAGE[e.toUpperCase()];b=b.replace("ISO3_COUNTRY_CODE",d);b=b.replace("ISO3_LAN_CODE",e);b=b.replace("SSDCAT_VALUE",
a);g.createTab(b)};g.addMessageListener(d.handleMessage);return d}(c.SymBfw,c.NSSS,c.SymO2)})(executionContext);
