var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,b){a!=Array.prototype&&a!=Object.prototype&&(a[e]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var e=0;return $jscomp.iteratorPrototype(function(){return e<a.length?{done:!1,value:a[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var e=a[Symbol.iterator];return e?e.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var e,b=[];!(e=a.next()).done;)b.push(e.value);return b};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
$jscomp.polyfill=function(a,e,b,c){if(e){b=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var d=a[c];d in b||(b[d]={});b=b[d]}a=a[a.length-1];c=b[a];e=e(c);e!=c&&null!=e&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Object.is",function(a){return a?a:function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,b){var c=this;c instanceof String&&(c=String(c));var d=c.length;b=b||0;for(0>b&&(b=Math.max(b+d,0));b<d;b++){var e=c[b];if(e===a||Object.is(e,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,e,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(e instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,b){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,b||0)}},"es6","es3");
$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},e=Object.create(new $jscomp.global.Proxy(a,{get:function(b,c,d){return b==a&&"q"==c&&d==e}}));return!0===e.q}catch(b){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.owns=function(a,e){return Object.prototype.hasOwnProperty.call(a,e)};
$jscomp.polyfill("WeakMap",function(a){function e(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),f=Object.seal({}),c=new a([[b,2],[f,3]]);if(2!=c.get(b)||3!=c.get(f))return!1;c.delete(b);c.set(f,4);return!c.has(b)&&4==c.get(f)}catch(n){return!1}}function b(a){$jscomp.owns(a,d)||$jscomp.defineProperty(a,d,{value:{}})}function c(a){var f=Object[a];f&&(Object[a]=function(a){b(a);return f(a)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(e())return a;
var d="$jscomp_hidden_"+Math.random();c("freeze");c("preventExtensions");c("seal");var l=0,g=function(a){this.id_=(l+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var f;!(f=a.next()).done;)f=f.value,this.set(f[0],f[1])}};g.prototype.set=function(a,f){b(a);if(!$jscomp.owns(a,d))throw Error("WeakMap key fail: "+a);a[d][this.id_]=f;return this};g.prototype.get=function(a){return $jscomp.owns(a,d)?a[d][this.id_]:void 0};g.prototype.has=
function(a){return $jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)};g.prototype.delete=function(a){return $jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)?delete a[d][this.id_]:!1};return g},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function e(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var f=Object.seal({x:4}),c=new a($jscomp.makeIterator([[f,"s"]]));if("s"!=c.get(f)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var b=c.entries(),d=b.next();if(d.done||d.value[0]!=f||"s"!=d.value[1])return!1;d=b.next();return d.done||4!=d.value[0].x||"t"!=d.value[1]||!b.next().done?!1:!0}catch(q){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(e())return a;$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=new WeakMap,c=function(a){this.data_={};this.head_=g();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}};c.prototype.set=function(a,c){var b=d(this,a);b.list||(b.list=this.data_[b.id]=[]);b.entry?b.entry.value=c:(b.entry={next:this.head_,previous:this.head_.previous,head:this.head_,
key:a,value:c},b.list.push(b.entry),this.head_.previous.next=b.entry,this.head_.previous=b.entry,this.size++);return this};c.prototype.delete=function(a){a=d(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=g();this.size=0};c.prototype.has=function(a){return!!d(this,a).entry};
c.prototype.get=function(a){return(a=d(this,a).entry)&&a.value};c.prototype.entries=function(){return l(this,function(a){return[a.key,a.value]})};c.prototype.keys=function(){return l(this,function(a){return a.key})};c.prototype.values=function(){return l(this,function(a){return a.value})};c.prototype.forEach=function(a,c){for(var b=this.entries(),d;!(d=b.next()).done;)d=d.value,a.call(c,d[1],d[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(a,c){var d=c&&typeof c;"object"==
d||"function"==d?b.has(c)?d=b.get(c):(d=""+ ++k,b.set(c,d)):d="p_"+c;var e=a.data_[d];if(e&&$jscomp.owns(a.data_,d))for(a=0;a<e.length;a++){var f=e[a];if(c!==c&&f.key!==f.key||c===f.key)return{id:d,list:e,index:a,entry:f}}return{id:d,list:e,index:-1,entry:void 0}},l=function(a,c){var b=a.head_;return $jscomp.iteratorPrototype(function(){if(b){for(;b.head!=a.head_;)b=b.previous;for(;b.next!=b.head;)return b=b.next,{done:!1,value:c(b)};b=null}return{done:!0,value:void 0}})},g=function(){var a={};return a.previous=
a.next=a.head=a},k=0;return c},"es6","es3");
$jscomp.polyfill("Set",function(a){function e(){if($jscomp.ASSUME_NO_NATIVE_SET||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),b=new a($jscomp.makeIterator([c]));if(!b.has(c)||1!=b.size||b.add(c)!=b||1!=b.size||b.add({x:4})!=b||2!=b.size)return!1;var e=b.entries(),g=e.next();if(g.done||g.value[0]!=c||g.value[1]!=c)return!1;g=e.next();return g.done||g.value[0]==c||4!=g.value[0].x||g.value[1]!=g.value[0]?!1:e.next().done}catch(k){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(e())return a;$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.map_.size};b.prototype.add=function(a){this.map_.set(a,a);this.size=this.map_.size;return this};b.prototype.delete=function(a){a=this.map_.delete(a);this.size=this.map_.size;return a};b.prototype.clear=function(){this.map_.clear();
this.size=0};b.prototype.has=function(a){return this.map_.has(a)};b.prototype.entries=function(){return this.map_.entries()};b.prototype.values=function(){return this.map_.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(a,b){var c=this;this.map_.forEach(function(d){return a.call(b,d,d,c)})};return b},"es6","es3");var executionContext=this;
(function(a){(a.SafeWeb=a.SafeWeb||{}).constants={SHASTA_URL:"https://ratings-wrs.symantec.com",SHASTA_LOOKUP_PATH:"brief",DEFAULT_FULL_REPORT_URL:"https://safeweb.norton.com/report/show",HTTP_PROTOCOL:"http",HTTPS_PROTOCOL:"https",PII_SUBMISSION_TIMEOUT:2E3,SCAM_INSIGHT_BLOCK_PAGE_PATH:"content/ui/scam-insight-block-page.html",BLOCK_PAGE_PATH:"content/ui/blockedPage.html",ROOT_NODE:{TAG_NAME:"symantec",VERSION_ATTR:"v",CACHE_POSITIVE_ATTR:"cacheP",CACHE_NEGATIVE_ATTR:"cacheN"},PII_FLAGS:{EXIT_SITE:0,
CONTINUE_TO_SITE:1,SUPPRESSED_DUE_TO_SILENTMODE:2,SUPPRESSED_DUE_TO_HTTPS:4},PII_SUBMISSION_STATUS:{SUCCESS:"Success",FAILURE:"Fail"},SITE_NODE:{TAG_NAME:"site",CANONICAL_SITE_ID_ATTR:"id",COMBINED_RATING_ATTR:"r",SECURITY_RATING_ATTR:"sr",BUSINESS_RATING_ATTR:"br",CACHE_ATTR:"cache",PII_ENABLE_ATTR:"piien",PII_POLICY_HTTPS:"piipolhttps",PII_POLICY_ID:"piipolid",PII_POLICY_FIELD_TYPE:"piipolft"},WRS_RATINGS:{UNKNOWN_SITE:"u",BAD_SITE:"b",WARNING_SITE:"w",GOOD_SITE:"g",NORTON_SECURE_SITE:"r",PII_NOT_ENABLED:"n",
PII_ENABLED:"y",PII_SILENCE:"s"},ANNOYANCE_FACTORS_KEYS:{PUAPP:!0,HRDUN:!0,JOKE:!0,MLAPP:!0,TRCKW:!0,TPSQT:!0,PPCNA:!0,HACK:!0,SPAM:!0,SWBPL:!0},PII_FACTORS_KEYS:{PIIAGE:"age",PIIPOP:"pop"},PII_POLICY_HTTPS_KEYS:{DONTCARE:"dc",HTTPS:"h"},IDENTITY_THREATS_KEYS:{MLWR:!0,MBCHG:!0,RMTA:!0,PHISH:!0,BDOOR:!0,ISTLR:!0,DIAL:!0,DLDR:!0,SPWR:!0},SHOPPING_RISKS_KEYS:{CTFGS:!0,RCGS:!0,REPLC:!0},COMPUTER_THREATS_KEYS:{COHD:!0,ADWR:!0,VIRUS:!0,WORM:!0,SRISK:!0,BREXP:!0,MLWR:!0,MBCHG:!0,HEUR:!0,ELTMS:!0,TRJN:!0},
SITE_FACT_NODE:{TAG_NAME:"d",REPORTED_BY_KEY:"reported_by",SRC_KEY:"src",ID_KEY:"id"},SITE_FACT_IDS:{PRIVACY_POLICY_APPROVED:"privacy policy approved",NETWORK_SCANNING_SERVICE:"network scanning service",SSL_CA_NAME:"ssl CA name",AUTHORIZED_RESELLER:"Authorized Reseller",CERTIFIED_BUSINESS:"certified business",VERISIGN_TRUSTED:"VRTRU",VERISIGN_SSL:"VRSSL"},SITE_FACT_SOURCES:{SRC_BUYSAFE:"BUYSAFE",SRC_VERISIGN:"Verisign",SRC_MARK_MONITOR:"MARKMONITOR"},ATTRIBUTE_COUNT:"cnt",CACHE_LIMIT:1E3,RATING_TYPE:{WCID_HEURISTICS:1,
WCID_CHECK_URL:2,SAFEWEB:3,SCAM_INSIGHT:4},MESSAGES:{WAX_FIELDS_FOUND:"45E6BAD1-9F79-4E16-BA3A-1F77AA21EAC9",PROCESS_PAGE_FOR_SCAM_FIELDS:"FEDA41BC-73DC-4F99-A2CF-B5589CF2D0F8",TOP_FRAME_UNLOADED:"E5C199FF-A74B-414F-803C-4C7030C0E573"},IS_SCAM_INSIGHT_ENABLED:!0,performanceReporter:{COMPONENT:{SCAM_INSIGHT:"scam_insight"},TYPE:{INIT:"init",PII_PROTO_SUBMISSION:"_piiProtoSubmission",CALCULATE_SCAM_RATING:"_calculateScamInsightRating",HANDLE_PII_RATING:"_handlePIIEnabledRating",SET_WRS_RESPONSE:"setWrsResponse",
HANDLE_MESSAGE:"_handleMessage",HANDLE_MESSAGE_CALLBACK:"_handleScamPageFoundCallback",HANDLE_CACHE_RESPONSE:"_handleCacheResponse",SEND_PII_SUBMISSION:"sendPIISubmission",COLLECT_PII_FIELDS:"_collectPIIFields",TOP_FRAME_UNLOADED:"topFrameUnloaded",ADD_MUTATION_OBSERVER:"_addBodyMutationObserver",FIELD_FOUND_CALLBACK:"handleFieldsFoundCallback"}},SCAM_INSIGHT_RESULT:{UNTESTED:0,SUSPICIOUS_PAGE:1,SUSPICIOUS_NO_BLOCK_PAGE:2,NOT_SUSPICIOUS_PAGE:3},SCAM_INSIGHT_RATING_KEY:"scamRating"}})(executionContext);
(function(a){(a.SafeWeb=a.SafeWeb||{}).scamInsightWaxController=function(a){var b=SymWax.main,c=a.extensionAdapter,d=SafeWeb.constants,e=SymWax.constants,g=a.utils.isntNil,k=a.utils.isNil,f=a.utils.isArray,r=a.logger,n=a.performanceReporterFactoryProxy,h={init:function(){SafeWeb.constants.IS_SCAM_INSIGHT_ENABLED&&(h.arrPIIFields=[],h._bodyObserver=null,b.registerFieldsFoundCallback(h.handleFieldsFoundCallback,e.fieldFilter.type.CATEGORIZED_INPUT_FIELDS),b.registerFormsFound(function(){}),window.addEventListener("load",
function(){b.initWithThreshold(function(a){!0===a&&c.addContentScriptMessageListener(h.handleMessage)})},!0),a.utils.isTopLevelWindow()&&window.addEventListener("beforeunload",function(){c.sendMessage({id:d.MESSAGES.TOP_FRAME_UNLOADED})},!0))},_addBodyMutationObserver:function(){var a=document.querySelectorAll("body")[0];if(!k(a)){g(h._bodyObserver)&&h._bodyObserver.disconnect();var c=0;h._bodyObserver=new MutationObserver(function(){0!==c&&clearTimeout(c);c=setTimeout(function(){if("complete"===
b.getReadyState()){var a=d.performanceReporter.TYPE.ADD_MUTATION_OBSERVER+":"+Date.now();n.reportStart(d.performanceReporter.COMPONENT.SCAM_INSIGHT,a);b.analyzePage();n.reportEnd(d.performanceReporter.COMPONENT.SCAM_INSIGHT,a)}c=0},500)});h._bodyObserver.observe(a,{attributes:!0,childList:!0,subtree:!0})}},handleFieldsFoundCallback:function(a){if(f(a)&&!(0>=a.length)){var b=d.performanceReporter.TYPE.FIELD_FOUND_CALLBACK+":"+Date.now();n.reportStart(d.performanceReporter.COMPONENT.SCAM_INSIGHT,b);
var k=[],l=!0,q;for(q in a){var m=e.fieldTypeToPIIIdentifiers[a[q].getFieldType()],p=e.fieldTypeToPIIIdentifiers[a[q].getPreGroupFieldType()];g(m)&&!k.includes(m)&&(k.push(m),h.arrPIIFields.includes(m)||(l=!1));g(m)&&g(p)&&m!==p&&!k.includes(p)&&(k.push(p),h.arrPIIFields.includes(p)||(l=!1))}!1===l&&(h.arrPIIFields=[].concat($jscomp.arrayFromIterable(new Set([].concat($jscomp.arrayFromIterable(h.arrPIIFields),$jscomp.arrayFromIterable(k))))),r.debug(h.arrPIIFields),c.sendMessage({id:d.MESSAGES.WAX_FIELDS_FOUND,
data:h.arrPIIFields}));n.reportEnd(d.performanceReporter.COMPONENT.SCAM_INSIGHT,b)}},handleMessage:function(a,b,c){if(!k(a)&&!k(a.id))switch(a.id){case d.MESSAGES.PROCESS_PAGE_FOR_SCAM_FIELDS:h._addBodyMutationObserver(),r.debug("Mutation observer added")}}};h.init();return h}(a.SymBfw)})(executionContext);
