var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(g,f,e){g!=Array.prototype&&g!=Object.prototype&&(g[f]=e.value)};$jscomp.getGlobal=function(g){return"undefined"!=typeof window&&window===g?g:"undefined"!=typeof global&&null!=global?global:g};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var g=0;return function(f){return $jscomp.SYMBOL_PREFIX+(f||"")+g++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var g=$jscomp.global.Symbol.iterator;g||(g=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[g]&&$jscomp.defineProperty(Array.prototype,g,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(g){var f=0;return $jscomp.iteratorPrototype(function(){return f<g.length?{done:!1,value:g[f++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(g){$jscomp.initSymbolIterator();g={next:g};g[$jscomp.global.Symbol.iterator]=function(){return this};return g};$jscomp.makeIterator=function(g){$jscomp.initSymbolIterator();var f=g[Symbol.iterator];return f?f.call(g):$jscomp.arrayIterator(g)};
$jscomp.iteratorFromArray=function(g,f){$jscomp.initSymbolIterator();g instanceof String&&(g+="");var e=0,c={next:function(){if(e<g.length){var b=e++;return{value:f(b,g[b]),done:!1}}c.next=function(){return{done:!0,value:void 0}};return c.next()}};c[Symbol.iterator]=function(){return c};return c};
$jscomp.polyfill=function(g,f,e,c){if(f){e=$jscomp.global;g=g.split(".");for(c=0;c<g.length-1;c++){var b=g[c];b in e||(e[b]={});e=e[b]}g=g[g.length-1];c=e[g];f=f(c);f!=c&&null!=f&&$jscomp.defineProperty(e,g,{configurable:!0,writable:!0,value:f})}};$jscomp.polyfill("Array.prototype.keys",function(g){return g?g:function(){return $jscomp.iteratorFromArray(this,function(f){return f})}},"es6","es3");$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(g){function f(){this.batch_=null}function e(d){return d instanceof b?d:new b(function(a,b){a(d)})}if(g&&!$jscomp.FORCE_POLYFILL_PROMISE)return g;f.prototype.asyncExecute=function(d){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(d);return this};f.prototype.asyncExecuteBatch_=function(){var d=this;this.asyncExecuteFunction(function(){d.executeBatch_()})};var c=$jscomp.global.setTimeout;f.prototype.asyncExecuteFunction=function(d){c(d,
0)};f.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var d=this.batch_;this.batch_=[];for(var a=0;a<d.length;++a){var b=d[a];d[a]=null;try{b()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};f.prototype.asyncThrow_=function(d){this.asyncExecuteFunction(function(){throw d;})};var b=function(d){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{d(a.resolve,a.reject)}catch(h){a.reject(h)}};b.prototype.createResolveAndReject_=
function(){function d(d){return function(k){b||(b=!0,d.call(a,k))}}var a=this,b=!1;return{resolve:d(this.resolveTo_),reject:d(this.reject_)}};b.prototype.resolveTo_=function(d){if(d===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof b)this.settleSameAsPromise_(d);else{a:switch(typeof d){case "object":var a=null!=d;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(d):this.fulfill_(d)}};b.prototype.resolveToNonPromiseObj_=function(d){var a=
void 0;try{a=d.then}catch(h){this.reject_(h);return}"function"==typeof a?this.settleSameAsThenable_(a,d):this.fulfill_(d)};b.prototype.reject_=function(a){this.settle_(2,a)};b.prototype.fulfill_=function(a){this.settle_(1,a)};b.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};b.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var d=
0;d<this.onSettledCallbacks_.length;++d)a.asyncExecute(this.onSettledCallbacks_[d]);this.onSettledCallbacks_=null}};var a=new f;b.prototype.settleSameAsPromise_=function(a){var d=this.createResolveAndReject_();a.callWhenSettled_(d.resolve,d.reject)};b.prototype.settleSameAsThenable_=function(a,b){var d=this.createResolveAndReject_();try{a.call(b,d.resolve,d.reject)}catch(l){d.reject(l)}};b.prototype.then=function(a,e){function d(a,d){return"function"==typeof a?function(d){try{c(a(d))}catch(n){k(n)}}:
d}var c,k,f=new b(function(a,d){c=a;k=d});this.callWhenSettled_(d(a,c),d(e,k));return f};b.prototype.catch=function(a){return this.then(void 0,a)};b.prototype.callWhenSettled_=function(d,b){function e(){switch(c.state_){case 1:d(c.result_);break;case 2:b(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?a.asyncExecute(e):this.onSettledCallbacks_.push(e)};b.resolve=e;b.reject=function(a){return new b(function(d,b){b(a)})};b.race=function(a){return new b(function(d,
b){for(var c=$jscomp.makeIterator(a),k=c.next();!k.done;k=c.next())e(k.value).callWhenSettled_(d,b)})};b.all=function(a){var d=$jscomp.makeIterator(a),c=d.next();return c.done?e([]):new b(function(a,k){function b(k){return function(d){f[k]=d;m--;0==m&&a(f)}}var f=[],m=0;do f.push(void 0),m++,e(c.value).callWhenSettled_(b(f.length-1),k),c=d.next();while(!c.done)})};return b},"es6","es3");(function(g){(g.SymBfw=g.SymBfw||{}).globals={BROWSER:"Chrome",PRODUCT_GUID:"DC6B1B05-C7B2-43EB-81E3-CBD3896553C2"}})(this);
(function(g){(g.SymBfw=g.SymBfw||{}).logger=function(f){return{debug:function(e){},log:function(e){},error:function(e){console.error(e);var c=f.telemetryWrapper;c.send(c.componentType.LOGGER,c.actionType.ERROR,e)},warn:function(e){console.warn(e);var c=f.telemetryWrapper;c.send(c.componentType.LOGGER,c.actionType.WARN,e)},info:function(e){console.info(e)}}}(g.SymBfw)})(this);
(function(g){g=g.SymBfw;var f={httpStatusCodes:{},localizer:{DEFAULT_MESSAGES_DICTIONARY:"strings",GET_LOCALIZED_STRING:"44F4D54E-AB86-454C-A494-DE3AD87E72F9",GET_LOCALIZED_STRINGS:"0D1C5EEF-749F-4EEB-AD6D-F9C26018EE91",GET_ALL_LOCALIZED_STRINGS:"33445b60-9a88-4d99-829f-564704b2a960",GET_LOCALIZED_STRING_FROM_DICTIONARY:"D15C0B4C-DC1B-403F-A3C8-8BB42137B325",GET_LOCALIZED_STRINGS_FROM_DICTIONARY:"88313974-C371-4A8D-9196-0A2CE43C8327",GET_LOCALIZED_STRING_WITH_FORMAT:"F3D7C8CE-B1A9-425A-AD24-4120C592AF86",
GET_LOCALIZED_STRING_WITH_FORMAT_FROM_DICTIONARY:"9066F4CC-31A4-45F5-A07A-81DDC38E5F99",GET_CURRENT_LANGUAGE_DIRECTION:"C30B2719-DD82-41EC-E93A-8A602444F90A"},clipboard:{messages:{CLEAR_CLIPBOARD:"aa232db5-1dba-473a-ab4b-e9c378b7978b"},DEFAULT_TIMEOUT:6E4}};f.httpStatusCodes.OK=200;f.httpStatusCodes.PARTIAL_CONTENT=206;f.httpStatusCodes.CREATED=201;f.httpStatusCodes.NO_CONTENT=204;f.httpStatusCodes.INCORRECT_URI=302;f.httpStatusCodes.NOT_MODIFIED=304;f.httpStatusCodes.BAD_REQUEST=400;f.httpStatusCodes.UNAUTHORIZED=
401;f.httpStatusCodes.INVALID_SCHEMA=403;f.httpStatusCodes.NOT_FOUND=404;f.httpStatusCodes.HEADER_ERROR=406;f.httpStatusCodes.GONE=410;f.httpStatusCodes.ENTITY_TOO_LARGE=413;f.httpStatusCodes.DATASTORE_RATE_LIMITED=429;f.httpStatusCodes.RATE_LIMITING=503;f.httpStatusCodes.SERVER_ERROR=500;f.DEFAULT_FETCH_TIMEOUT=6E4;f.telemetry={TELEMETRY_ENABLED:"293E0764-AF48-4C52-B675-0161A7B6BECE",TELEMETRY_OPT_OUT_SHOWN:"FE795012-44D6-491D-A8A1-E83633892C9D",BFW_TELEMETRY_SETTINGS_CONTAINER:"233D07C0-6318-4BCE-A36A-82DFB19F3B2A",
USER_RESPONDED_IN_OPT_OUT_PAGE:"8157BC1F-5ED8-4373-A18D-8CD8E0263752",LAST_OFFER_DATE:"9EA53F0C-7F18-44A5-8138-C11F27D66FC1"};f.os={WINDOWS:"Windows",MAC:"Mac",UNKNOWN:"Unknown"};f.uiConstants={NOTIFICATION:{IFRAME_ID:"symc-notification-popup",HTML:"content/ui/notification.html",STYLE:"content/ui/content-page.css",STACK_COUNT:1,DEFAULT_TIMEOUT:1E4,HEIGHT:160,WIDTH:460,TYPE:{QUESTION:0,TIMED:1},BUTTON:{DEFAULT:0,SECONDARY:1},MESSAGES:{DEFAULT_MESSAGE:"8DB8FE17-6F5E-485E-81EE-1112762F48E4",DEFAULT_BUTTON_PRESSED:"209CBB4D-6D6B-46F4-9EA7-303181937BF6",
SECONDARY_LINK_PRESSED:"8881560D-E8A2-41FA-A81D-A90D41311D0D",THIRD_BUTTON_PRESSED:"196F06EB-956E-44EE-A60D-F4741C5CF4D3",NOTIFICATION_CLOSED:"EA7414A5-667F-4459-BAC2-38464F3330A3",NOTIFICATION_QUEUE_MESSAGE:"A88CCFCD-B98D-4607-B780-79A1CF7ADFAD",NOTIFICATIONS_SHOWN:"57C094C2-F0F0-44C2-9BBF-9E147135FB50",UI_INIT:"EE5B61D6-3A55-4ABB-B304-02BDAD9698FE",UI_INIT_PROXY:"0FABE0DB-1C87-475B-D89E-F4EC0EE963DE",HIDE_NOTIFICATIONS:"8211780F-93EC-4E37-8933-E60CB6052E84"}},CONTENT_PAGE_STYLE_ID:"symc-content-stylesheet"};
f.performanceReporter={MESSAGES:{REPORT_START:"2379B4CB-E725-4818-8FCC-A9372EABBF45",REPORT_END:"1F62DD4E-56AD-4528-9A69-BFE9EC135B9F",GET_PERFORMANCE_REPORTER:"2306DE62-ACA8-40AE-9909-517474C1120B"}};f.utils={IP:"ip"};f.NAVIGATION_COMPLETE="complete";g.constants=f})(this);
(function(g){g.SymBfw.utils=function(f){var e={},c=f.constants;e.createNewGuid=function(){var a=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(d){var b=(a+16*Math.random())%16|0;a=Math.floor(a/16);return("x"==d?b:b&7|8).toString(16)})};e.stringUTF16LEToByteArray=function(a){if(!1===this.isString(a))throw Error("Input string cannot be null or is not a string");for(var d=[],b=0;b<a.length;++b){var c=a.charCodeAt(b),e=(c&65280)>>8;d.push(c&255);d.push(e)}return d};
e.arrayBufferToStringUTF16LE=function(a){if(this.isNil(a))return null;a instanceof ArrayBuffer&&(a=new Uint8Array(a));for(var d=[],b=0;b<a.byteLength;b++)d.push(a[b]);return this.byteArrayToStringUTF16LE(d)};e.byteArrayToStringUTF16LE=function(a){if(!1===this.isArray(a))throw Error("Byte array cannot be null or is not an array");if(2>a.length)throw Error("Byte array needs to contain at least two bytes");if(0!==a.length%2)throw Error("Byte array needs to contain even number of bytes");for(var d="",
b=0;b<a.length-1;b+=2){var c=a[b];if(255<c)throw Error("Encoding error: Input contains element larger than a byte.");c&=255;var e=a[b+1];if(255<e)throw Error("Encoding error: Input contains element larger than a byte.");e=e<<8&65280;d+=String.fromCharCode(c+e)}return d};e.downloadFileFromUrl=function(a){var d=document.createElement("iframe");d.style.display="none";d.src=a;d.width="1";d.height="1";d.frameborder="0";document.body.appendChild(d);setTimeout(function(){document.body.removeChild(d)},5E3)};
e.obfuscatePassword=function(a,d){if(!1===this.isString(a))throw Error("password  cannot be null and has to be a string");if(!1===this.isString(d))throw Error("obfuscationKey  cannot be null and has to be a string");a=new Uint8Array(f.utils.stringUTF16LEToByteArray(a));d=new Uint8Array(f.utils.stringUTF16LEToByteArray(d));d=f.utils._obfuscateData(a,d);return d=f.utils.arrayBufferToStringUTF16LE(d)};e._obfuscateData=function(a,d){if(e.isNil(a)||e.isNil(d))return null;a instanceof ArrayBuffer&&(a=new Uint8Array(a));
d instanceof ArrayBuffer&&(d=new Uint8Array(d));for(var b=a.byteLength,c=new Uint8Array(b),f=0;f<b;f++)c[f]=a[f]^d[f%b];return c};e.getOSType=function(){var a=c.os.UNKNOWN;-1!=navigator.appVersion.toLowerCase().indexOf("win")?a=c.os.WINDOWS:-1!=navigator.appVersion.toLowerCase().indexOf("mac")&&(a=c.os.MAC);return a};e.isNil=function(a){return"undefined"===typeof a||null===a?!0:!1};e.isntNil=function(a){return"undefined"!==typeof a&&null!==a?!0:!1};e.isEmptyObject=function(a){return e.isNil(a)||0===
Object.keys(a).length?!0:!1};e.isString=function(a){return e.isntNil(a)&&"string"===typeof a?!0:!1};e.isFunction=function(a){return e.isntNil(a)&&"function"===typeof a?!0:!1};e.isArray=function(a){return Array.isArray(a)};e.isBoolean=function(a){return e.isntNil(a)&&"boolean"===typeof a?!0:!1};var b={ac:{com:!0,gov:!0,mil:!0,net:!0,org:!0,edu:!0},ad:{nom:!0},ae:{ac:!0,co:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,pro:!0,sch:!0},af:{com:!0,edu:!0,gov:!0,net:!0,org:!0},ai:{off:!0,com:!0,net:!0,org:!0},
al:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0,uniti:!0,tirana:!0,soros:!0,upt:!0,inima:!0},an:{com:!0,net:!0,org:!0,edu:!0},ag:{com:!0,org:!0,net:!0,co:!0,nom:!0},ao:{co:!0,ed:!0,gv:!0,it:!0,og:!0,pb:!0},ar:{com:!0,edu:!0,gob:!0,gov:!0,"int":!0,mil:!0,net:!0,org:!0,tur:!0},arpa:{e164:!0,"in-addr":!0,iris:!0,ip6:!0,uri:!0,urn:!0},at:{ac:!0,co:!0,gv:!0,or:!0,priv:!0},au:{asn:!0,com:!0,net:!0,id:!0,org:!0,csiro:!0,oz:!0,info:!0,conf:!0,act:!0,nsw:!0,nt:!0,qld:!0,sa:!0,tas:!0,vic:!0,wa:!0},aw:{com:!0},
az:{com:!0,net:!0,"int":!0,gov:!0,biz:!0,org:!0,edu:!0,mil:!0,pp:!0,name:!0,info:!0},ba:{co:!0,com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0,rs:!0,unbi:!0,unmo:!0,unsa:!0,untz:!0,unze:!0},bb:{biz:!0,co:!0,com:!0,edu:!0,gov:!0,info:!0,net:!0,org:!0,store:!0,tv:!0},bd:{com:!0,edu:!0,net:!0,gov:!0,org:!0,mil:!0},be:{ac:!0},bf:{gov:!0},bh:{biz:!0,cc:!0,com:!0,edu:!0,gov:!0,info:!0,net:!0,org:!0},bm:{com:!0,edu:!0,org:!0,gov:!0,net:!0},bn:{com:!0,edu:!0,gov:!0,net:!0,org:!0},bo:{com:!0,edu:!0,gob:!0,gov:!0,
"int":!0,mil:!0,net:!0,org:!0,tv:!0},br:{adm:!0,adv:!0,agr:!0,am:!0,arq:!0,art:!0,ato:!0,b:!0,bio:!0,blog:!0,bmd:!0,cim:!0,cng:!0,cnt:!0,com:!0,coop:!0,ecn:!0,edu:!0,eng:!0,esp:!0,etc:!0,eti:!0,far:!0,flog:!0,fm:!0,fnd:!0,fot:!0,fst:!0,g12:!0,ggf:!0,gov:!0,imb:!0,ind:!0,inf:!0,jor:!0,jus:!0,lel:!0,mat:!0,med:!0,mil:!0,mus:!0,net:!0,nom:!0,not:!0,ntr:!0,odo:!0,org:!0,ppg:!0,pro:!0,psc:!0,psi:!0,qsl:!0,rec:!0,slg:!0,srv:!0,tmp:!0,trd:!0,tur:!0,tv:!0,vet:!0,vlog:!0,wiki:!0,zlg:!0},bs:{com:!0,edu:!0,
gov:!0,net:!0,org:!0},bt:{com:!0,edu:!0,gov:!0,net:!0,org:!0},bw:{co:!0,org:!0},by:{gov:!0,mil:!0},bz:{du:!0,et:!0,om:!0,ov:!0,rg:!0},ca:{ab:!0,bc:!0,mb:!0,nb:!0,nf:!0,nl:!0,ns:!0,nt:!0,nu:!0,on:!0,pe:!0,qc:!0,sk:!0,yk:!0},cc:{co:!0},ck:{biz:!0,co:!0,edu:!0,gen:!0,gov:!0,info:!0,net:!0,org:!0},cn:{ac:!0,ah:!0,bj:!0,com:!0,cq:!0,edu:!0,fj:!0,gd:!0,gov:!0,gs:!0,gx:!0,gz:!0,ha:!0,hb:!0,he:!0,hi:!0,hl:!0,hn:!0,jl:!0,js:!0,jx:!0,ln:!0,mil:!0,net:!0,nm:!0,nx:!0,org:!0,qh:!0,sc:!0,sd:!0,sh:!0,sn:!0,sx:!0,
tj:!0,tw:!0,xj:!0,xz:!0,yn:!0,zj:!0},co:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,nom:!0,org:!0},cr:{ac:!0,c:!0,co:!0,ed:!0,fi:!0,go:!0,or:!0,sa:!0},cx:{gov:!0},cy:{ac:!0,biz:!0,com:!0,ekloges:!0,gov:!0,ltd:!0,name:!0,net:!0,org:!0,parliament:!0,press:!0,pro:!0,tm:!0},cu:{com:!0,edu:!0,org:!0,net:!0,gov:!0,inf:!0},dm:{com:!0,net:!0,org:!0,edu:!0,gov:!0},"do":{art:!0,com:!0,edu:!0,gob:!0,gov:!0,mil:!0,net:!0,org:!0,sld:!0,web:!0},dz:{art:!0,asso:!0,com:!0,edu:!0,gov:!0,net:!0,org:!0,pol:!0},ec:{com:!0,edu:!0,
fin:!0,gov:!0,info:!0,med:!0,mil:!0,net:!0,org:!0,pro:!0},ee:{com:!0,org:!0,fie:!0,pri:!0},eg:{com:!0,edu:!0,eun:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,sci:!0},er:{com:!0,edu:!0,gov:!0,ind:!0,mil:!0,net:!0,org:!0,rochest:!0,w:!0},es:{com:!0,edu:!0,gob:!0,nom:!0,org:!0},et:{biz:!0,com:!0,edu:!0,gov:!0,info:!0,name:!0,net:!0,org:!0},fi:{aland:!0},fj:{ac:!0,biz:!0,com:!0,info:!0,mil:!0,name:!0,net:!0,org:!0,pro:!0},fk:{ac:!0,co:!0,gov:!0,net:!0,nom:!0,org:!0},fr:{asso:!0,com:!0,f:!0,gouv:!0,nom:!0,prd:!0,
presse:!0,tm:!0},ge:{com:!0,edu:!0,gov:!0,org:!0,mil:!0,net:!0,pvt:!0},gg:{co:!0,net:!0,org:!0},gh:{com:!0,edu:!0,gov:!0,mil:!0,org:!0},gi:{com:!0,ltd:!0,gov:!0,mod:!0,edu:!0,org:!0},gn:{ac:!0,com:!0,gov:!0,net:!0,org:!0},gp:{com:!0,net:!0,edu:!0,asso:!0,org:!0},gr:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},gt:{com:!0,edu:!0,gob:!0,ind:!0,mil:!0,net:!0,org:!0},gu:{com:!0,edu:!0,gov:!0,net:!0,org:!0},hk:{com:!0,edu:!0,gov:!0,idv:!0,net:!0,org:!0},ht:{com:!0,net:!0,firm:!0,shop:!0,info:!0,pro:!0,adult:!0,
org:!0,art:!0,pol:!0,rel:!0,asso:!0,perso:!0,coop:!0,med:!0,edu:!0,gouv:!0},hu:{2E3:!0,agrar:!0,bolt:!0,casino:!0,city:!0,co:!0,erotica:!0,erotika:!0,film:!0,forum:!0,games:!0,hotel:!0,info:!0,ingatlan:!0,jogasz:!0,konyvelo:!0,lakas:!0,media:!0,news:!0,org:!0,priv:!0,reklam:!0,sex:!0,shop:!0,sport:!0,suli:!0,szex:!0,tm:!0,tozsde:!0,utazas:!0,video:!0},id:{ac:!0,co:!0,go:!0,mil:!0,net:!0,or:!0,sch:!0,web:!0},il:{ac:!0,co:!0,gov:!0,idf:!0,k12:!0,muni:!0,net:!0,org:!0},im:{co:!0,"ltd.co":!0,"plc.co":!0,
net:!0,gov:!0,org:!0,nic:!0,ac:!0},"in":{ac:!0,co:!0,edu:!0,ernet:!0,firm:!0,gen:!0,gov:!0,i:!0,ind:!0,mil:!0,net:!0,nic:!0,org:!0,res:!0},iq:{com:!0,edu:!0,gov:!0,i:!0,mil:!0,net:!0,org:!0},ir:{ac:!0,co:!0,dnssec:!0,gov:!0,i:!0,id:!0,net:!0,org:!0,sch:!0},it:{edu:!0,gov:!0},je:{co:!0,net:!0,org:!0},jo:{com:!0,edu:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,sch:!0},jp:{ac:!0,ad:!0,co:!0,ed:!0,go:!0,gr:!0,lg:!0,ne:!0,or:!0},ke:{ac:!0,co:!0,go:!0,info:!0,me:!0,mobi:!0,ne:!0,or:!0,sc:!0},kh:{com:!0,edu:!0,
gov:!0,mil:!0,net:!0,org:!0,per:!0},ki:{biz:!0,com:!0,de:!0,edu:!0,gov:!0,info:!0,mob:!0,net:!0,org:!0,tel:!0},km:{asso:!0,com:!0,coop:!0,edu:!0,gouv:!0,k:!0,medecin:!0,mil:!0,nom:!0,notaires:!0,pharmaciens:!0,presse:!0,tm:!0,veterinaire:!0},kn:{edu:!0,gov:!0,net:!0,org:!0},kr:{ac:!0,busan:!0,chungbuk:!0,chungnam:!0,co:!0,daegu:!0,daejeon:!0,es:!0,gangwon:!0,go:!0,gwangju:!0,gyeongbuk:!0,gyeonggi:!0,gyeongnam:!0,hs:!0,incheon:!0,jeju:!0,jeonbuk:!0,jeonnam:!0,k:!0,kg:!0,mil:!0,ms:!0,ne:!0,or:!0,pe:!0,
re:!0,sc:!0,seoul:!0,ulsan:!0},kw:{com:!0,edu:!0,gov:!0,net:!0,org:!0},ky:{com:!0,edu:!0,gov:!0,net:!0,org:!0},kz:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},lb:{com:!0,edu:!0,gov:!0,net:!0,org:!0},lc:{com:!0,org:!0,edu:!0,gov:!0},li:{com:!0,net:!0,org:!0,gov:!0},lk:{assn:!0,com:!0,edu:!0,gov:!0,grp:!0,hotel:!0,"int":!0,ltd:!0,net:!0,ngo:!0,org:!0,sch:!0,soc:!0,web:!0},lr:{com:!0,edu:!0,gov:!0,net:!0,org:!0},ls:{org:!0,co:!0},lt:{gov:!0,mil:!0},lu:{gov:!0,mil:!0,org:!0,net:!0},lv:{asn:!0,com:!0,conf:!0,
edu:!0,gov:!0,id:!0,mil:!0,net:!0,org:!0},ly:{com:!0,edu:!0,gov:!0,id:!0,med:!0,net:!0,org:!0,plc:!0,sch:!0},ma:{ac:!0,co:!0,gov:!0,m:!0,net:!0,org:!0,press:!0},mc:{asso:!0,tm:!0},me:{ac:!0,co:!0,edu:!0,gov:!0,its:!0,net:!0,org:!0,priv:!0},mg:{com:!0,edu:!0,gov:!0,mil:!0,nom:!0,org:!0,prd:!0,tm:!0},mk:{com:!0,edu:!0,gov:!0,inf:!0,name:!0,net:!0,org:!0,pro:!0},ml:{com:!0,edu:!0,gov:!0,net:!0,org:!0,presse:!0},mn:{edu:!0,gov:!0,org:!0},mo:{com:!0,edu:!0,gov:!0,net:!0,org:!0},mt:{com:!0,edu:!0,gov:!0,
net:!0,org:!0},mv:{aero:!0,biz:!0,com:!0,coop:!0,edu:!0,gov:!0,info:!0,"int":!0,mil:!0,museum:!0,name:!0,net:!0,org:!0,pro:!0},mw:{ac:!0,co:!0,com:!0,coop:!0,edu:!0,gov:!0,"int":!0,museum:!0,net:!0,org:!0},mx:{com:!0,edu:!0,gob:!0,net:!0,org:!0},my:{com:!0,edu:!0,gov:!0,mil:!0,name:!0,net:!0,org:!0,sch:!0},nf:{arts:!0,com:!0,firm:!0,info:!0,net:!0,other:!0,per:!0,rec:!0,store:!0,web:!0},ng:{biz:!0,com:!0,edu:!0,gov:!0,mil:!0,mobi:!0,name:!0,net:!0,org:!0,sch:!0},ni:{ac:!0,co:!0,com:!0,edu:!0,gob:!0,
mil:!0,net:!0,nom:!0,org:!0},no:{mil:!0,stat:!0,kommune:!0,herad:!0,priv:!0,vgs:!0,fhs:!0,museum:!0,fylkesbibl:!0,folkebibl:!0,idrett:!0},np:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},nr:{biz:!0,com:!0,edu:!0,gov:!0,info:!0,net:!0,org:!0},om:{ac:!0,biz:!0,co:!0,com:!0,edu:!0,gov:!0,med:!0,mil:!0,museum:!0,net:!0,org:!0,pro:!0,sch:!0},pe:{com:!0,edu:!0,gob:!0,mil:!0,net:!0,nom:!0,org:!0,sld:!0},pf:{com:!0,org:!0,edu:!0},pg:{"com.pg":!0,net:!0},ph:{com:!0,edu:!0,gov:!0,i:!0,mil:!0,net:!0,ngo:!0,org:!0},
pk:{biz:!0,com:!0,edu:!0,fam:!0,gob:!0,gok:!0,gon:!0,gop:!0,gos:!0,gov:!0,net:!0,org:!0,web:!0},pl:{art:!0,bialystok:!0,biz:!0,com:!0,edu:!0,gda:!0,gdansk:!0,gorzow:!0,gov:!0,info:!0,katowice:!0,krakow:!0,lodz:!0,lublin:!0,mil:!0,net:!0,ngo:!0,olsztyn:!0,org:!0,poznan:!0,pwr:!0,radom:!0,slupsk:!0,szczecin:!0,torun:!0,warszawa:!0,waw:!0,wroc:!0,wroclaw:!0,zgora:!0},pr:{ac:!0,biz:!0,com:!0,edu:!0,est:!0,gov:!0,info:!0,isla:!0,name:!0,net:!0,org:!0,pro:!0,prof:!0},pro:{law:!0,med:!0,cpa:!0},ps:{com:!0,
edu:!0,gov:!0,net:!0,org:!0,plo:!0,sec:!0},pt:{com:!0,edu:!0,gov:!0,"int":!0,net:!0,nome:!0,org:!0,publ:!0},pw:{belau:!0,co:!0,ed:!0,go:!0,ne:!0,or:!0},ro:{arts:!0,com:!0,firm:!0,info:!0,nom:!0,nt:!0,org:!0,rec:!0,store:!0,tm:!0,www:!0},rs:{ac:!0,co:!0,edu:!0,gov:!0,"in":!0,org:!0},sb:{com:!0,edu:!0,gov:!0,net:!0,org:!0},sc:{com:!0,edu:!0,gov:!0,net:!0,org:!0},sh:{co:!0,com:!0,edu:!0,gov:!0,net:!0,nom:!0,org:!0},sl:{com:!0,edu:!0,gov:!0,net:!0,org:!0},st:{co:!0,com:!0,consulado:!0,edu:!0,embaixada:!0,
gov:!0,mil:!0,net:!0,org:!0,principe:!0,saotome:!0,store:!0},sv:{com:!0,edu:!0,gob:!0,org:!0,red:!0},sz:{ac:!0,co:!0,org:!0},tr:{av:!0,bbs:!0,bel:!0,biz:!0,com:!0,dr:!0,edu:!0,gen:!0,gov:!0,info:!0,k12:!0,name:!0,net:!0,org:!0,pol:!0,tel:!0,tsk:!0,tv:!0,web:!0},tt:{aero:!0,biz:!0,cat:!0,co:!0,com:!0,coop:!0,edu:!0,gov:!0,info:!0,"int":!0,jobs:!0,mil:!0,mobi:!0,museum:!0,name:!0,net:!0,org:!0,pro:!0,tel:!0,travel:!0},tw:{club:!0,com:!0,ebiz:!0,edu:!0,game:!0,gov:!0,idv:!0,mil:!0,net:!0,org:!0},mu:{ac:!0,
co:!0,com:!0,gov:!0,net:!0,or:!0,org:!0},mz:{ac:!0,co:!0,edu:!0,gov:!0,org:!0},na:{co:!0,com:!0},nz:{ac:!0,co:!0,cri:!0,geek:!0,gen:!0,govt:!0,health:!0,iwi:!0,maori:!0,mil:!0,net:!0,org:!0,parliament:!0,school:!0},pa:{abo:!0,ac:!0,com:!0,edu:!0,gob:!0,ing:!0,med:!0,net:!0,nom:!0,org:!0,sld:!0},py:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},qa:{com:!0,edu:!0,gov:!0,mil:!0,net:!0,org:!0},re:{asso:!0,com:!0,nom:!0},ru:{ac:!0,adygeya:!0,altai:!0,amur:!0,arkhangelsk:!0,astrakhan:!0,bashkiria:!0,belgorod:!0,
bir:!0,bryansk:!0,buryatia:!0,cbg:!0,chel:!0,chelyabinsk:!0,chita:!0,chukotka:!0,chuvashia:!0,com:!0,dagestan:!0,"e-burg":!0,edu:!0,gov:!0,grozny:!0,"int":!0,irkutsk:!0,ivanovo:!0,izhevsk:!0,jar:!0,"joshkar-ola":!0,kalmykia:!0,kaluga:!0,kamchatka:!0,karelia:!0,kazan:!0,kchr:!0,kemerovo:!0,khabarovsk:!0,khakassia:!0,khv:!0,kirov:!0,koenig:!0,komi:!0,kostroma:!0,kranoyarsk:!0,kuban:!0,kurgan:!0,kursk:!0,lipetsk:!0,magadan:!0,mari:!0,"mari-el":!0,marine:!0,mil:!0,mordovia:!0,mosreg:!0,msk:!0,murmansk:!0,
nalchik:!0,net:!0,nnov:!0,nov:!0,novosibirsk:!0,nsk:!0,omsk:!0,orenburg:!0,org:!0,oryol:!0,penza:!0,perm:!0,pp:!0,pskov:!0,ptz:!0,rnd:!0,ryazan:!0,sakhalin:!0,samara:!0,saratov:!0,simbirsk:!0,smolensk:!0,spb:!0,stavropol:!0,stv:!0,surgut:!0,tambov:!0,tatarstan:!0,tom:!0,tomsk:!0,tsaritsyn:!0,tsk:!0,tula:!0,tuva:!0,tver:!0,tyumen:!0,udm:!0,udmurtia:!0,"ulan-ude":!0,vladikavkaz:!0,vladimir:!0,vladivostok:!0,volgograd:!0,vologda:!0,voronezh:!0,vrn:!0,vyatka:!0,yakutia:!0,yamal:!0,yekaterinburg:!0,"yuzhno-sakhalinsk":!0},
rw:{ac:!0,co:!0,com:!0,edu:!0,gouv:!0,gov:!0,"int":!0,mil:!0,net:!0},sa:{com:!0,edu:!0,gov:!0,med:!0,net:!0,org:!0,pub:!0,sch:!0},sd:{com:!0,edu:!0,gov:!0,info:!0,med:!0,net:!0,org:!0,tv:!0},se:{a:!0,ac:!0,b:!0,bd:!0,c:!0,d:!0,e:!0,f:!0,g:!0,h:!0,i:!0,k:!0,l:!0,m:!0,n:!0,o:!0,org:!0,p:!0,parti:!0,pp:!0,press:!0,r:!0,s:!0,t:!0,tm:!0,u:!0,w:!0,x:!0,y:!0,z:!0},sg:{com:!0,edu:!0,gov:!0,idn:!0,net:!0,org:!0,per:!0},sn:{art:!0,com:!0,edu:!0,gouv:!0,org:!0,perso:!0,univ:!0},sy:{com:!0,edu:!0,gov:!0,mil:!0,
net:!0,news:!0,org:!0},th:{ac:!0,co:!0,go:!0,"in":!0,mi:!0,net:!0,or:!0},tj:{ac:!0,biz:!0,co:!0,com:!0,edu:!0,go:!0,gov:!0,info:!0,"int":!0,mil:!0,name:!0,net:!0,nic:!0,org:!0,test:!0,web:!0},tn:{agrinet:!0,com:!0,defense:!0,edunet:!0,ens:!0,fin:!0,gov:!0,ind:!0,info:!0,intl:!0,mincom:!0,nat:!0,net:!0,org:!0,perso:!0,rnrt:!0,rns:!0,rnu:!0,tourism:!0},tz:{ac:!0,co:!0,go:!0,ne:!0,or:!0},ua:{biz:!0,cherkassy:!0,chernigov:!0,chernovtsy:!0,ck:!0,cn:!0,co:!0,com:!0,crimea:!0,cv:!0,dn:!0,dnepropetrovsk:!0,
donetsk:!0,dp:!0,edu:!0,gov:!0,"if":!0,"in":!0,"ivano-frankivsk":!0,kh:!0,kharkov:!0,kherson:!0,khmelnitskiy:!0,kiev:!0,kirovograd:!0,km:!0,kr:!0,ks:!0,kv:!0,lg:!0,lugansk:!0,lutsk:!0,lviv:!0,me:!0,mk:!0,net:!0,nikolaev:!0,od:!0,odessa:!0,org:!0,pl:!0,poltava:!0,pp:!0,rovno:!0,rv:!0,sebastopol:!0,sumy:!0,te:!0,ternopil:!0,uzhgorod:!0,vinnica:!0,vn:!0,zaporizhzhe:!0,zhitomir:!0,zp:!0,zt:!0},ug:{ac:!0,co:!0,go:!0,ne:!0,or:!0,org:!0,sc:!0},uk:{ac:!0,bl:!0,"british-library":!0,co:!0,cym:!0,gov:!0,govt:!0,
icnet:!0,jet:!0,lea:!0,ltd:!0,me:!0,mil:!0,mod:!0,"national-library-scotland":!0,nel:!0,net:!0,nhs:!0,nic:!0,nls:!0,org:!0,orgn:!0,parliament:!0,plc:!0,police:!0,sch:!0,scot:!0,soc:!0},us:{dni:!0,fed:!0,isa:!0,kids:!0,nsn:!0},uy:{com:!0,edu:!0,gub:!0,mil:!0,net:!0,org:!0},ve:{co:!0,com:!0,edu:!0,gob:!0,info:!0,mil:!0,net:!0,org:!0,web:!0},vi:{co:!0,com:!0,k12:!0,net:!0,org:!0},vn:{ac:!0,biz:!0,com:!0,edu:!0,gov:!0,health:!0,info:!0,"int":!0,name:!0,net:!0,org:!0,pro:!0},ye:{co:!0,com:!0,gov:!0,ltd:!0,
me:!0,net:!0,org:!0,plc:!0},yu:{ac:!0,co:!0,edu:!0,gov:!0,org:!0},za:{ac:!0,agric:!0,alt:!0,bourse:!0,city:!0,co:!0,cybernet:!0,db:!0,edu:!0,gov:!0,grondar:!0,iaccess:!0,imt:!0,inca:!0,landesign:!0,law:!0,mil:!0,net:!0,ngo:!0,nis:!0,nom:!0,olivetti:!0,org:!0,pix:!0,school:!0,tm:!0,web:!0},zm:{ac:!0,co:!0,com:!0,edu:!0,gov:!0,net:!0,org:!0,sch:!0}};e.getSLD=function(a){if(e.isNil(a))return null;var d=a.split("."),c=d.length-2;if(0>c)return null;a=d[c];d=d[c+1];c=b[d];return e.isNil(c)||e.isNil(c[a])?
null:a+"."+d};e.depthOfTLDorSLD=function(a){if(e.isNil(a))return null;a=e.getSLD(a);return e.isntNil(a)?2:1};e.isInteger=function(a){return e.isNil(a)?!1:"number"===typeof a&&isFinite(a)&&Math.floor(a)===a};e.isSuccessCode=function(a){return e.isNil(a)?!1:a===c.httpStatusCodes.OK||a===c.httpStatusCodes.PARTIAL_CONTENT||a===c.httpStatusCodes.CREATED||a===c.httpStatusCodes.NO_CONTENT?!0:!1};e.safeFetch=function(a,d,b){d=void 0===d?{}:d;b=void 0===b?c.DEFAULT_FETCH_TIMEOUT:b;return new Promise(function(c,
e){var k=setTimeout(function(){e(Error("Request timed out "+a))},b);fetch(a,d).then(function(a){clearTimeout(k);c(a)}).catch(function(a){clearTimeout(k);e(a)})})};e.isSuccessCodeLocalFile=function(a){return e.isInteger(a)?"Safari"===f.globals.BROWSER&&0===a||a===c.httpStatusCodes.OK?!0:!1:!1};e.urlWithoutQueryParameters=function(a,b){e.isNil(b)&&(b=!0);if(e.isNil(a))return null;var d=new URI(a),c=d.protocol();if(e.isNil(c)||""===c||"http"!==c&&"https"!==c)c="http",d=new URI(c+"://"+a);a=d.hostname();
d=d.path();if(e.isNil(d)||"/"===d)d="";return b?c+"://"+a+d:a+d};e.baseURL=function(a){return e.isNil(a)?null:(new URI(a)).hostname()};e.pathName=function(a){return e.isNil(a)?null:(new URI(a)).pathname()};e.urlProtocol=function(a){if(e.isNil(a))return null;a=(new URI(a)).protocol();return""===a?null:a};e.getUrlTLD=function(a){if(e.isNil(a))return null;a=(new URI(a)).tld();return""===a?null:a};e.getCompanyDomain=function(a){if(e.isNil(a))return null;var d=(new URI(a)).hostname();a=e.getUrlTLD(a);
return""===d?null:e.isntNil(a)&&0<d.indexOf(a)?(d=d.substring(0,d.indexOf(a)-1).split("."),d[d.length-1]):d};e.getDomain=function(a){if(e.isNil(a))return null;a=(new URI(a)).domain();return""===a?null:a};e.isUrlAnIp=function(a){return e.isNil(a)?null:(new URI(a)).is(c.utils.IP)};e.appendToObject=function(a,d){if(e.isNil(a)||e.isNil(d))throw Error("invalid arguments to appendToObject");Object.keys(d).forEach(function(b){a[b]=d[b]})};e.createCustomHTMLEvent=function(a,b){if(!1===this.isString(a))throw Error("Event name cannot be null and has to be a string");
a=new CustomEvent(a,{detail:b});window.dispatchEvent(a)};e.isTopLevelWindow=function(){return"Edge"===f.globals.BROWSER?window.top.location==window.self.location?!0:!1:window.top==window.self?!0:!1};e.isNewVersionUpdated=function(a,b){b=b.split(".");a=a.split(".");var d=b[1]!==a[1];return b[0]!==a[0]||d?!0:!1};return e}(g.SymBfw)})(this);
(function(g){var f=Math.pow(2,31)-1;g.SymBfw.extensionAdapter=function(e){var c={},b=e.utils.isNil,a=e.utils.isntNil,d=e.utils.isString,g=e.utils.isInteger,h=e.utils.isFunction,l=e.utils.isArray;c.getLastError=function(){return chrome.runtime.lastError};c.getExtensionId=function(){return chrome.runtime.id};c.getBackgroundPage=function(){return b(chrome)||b(chrome.extension)?null:chrome.extension.getBackgroundPage()};c.getExtensionURL=function(a){if(b(chrome)||b(chrome.extension))throw Error("chrome or chrome.extension is null");
if(!d(a))throw Error("extensionAdapter.getExtensionURL expects a string path argument");return chrome.extension.getURL(a)};c.getAllWindows=function(a,d){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!h(a))throw Error("invalid arguments to extensionAdapter.getAllWindows");b(d)&&(d={});chrome.windows.getAll(d,a)};c.getCurrentWindow=function(a,d){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!h(a))throw Error("invalid arguments to extensionAdapter.getAllWindows");
b(d)&&(d={});chrome.windows.getCurrent(d,a)};c.createWindow=function(a,d,c){c=void 0===c?!0:c;if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");c={focused:c};b(a)||(c.url=a);chrome.windows.create(c,d)};c.createAppWindow=function(a,d){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");var k={};k.type=chrome.windows.CreateType.PANEL;b(a)||(k.url=a);chrome.windows.create(k,d)};c.createPrivateWindow=function(a,d,c){c=void 0===
c?!0:c;if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");c={incognito:!0,focused:c};b(a)||(c.url=a);chrome.windows.create(c,d)};c.closeWindow=function(a,d){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!g(a))throw Error("invalid arguments to extensionAdapter.closeWindow");chrome.windows.remove(a,d)};c.focusWindow=function(a,d){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!g(a))throw Error("invalid arguments to extensionAdapter.focusWindow");
chrome.windows.update(a,{focused:!0},d)};c.addWindowRemovedEventListener=function(a){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!h(a))throw Error("extensionAdapter.addWindowRemovedEventListener needs a callback");chrome.windows.onRemoved.addListener(a)};c.addWindowFocusedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.windows is null");if(!h(a))throw Error("extensionAdapter.addWindowFocusedEventListener needs a callback");
chrome.windows.onFocusChanged.addListener(a)};c.getTab=function(a,d){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!g(a)||!h(d))throw Error("invalid arguments to extensionAdapter.getTab");chrome.tabs.get(a,d)};c.getActiveTab=function(a,d){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!h(a))throw Error("invalid arguments to extensionAdapter.getActiveTab");var c={active:!0};g(d)?c.windowId=d:c.currentWindow=!0;chrome.tabs.query(c,
function(d){a(d[0])})};c.getAllTabs=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!h(a))throw Error("invalid arguments to extensionAdapter.getAllTabs");chrome.tabs.query({},a)};c.getTabsWithURL=function(a,c){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!d(a)||!h(c))throw Error("invalid arguments to extensionAdapter.getTabsWithURL");chrome.tabs.query({url:a},c)};c.updateTabUrl=function(a,c,e){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");
if(!g(a)||!d(c))throw Error("invalid arguments to extensionAdapter.updateTabUrl");chrome.tabs.update(a,{url:c},e)};c.activateTab=function(a,d){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(b(a)||!g(a))throw Error("invalid arguments to extensionAdapter.activateTab");chrome.tabs.update(a,{active:!0},d)};c.createTab=function(a,d,c){c=void 0===c?!0:c;if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");b(a)?chrome.tabs.create({},d):chrome.tabs.create({url:a,
active:c},d)};c.closeTab=function(a,d){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!g(a)&&!l(a))throw Error("invalid arguments to extensionAdapter.closeTab");chrome.tabs.remove(a,d)};c.closeTabAndEnsureBrowserIsAlive=function(d,b){if(!g(d)||0>=d||a(b)&&!h(b))throw Error("Invalid arguments to extensionAdapter.closeTabAndEnsureBrowserIsAlive()");c.getAllWindows(function(k){1===k.length?c.getAllTabs(function(k){1===k.length&&c.createTab();c.closeTab(d);a(b)&&
b()}):(c.closeTab(d),a(b)&&b())})};c.addTabRemovedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!h(a))throw Error("extensionAdapter.addTabRemovedEventListener needs a callback");chrome.tabs.onRemoved.addListener(a)};c.addTabActivatedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!h(a))throw Error("extensionAdapter.addTabActivatedEventListener needs a callback");chrome.tabs.onActivated.addListener(a)};
c.addTabReplacedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(b(a)||!h(a))throw Error("extensionAdapter.addTabReplacedEventListener needs a callback");chrome.tabs.onReplaced.addListener(a)};c.addTabUpdatedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");if(!h(a))throw Error("extensionAdapter.addTabUpdatedEventListener needs a callback");chrome.tabs.onUpdated.addListener(a)};
c.addOnBeforeRequestEventListener=function(a,d,c){if(b(chrome)||b(chrome.webRequest))throw Error("chrome is null or chrome.tabs is null");if(!1===h(a))throw Error("Callback cannot be null");chrome.webRequest.onBeforeRequest.addListener(a,{urls:d},c)};c.removeOnBeforeRequestEventListener=function(a){chrome.webRequest.onBeforeRequest.removeListener(a)};c.setBrowserIcon=function(a,d){if(b(chrome)||b(chrome.browserAction))throw Error("chrome is null or chrome.browserAction is null");if(b(a))throw Error("invalid arguments to extensionAdapter.setBrowserIcon");
chrome.browserAction.setIcon(a,d)};c.sendMessage=function(a,d){if(b(chrome)||b(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(b(a))throw Error("invalid arguments to extensionAdapter.sendMessage");chrome.runtime.sendMessage(a,d)};c.sendMessageExternal=function(a,d,c){if(b(chrome)||b(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(b(a))throw Error("invalid arguments to extensionAdapter.sendMessage");if(b(d))throw Error("invalid arguments to extensionAdapter.sendMessage");
chrome.runtime.sendMessage(a,d,c)};c.sendMessageToTab=function(a,d,c,e){if(b(chrome)||b(chrome.tabs))throw Error("chrome or chrome.tabs is null");if(b(d)||b(a))throw Error("invalid arguments to extensionAdapter.sendMessageToTab");chrome.tabs.sendMessage(a.id,d,e,c)};c.addMessageListener=function(a){if(b(chrome)||b(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(!h(a))throw Error("invalid arguments to extensionAdapter.addMessageListener");chrome.runtime.onMessage.addListener(function(d,
b,c){return a(d,c,b.tab)})};c.addMessageExternalListener=function(a){if(b(chrome)||b(chrome.runtime))throw Error("chrome or chrome.runtime is null");if(!h(a))throw Error("invalid arguments to extensionAdapter.addMessageExternalListener");chrome.runtime.onMessageExternal.addListener(function(d,b,c){return a(d,b,c)})};c.addContentScriptMessageListener=function(a){c.addMessageListener(a)};c.addTabCreatedEventListener=function(a){if(b(chrome)||b(chrome.tabs))throw Error("chrome is null or chrome.tabs is null");
if(!h(a))throw Error("extensionAdapter.\u200baddTabCreatedEventListener needs a callback");chrome.tabs.onCreated.addListener(a)};c.addWindowCreatedEventListener=function(a){if(b(chrome)||b(chrome.windows))throw Error("chrome is null or chrome.windows is null");if(!h(a))throw Error("extensionAdapter.\u200baddWindowCreatedEventListener needs a callback");chrome.windows.onCreated.addListener(a)};c.getTabID=function(a){return b(a)?null:a.id};c.getWindowIDForTab=function(a){return b(a)?null:a.windowId};
c.getWindowID=function(a){return b(a)?null:a.id};c.i18nGetMessage=function(a,c){if(b(window.chrome)||b(window.chrome.i18n))throw Error("Unsupported api");if(!d(a))throw Error("chrome.i18n.getMessage expects a string messageName argument");return chrome.i18n.getMessage(a,c)};c.hidePopup=function(){window.open("","_self").close()};c.setBadgeText=function(c,e){if(b(chrome)||b(chrome.browserAction))throw Error("chrome or chrome.browserAction is null");if(!d(c)||4<c.length)throw Error("invalid arguments to extensionAdapter.setBadgeText");
c={text:c};a(e)&&(c.tabId=e);chrome.browserAction.setBadgeText(c)};c.setBadgeBackgroundColor=function(a){if(b(chrome)||b(chrome.browserAction))throw Error("chrome or chrome.browserAction is null");if(!d(a))throw Error("invalid arguments to extensionAdapter.setBadgeBackgroundColor");chrome.browserAction.setBadgeBackgroundColor({color:a})};c.onPopoverLoad=function(a){window.addEventListener("load",a)};c.getAllHistory=function(){return new Promise(function(a){chrome.history.search({text:"",startTime:0,
maxResults:f},function(b){var c=[];b=$jscomp.makeIterator(b);for(var e=b.next();!e.done;e=b.next())e=e.value,d(e.url)&&c.push(e.url);a(c)})})};c.addUrlsToHistory=function(a){if(!l(a))throw Error("urls must be an array");var d=[];a=$jscomp.makeIterator(a);for(var b=a.next();!b.done;b=a.next())d.push(c.addUrlToHistory(b.value));return Promise.all(d)};c.clearHistory=function(){return new Promise(function(a){chrome.history.deleteAll(function(){a()})})};c.addUrlToHistory=function(a){if(!d(a))throw Error("url must be a string");
return new Promise(function(d){chrome.history.addUrl({url:a},function(){d()})})};c.getAllCookies=function(){return new Promise(function(a){chrome.cookies.getAll({},function(d){a(d)})})};c.removeCookie=function(a){if(b(a))throw Error("cookie cannot be null");var d=(a.secure?"https://":"http://")+a.domain+a.path;return new Promise(function(c,e){chrome.cookies.remove({name:a.name,url:d},function(a){b(a)&&e(chrome.runtime.lastError);c(a)})})};c.removeCookies=function(a){if(!l(a))throw Error("cookiesArray must be array");
var d=[];a=$jscomp.makeIterator(a);for(var b=a.next();!b.done;b=a.next())d.push(c.removeCookie(b.value));return Promise.all(d)};c.setCookie=function(c){if(b(c))throw Error("cookie cannot be null");var e={url:(new URL((c.secure?"https://":"http://")+c.domain)).toString(),httpOnly:c.httpOnly,name:c.name,sameSite:c.sameSite,secure:c.secure,storeId:c.storeId,value:c.value,path:c.path};d(c.domain)&&"."===c.domain.charAt()&&(e.domain=c.domain);a(c.expirationDate)&&(e.expirationDate=c.expirationDate);return new Promise(function(d,
c){chrome.cookies.set(e,function(e){var f=chrome.runtime.lastError;b(e)&&a(f)&&c(f);d(e)})})};c.setCookies=function(a){if(!l(a))throw Error("cookiesArray must be array");var d=[];a=$jscomp.makeIterator(a);for(var b=a.next();!b.done;b=a.next())d.push(c.setCookie(b.value));return Promise.all(d)};c.init=function(){};c.returnAdapter=function(){var a={};a.getExtensionURL=c.getExtensionURL;a.getBackgroundPage=c.getBackgroundPage;a.sendMessage=c.sendMessage;a.addMessageListener=c.addMessageListener;a.addContentScriptMessageListener=
c.addContentScriptMessageListener;a.getExtensionId=c.getExtensionId;a.init=c.init;try{return chrome.tabs?c:a}catch(p){return a}};return c.returnAdapter()}(g.SymBfw)})(this);
(function(g){g.SymBfw.clipboard=function(f){var e={},c=f.utils.isNil,b=f.logger;e.createDummyTextAreaAndSetText=function(a){var d=document.createElement("textarea");d.style.position="fixed";d.style.top=0;d.style.left=0;d.style.width="2em";d.style.height="2em";d.style.padding=0;d.style.border="none";d.style.outline="none";d.style.boxShadow="none";d.style.background="transparent";d.value=a;document.body.appendChild(d);d.select();return d};e.copyToClipboard=function(a){if(c(a)||""===a)throw Error("Value to copy to clipboard cannot be null");
a=e.createDummyTextAreaAndSetText(a);document.execCommand("copy")||b.error("Failed to copy to clipboard");document.body.removeChild(a)};return e}(g.SymBfw)})(this);
(function(g){g.SymBfw.localizerProxy=function(f){var e=f.utils.isNil,c=f.utils.isFunction,b=f.constants.localizer,a={getLocalizedString:function(d,c){a.sendMessage(b.GET_LOCALIZED_STRING,d,c)},getLocalizedStrings:function(d,c){a.sendMessage(b.GET_LOCALIZED_STRINGS,d,c)},getAllLocalizedStrings:function(d){a.sendMessage(b.GET_ALL_LOCALIZED_STRINGS,{},d)},getLocalizedStringFromDictionary:function(d,c,e){a.sendMessage(b.GET_LOCALIZED_STRING_FROM_DICTIONARY,{string:d,name:c},e)},getLocalizedStringsFromDictionary:function(d,
c,e){a.sendMessage(b.GET_LOCALIZED_STRINGS_FROM_DICTIONARY,{array:d,name:c},e)},getLocalizedStringWithFormat:function(d,c,e){a.sendMessage(b.GET_LOCALIZED_STRING_WITH_FORMAT,{string:d,params:c},e)},getLocalizedStringWithFormatFromDictionary:function(d,c,e,f){a.sendMessage(b.GET_LOCALIZED_STRING_WITH_FORMAT_FROM_DICTIONARY,{string:d,params:c,name:e},f)},getCurrentLanguageDirection:function(d){a.sendMessage(b.GET_CURRENT_LANGUAGE_DIRECTION,{},d)},sendMessage:function(a,g,h){if(e(a))throw Error("Message ID cannot be null");
if(e(g))throw Error("Payload cannot be null");if(!1===c(h))throw Error("Callback cannot be null");f.extensionAdapter.sendMessage({id:a,payload:g},function(a){switch(a.id){case b.GET_LOCALIZED_STRING:case b.GET_LOCALIZED_STRINGS:case b.GET_ALL_LOCALIZED_STRINGS:case b.GET_LOCALIZED_STRING_FROM_DICTIONARY:case b.GET_LOCALIZED_STRINGS_FROM_DICTIONARY:case b.GET_LOCALIZED_STRING_WITH_FORMAT:case b.GET_LOCALIZED_STRING_WITH_FORMAT_FROM_DICTIONARY:case b.GET_CURRENT_LANGUAGE_DIRECTION:h(a.payload)}})}};
return a}(g.SymBfw)})(this);
(function(g){g=g.SymBfw=g.SymBfw||{};var f={APPLICATION_NAME:"APPLICATION_NAME",APPLICATION_VERSION:"APPLICATION_VERSION",CLIENT_ID:"CLIENT_ID",DATA_SOURCE:"DATA_SOURCE",TRACKING_ID:"TRACKING_ID",USER_AGENT:"USER_AGENT",USER_LANGUAGE:"USER_LANGUAGE",GOOGLE_ANALYTICS_PROTOCOL_VERSION:"GOOGLE_ANALYTICS_PROTOCOL_VERSION",ANONYMIZE_IP:"ANONYMIZE_IP"};f.defaultParametersList=[f.APPLICATION_NAME,f.APPLICATION_VERSION,f.CLIENT_ID,f.DATA_SOURCE,f.TRACKING_ID,f.GOOGLE_ANALYTICS_PROTOCOL_VERSION,f.ANONYMIZE_IP];
f.dataSource={BROWSER_EXTENSION:"web",MOBILE_APP:"app"};f.HIT_TYPE={PAGE_VIEW:"pageview",SCREEN_VIEW:"screenview",EVENT:"event",EXCEPTION:"exception"};f.MESSAGES={SEND_TELEMETRY_TO_BGPROXY:"b021e29a-4fe3-4a60-865f-0cf783318187"};f.parameters={NON_INTERACTION_HIT:"ni",HIT_TYPE:"t",CATEGORY:"ec",ACTION:"ea",LABEL:"el",DOCUMENT_PATH:"dp",DOCUMENT_TITLE:"dt",CUSTOM_DIMENSION1:"cd1",PRODUCT_IMPRESSION_BRAND1:"il1pi1br",ITEM_CATEGORY:"iv",CAMPAIGN_SOURCE:"cs",CAMPAIGN_MEDIUM:"cm"};f.TELEMETRY_CATEGORY=
{BROWSER:"Browser",EXTENSION:"Extension"};f.actionType={BROWSER:{LAUNCH:"launch",UPDATE:"update"},EXTENSION:{INSTALL:"install",UPDATE:"update"}};f.defaultParameters={APPLICATION_NAME:{maxLength:100,key:"an"},APPLICATION_VERSION:{maxLength:100,key:"av"},CLIENT_ID:{maxLength:100,key:"cid"},DATA_SOURCE:{maxLength:50,key:"ds",value:f.dataSource.BROWSER_EXTENSION},TRACKING_ID:{maxLength:100,key:"tid"},USER_AGENT:{maxLength:1E3,key:"ua"},USER_LANGUAGE:{maxLength:20,key:"ul"},GOOGLE_ANALYTICS_PROTOCOL_VERSION:{maxLength:100,
key:"v",value:1},ANONYMIZE_IP:{maxLength:1,key:"aip",value:1}};g.telemetryConstants=f})(this);(function(g){g.SymBfw.telemetryProxy=function(f){var e=f.utils.isNil,c=f.telemetryConstants;return{send:function(b){if(e(b))throw Error("parameters cannot be null");f.extensionAdapter.sendMessage({id:c.MESSAGES.SEND_TELEMETRY_TO_BGPROXY,payload:{parameters:b}})}}}(g.SymBfw)})(this);
(function(g){g.SymBfw.telemetryWrapper=function(f){var e=f.utils.isNil,c=f.utils.isString,b={TELEMETRY_CATEGORY:"bfw",TELEMETRY_TYPE:"event",componentType:{LOGGER:"logger",LOCALIZER:"localizer",STORAGE:"storage",SETTINGS:"settings",SECURE_SETTINGS:"secureSettings"},actionType:{WARN:"warn",ERROR:"error"},parameters:{EVENT:"t",CATEGORY:"ec",ACTION:"ea",PAYLOAD:"el"},send:function(a,d,g){if(!c(a))throw Error("componentType should be a string");if(!c(d))throw Error("actionType should be a string");if(e(g))throw Error("payload should not be Nil");
if(!c(g)){if(!(g instanceof Error))throw Error("payload should be an instanceof Error other than a string");g=g.toString()}var h={};h[b.parameters.EVENT]=b.TELEMETRY_TYPE;h[b.parameters.CATEGORY]=b.TELEMETRY_CATEGORY+"-"+a;h[b.parameters.ACTION]=d;h[b.parameters.PAYLOAD]=g;return(f.telemetry||f.telemetryProxy).send(h)}};return b}(g.SymBfw)})(this);
(function(g){var f={},e=SymBfw.utils.isntNil,c=SymBfw.utils.isNil,b=SymBfw.localizerProxy,a=SymBfw.constants.uiConstants;f.direction="ltr";f.updateFrameSizeAndLocation=function(a,b,f,g){a=document.getElementById(a);c(a)||(e(f)&&a.setAttribute("width",f),e(b)&&a.setAttribute("height",b),e(g)&&a.setAttribute("style","left:"+g.left+"px;top:"+g.top+"px;"))};f.createFrame=function(a,c,g,l,k){b.getCurrentLanguageDirection(function(d){f.direction=d;var b=document.createElement("IFRAME");b.setAttribute("id",
a);b.setAttribute("src",c);b.setAttribute("class","symc-notification-hide");b.setAttribute("frameBorder",0);b.setAttribute("dir",d);e(l)&&b.setAttribute("width",l);e(g)&&b.setAttribute("height",g);e(k)&&b.setAttribute("style","left:"+k.left+"px;top:"+k.top+"px;");document.documentElement.appendChild(b);b.addEventListener("load",function(){"symc-in-page-popup"!==b.getAttribute("id")&&b.setAttribute("class","symc-notification-show")})})};f.getDirection=function(){return f.direction};f.injectStyle=function(d){var b=
document.documentElement,c=document.getElementById(a.CONTENT_PAGE_STYLE_ID);e(c)&&b.removeChild(c);c=document.createElement("LINK");c.setAttribute("id",a.CONTENT_PAGE_STYLE_ID);c.setAttribute("rel","stylesheet");c.setAttribute("href",d);b.appendChild(c)};f.isPageRTL=function(a){for(;e(a);){var b=a.getAttribute("dir");if(e(b)&&"rtl"===b)return!0;a=a.parentElement}return!1};f.isTopLevelWindow=function(){return window===window.top?!0:!1};g.SymBfw.uiUtils=f})(this);
(function(g){g.SymBfw.performanceReporterFactoryProxy=function(f){var e=f.utils.isNil,c=f.extensionAdapter,b=f.constants.performanceReporter.MESSAGES,a={AUTOMATION_MODE:!1,reportStart:function(d,c){a.sendMessage(b.REPORT_START,{component:d,type:c})},reportEnd:function(c,e){a.sendMessage(b.REPORT_END,{component:c,type:e})},sendMessage:function(b,g){if(!1!==a.AUTOMATION_MODE){if(e(b))throw Error("messageID cannot be null");if(e(g))throw Error("payload cannot be null");e(this._frameGUID)&&(this._frameGUID=
f.utils.createNewGuid());g.guid=this._frameGUID;g.frameURL=document.URL;c.sendMessage({id:b,payload:g})}}};return a}(g.SymBfw)})(this);
