(function(){function g(k,f,l){function h(a,b){if(!f[a]){if(!k[a]){var d="function"==typeof require&&require;if(!b&&d)return d(a,!0);if(c)return c(a,!0);b=Error("Cannot find module '"+a+"'");throw b.code="MODULE_NOT_FOUND",b;}b=f[a]={exports:{}};k[a][0].call(b.exports,function(b){return h(k[a][1][b]||b)},b,b.exports,g,k,f,l)}return f[a].exports}for(var c="function"==typeof require&&require,b=0;b<l.length;b++)h(l[b]);return h}return g})()({1:[function(g,k,f){function l(c,b){if("function"!==typeof b&&
null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);c.prototype=Object.create(b&&b.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(c,b):c.__proto__=b)}Object.defineProperty(f,"__esModule",{value:!0});var h=function(){function c(b,a){for(var c=0;c<a.length;c++){var d=a[c];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(b,d.key,
d)}}return function(b,a,f){a&&c(b.prototype,a);f&&c(b,f);return b}}();g=function(c){function b(a){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");a=(b.__proto__||Object.getPrototypeOf(b)).call(this,a);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!a||"object"!==typeof a&&"function"!==typeof a?this:a}l(b,c);h(b,[{key:"render",value:function(){var b=null;this.props.isChecked&&(b="../images/btn-global-checked.svg");
this.props.isChecked||(b="../images/btn-global-unchecked.svg");return React.createElement("div",{className:"checkbox-container"},React.createElement("img",{src:b}))}}]);return b}(React.Component);f.default=g},{}],2:[function(g,k,f){function l(c,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);c.prototype=Object.create(b&&b.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?
Object.setPrototypeOf(c,b):c.__proto__=b)}Object.defineProperty(f,"__esModule",{value:!0});var h=function(){function c(b,a){for(var c=0;c<a.length;c++){var d=a[c];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(b,d.key,d)}}return function(b,a,f){a&&c(b.prototype,a);f&&c(b,f);return b}}();g=React.PropTypes;k=function(c){function b(a){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");a=(b.__proto__||Object.getPrototypeOf(b)).call(this,
a);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");a=!a||"object"!==typeof a&&"function"!==typeof a?this:a;a.state={isPopupShown:!1};a._togglePopupDisplay=a._togglePopupDisplay.bind(a);a._hidePopup=a._hidePopup.bind(a);return a}l(b,c);h(b,[{key:"componentDidMount",value:function(){window.addEventListener("click",this._hidePopup)}},{key:"componentWillUnmount",value:function(){window.removeEventListener("click",this._hidePopup)}},{key:"_hidePopup",value:function(){!0===
this.state.isPopupShown&&this.setState({isPopupShown:!1})}},{key:"_togglePopupDisplay",value:function(b){b.stopPropagation();this.setState({isPopupShown:!this.state.isPopupShown})}},{key:"render",value:function(){return React.createElement("div",{className:"product-header"},React.createElement("div",{className:"norton-image"}),React.createElement("div",{className:"header-divider"}),React.createElement("div",{className:"product-header-title"},this.props.strings[this.props.productName]),this.props.isLoggedIn?
React.createElement("div",{className:"header-email",onClick:this._togglePopupDisplay},this.props.email):null,this.props.isLoggedIn&&this.state.isPopupShown?React.createElement("div",{className:"popup"},React.createElement("img",{src:"../images/bg-popup.svg"}),React.createElement("span",{className:"sign-out-popup",onClick:this.props.signOutClicked},this.props.strings["Sign out"])):null)}}]);return b}(React.Component);f.default=k;k.propTypes={event:g.shape({signOutClicked:g.func}),className:g.shape({"norton-image":g.string,
"header-divider":g.string,"product-header-title":g.string}),optionalContent:g.shape({isLoggedIn:g.bool,email:g.string})}},{}],3:[function(g,k,f){(function(k){function h(b){return b&&b.__esModule?b:{default:b}}function c(b,a){if(!(b instanceof a))throw new TypeError("Cannot call a class as a function");}function b(b,a){if(!b)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!a||"object"!==typeof a&&"function"!==typeof a?b:a}function a(b,a){if("function"!==
typeof a&&null!==a)throw new TypeError("Super expression must either be null or a function, not "+typeof a);b.prototype=Object.create(a&&a.prototype,{constructor:{value:b,enumerable:!1,writable:!0,configurable:!0}});a&&(Object.setPrototypeOf?Object.setPrototypeOf(b,a):b.__proto__=a)}Object.defineProperty(f,"__esModule",{value:!0});f.PrivacyContainer=f.GDPRContainer=f.UserLogInContainer=f.SettingsHeading=void 0;var n=function(){function b(b,a){for(var c=0;c<a.length;c++){var m=a[c];m.enumerable=m.enumerable||
!1;m.configurable=!0;"value"in m&&(m.writable=!0);Object.defineProperty(b,m.key,m)}}return function(a,m,c){m&&b(a.prototype,m);c&&b(a,c);return a}}(),d=g("./header.jsx"),l=h(d);d=g("./checkbox.jsx");var t=h(d);d=g("./utils.jsx");var u=h(d),p=NSSS.uiConstants.MESSAGES,q=SymBfw.extensionAdapter,v=SymBfw.utils.isntNil,w=NSSS.constants,x=f.SettingsHeading=function(d){function e(a){c(this,e);return b(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,a))}a(e,d);n(e,[{key:"render",value:function(){return React.createElement("div",
{className:"settings-text"},this.props.strings.Settings)}}]);return e}(React.Component),y=f.UserLogInContainer=function(d){function e(a){c(this,e);return b(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,a))}a(e,d);n(e,[{key:"render",value:function(){return React.createElement("div",{className:"signed-in-detail"},React.createElement("div",{className:"signed-in-as logged-in-email"},this.props.strings["Signed in as"],":\u00a0"),React.createElement("div",{className:"logged-in-email settings-email"},
this.props.email),React.createElement("div",{className:"logged-in-email vertical-divider"},"\u00a0|\u00a0"),React.createElement("div",{className:"logged-in-email sign-out",onClick:this.props.signOutClicked},this.props.strings["Sign out"]))}}]);return e}(React.Component),z=f.GDPRContainer=function(d){function e(a){c(this,e);a=b(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,a));a.state={isSharingData:a.props.isTelemetryEnabled};a._toggleCheckbox=a._toggleCheckbox.bind(a);return a}a(e,d);n(e,
[{key:"_toggleCheckbox",value:function(){this.setState({isSharingData:!this.state.isSharingData});q.sendMessage({name:p.SET_TELEMETRY_ENABLED,message:!this.state.isSharingData})}},{key:"render",value:function(){return React.createElement("div",{className:"gdpr-container"},React.createElement("div",{className:"share-data-title"},this.props.strings["Share Data with Norton"]),React.createElement("div",{className:"horizontal-divider"}),React.createElement("div",{className:"share-data-content"},React.createElement("div",
{className:"gdpr-checkbox",onClick:this._toggleCheckbox},React.createElement(t.default,{isChecked:this.state.isSharingData})),React.createElement("div",{className:"share-data-text"},this.props.strings["Share usage and error data anonymously with Norton and help us make our products even better"])))}}]);return e}(React.Component),A=f.PrivacyContainer=function(d){function e(a){c(this,e);a=b(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,a));a._privacyPolicyClicked=a._privacyPolicyClicked.bind(a);
return a}a(e,d);n(e,[{key:"_privacyPolicyClicked",value:function(){q.sendMessage({name:p.SETTINGS_PRIVACY_POLICY})}},{key:"render",value:function(){return React.createElement("div",{className:"privacy-container",onClick:this._privacyPolicyClicked},this.props.strings["Privacy Policy"])}}]);return e}(React.Component),r=function(d){function e(a){c(this,e);a=b(this,(e.__proto__||Object.getPrototypeOf(e)).call(this,a));a.state={isLoggedIn:a.props.isLoggedIn,email:a.props.email};a.props.direction&&u.default.setDirection(a.props.direction);
a.handleSignOutClicked=a.handleSignOutClicked.bind(a);return a}a(e,d);n(e,[{key:"handleSignOutClicked",value:function(){var a=this;q.sendMessage({name:p.SIGN_OUT},function(b){b.isLogoutSuccess&&a.setState({isLoggedIn:!1,email:null})})}},{key:"render",value:function(){return React.createElement("div",null,React.createElement(l.default,{isLoggedIn:this.state.isLoggedIn,email:this.state.email,signOutClicked:this.handleSignOutClicked,strings:this.props.strings,productName:this.props.productName}),React.createElement("div",
{className:"settings-container"},React.createElement(x,{strings:this.props.strings}),this.state.isLoggedIn?React.createElement(y,{signOutClicked:this.handleSignOutClicked,email:this.state.email,strings:this.props.strings}):null,React.createElement(z,{strings:this.props.strings,isTelemetryEnabled:this.props.isTelemetryEnabled}),React.createElement(A,{strings:this.props.strings})))}}]);return e}(React.Component);f.default=r;(function(){var a={show:function(){var a=w.PRODUCT_NAME.substring(7);q.sendMessage({name:p.SETTINGS_PAGE_UI_INIT},
function(b){v(b)&&ReactDOM.render(React.createElement(r,{isLoggedIn:b.isLoggedIn,email:b.email,strings:b.strings,direction:b.direction,productName:a,isTelemetryEnabled:b.isTelemetryEnabled}),document.getElementById("container"))})}};k.NSSS.showSettingsUI=a;a.show()})()}).call(this,"undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{})},{"./checkbox.jsx":1,"./header.jsx":2,"./utils.jsx":4}],4:[function(g,k,f){Object.defineProperty(f,"__esModule",{value:!0});
var l=function(){function c(b,a){for(var c=0;c<a.length;c++){var d=a[c];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(b,d.key,d)}}return function(b,a,f){a&&c(b.prototype,a);f&&c(b,f);return b}}(),h=SymBfw.utils.isntNil;g=function(){function c(){if(!(this instanceof c))throw new TypeError("Cannot call a class as a function");}l(c,null,[{key:"setDirection",value:function(b){var a=document.getElementsByTagName("body");h(a)&&h(a[0])&&a[0].setAttribute("dir",
b)}}]);return c}();f.default=g},{}]},{},[3]);
